<?php
declare(strict_types=1);

namespace Rateb\App\Core;

use PDO;

/**
 * Phase D — Enterprise Branch Appliance cold-start installer (Core orchestrator).
 * Reuses HybridRuntime, SqliteSchemaBootstrap, BranchSeedService, HybridSync*.
 * No Controllers/Services/Models changes. Cold-start only — no Internet required.
 */
final class BranchApplianceInstaller
{
    public const MIN_PHP = '8.1.0';

    /** @var list<string> */
    public const REQUIRED_EXTENSIONS = [
        'pdo',
        'pdo_sqlite',
        'sqlite3',
        'json',
        'gd',
    ];

    /** @var list<string> */
    public const RECOMMENDED_EXTENSIONS = [
        'mbstring',
        'openssl',
    ];

    /**
     * @param array{force?:bool,company?:string} $options
     * @return array{ok:bool,steps:list<array{id:string,ok:bool,detail:string}>,report:array<string,mixed>}
     */
    public function install(array $options = []): array
    {
        $force = !empty($options['force']);
        $steps = [];
        $fail = static function (string $id, string $detail) use (&$steps): array {
            $steps[] = ['id' => $id, 'ok' => false, 'detail' => $detail];

            return ['ok' => false, 'steps' => $steps, 'report' => ['failed_at' => $id]];
        };

        // PHP version
        $phpOk = version_compare(PHP_VERSION, self::MIN_PHP, '>=');
        $steps[] = ['id' => 'php_version', 'ok' => $phpOk, 'detail' => PHP_VERSION];
        if (!$phpOk) {
            return $fail('php_version', 'Need PHP ' . self::MIN_PHP . '+');
        }

        // Extensions
        $missingExt = [];
        foreach (self::REQUIRED_EXTENSIONS as $ext) {
            if (!extension_loaded($ext)) {
                $missingExt[] = $ext;
            }
        }
        $steps[] = [
            'id' => 'php_extensions',
            'ok' => $missingExt === [],
            'detail' => $missingExt === [] ? 'all present' : 'missing:' . implode(',', $missingExt),
        ];
        if ($missingExt !== []) {
            return $fail('php_extensions', implode(',', $missingExt));
        }
        $missingRec = [];
        foreach (self::RECOMMENDED_EXTENSIONS as $ext) {
            if (!extension_loaded($ext)) {
                $missingRec[] = $ext;
            }
        }
        $steps[] = [
            'id' => 'php_extensions_recommended',
            'ok' => true,
            'detail' => $missingRec === [] ? 'openssl present' : 'optional_missing:' . implode(',', $missingRec),
        ];

        // SQLite support
        $sqliteOk = HybridRuntime::sqliteExtensionAvailable()
            && class_exists(\PDO::class);
        $steps[] = ['id' => 'sqlite_support', 'ok' => $sqliteOk, 'detail' => $sqliteOk ? 'pdo_sqlite' : 'unavailable'];
        if (!$sqliteOk) {
            return $fail('sqlite_support', 'pdo_sqlite required');
        }

        // Directories + permissions
        $layout = BranchAppliancePaths::ensureLayout();
        $permOk = !in_array(false, $layout, true);
        $steps[] = ['id' => 'filesystem_permissions', 'ok' => $permOk, 'detail' => json_encode($layout) ?: ''];
        if (!$permOk) {
            return $fail('filesystem_permissions', 'branch storage not writable');
        }

        $sqlitePath = HybridRuntime::sqlitePath();
        if (is_file($sqlitePath) && $force) {
            Database::disconnect();
            @unlink($sqlitePath);
            @unlink($sqlitePath . '-wal');
            @unlink($sqlitePath . '-shm');
        }
        if (is_file($sqlitePath) && !$force) {
            $steps[] = ['id' => 'sqlite_exists', 'ok' => true, 'detail' => 'reuse existing (pass force to recreate)'];
        }

        // Identity + keys (cold-start, offline)
        $identity = (new BranchRegistration())->ensureLocalIdentity();
        $steps[] = [
            'id' => 'device_identity',
            'ok' => ($identity['branch_uuid'] ?? '') !== '',
            'detail' => 'branch=' . ($identity['branch_uuid'] ?? ''),
        ];
        $syncKey = bin2hex(random_bytes(32));
        file_put_contents(BranchAppliancePaths::identityDir() . '/sync.key', $syncKey);
        @chmod(BranchAppliancePaths::identityDir() . '/sync.key', 0600);
        $steps[] = ['id' => 'encryption_keys', 'ok' => is_file(BranchAppliancePaths::identityDir() . '/sync.key'), 'detail' => 'sync.key'];

        $sink = strtolower((string) ($options['sink'] ?? 'mysql'));
        if ($sink !== 'mysql' && $sink !== 'mirror') {
            $sink = 'mysql';
        }
        $mirrorLine = '';
        if ($sink === 'mirror') {
            $mirror = (string) ($options['mirror'] ?? (BranchAppliancePaths::root() . '/cloud-mirror.sqlite'));
            $mirrorLine = 'RATEB_HYBRID_SYNC_MIRROR=' . $mirror;
        }

        // serve.env — Hybrid Runtime + Sync Engine + Sync Service
        $envLines = [
            '# Generated by BranchApplianceInstaller (Phase D) — local appliance only',
            'RATEB_RUNTIME=branch',
            'RATEB_ALLOW_RUNTIME_MARKER=1',
            'RATEB_SQLITE_PATH=' . $sqlitePath,
            'RATEB_DEPLOYMENT=',
            'RATEB_ERP_PUBLIC_PREFIX=',
            'RATEB_HYBRID_SYNC_ENABLED=1',
            'RATEB_HYBRID_SYNC_SINK=' . $sink,
            'RATEB_HYBRID_SYNC_KEY=' . $syncKey,
            'RATEB_HYBRID_SYNC_PULL_ENTITIES=rateb_plans,rateb_permissions,rateb_warehouses',
            'RATEB_BRANCH_UUID=' . ($identity['branch_uuid'] ?? ''),
            'RATEB_DEVICE_UUID=' . ($identity['device_uuid'] ?? ''),
        ];
        if ($mirrorLine !== '') {
            $envLines[] = $mirrorLine;
        }
        $envLines[] = '';
        $serveEnv = BranchAppliancePaths::serveEnv();
        file_put_contents($serveEnv, implode("\n", $envLines));
        // Global runtime.mode is only for the default storage/branch appliance path.
        // Isolated SQLITE_PATH trees must not pollute the shared marker (breaks cloud-mode checks).
        $erpRoot = defined('RATEB_ROOT') ? str_replace('\\', '/', (string) RATEB_ROOT) : str_replace('\\', '/', dirname(__DIR__, 2));
        $defaultStorage = $erpRoot . '/storage/branch';
        if (HybridRuntime::branchStorageDir() === $defaultStorage) {
            file_put_contents(HybridRuntime::runtimeMarkerPath(), "branch\n");
        }
        $steps[] = ['id' => 'generate_env', 'ok' => is_file($serveEnv), 'detail' => $serveEnv];
        $steps[] = ['id' => 'configure_hybrid_runtime', 'ok' => true, 'detail' => 'RATEB_RUNTIME=branch'];
        $steps[] = ['id' => 'configure_sync_engine', 'ok' => true, 'detail' => 'RATEB_HYBRID_SYNC_ENABLED=1'];
        $steps[] = ['id' => 'configure_sync_service', 'ok' => true, 'detail' => 'sink=mysql key=set'];

        foreach ($envLines as $line) {
            if ($line === '' || str_starts_with($line, '#') || !str_contains($line, '=')) {
                continue;
            }
            [$k, $v] = array_pad(explode('=', $line, 2), 2, '');
            putenv($k . '=' . $v);
            $_ENV[$k] = $v;
        }
        HybridRuntime::reset();
        Database::disconnect();
        HybridSyncOutboxCapture::resetConnection();

        if (!HybridRuntime::shouldUseSqlite()) {
            return $fail('configure_hybrid_runtime', 'SQLite not selected after env');
        }

        // Create DB + schema + seed
        $pdo = Database::connection();
        $journal = (string) $pdo->query('PRAGMA journal_mode')->fetchColumn();
        $busy = (string) $pdo->query('PRAGMA busy_timeout')->fetchColumn();
        $steps[] = ['id' => 'create_sqlite', 'ok' => is_file($sqlitePath), 'detail' => "journal={$journal} busy={$busy}"];

        $schema = SqliteSchemaBootstrap::ensureErpSchema($pdo);
        $tables = SqliteSchemaBootstrap::countUserTables($pdo);
        $schemaOk = $tables >= 100;
        $steps[] = [
            'id' => 'apply_schema',
            'ok' => $schemaOk,
            'detail' => 'tables=' . $tables . ' version=' . ($schema['version'] ?? ''),
        ];
        if (!$schemaOk) {
            return $fail('apply_schema', 'incomplete schema');
        }

        $company = (string) ($options['company'] ?? BranchSeedService::DEFAULT_COMPANY);
        $seed = BranchSeedService::seedMinimalTenant($pdo, $company);
        $steps[] = [
            'id' => 'seed_administrator',
            'ok' => ($seed['user_id'] ?? 0) > 0,
            'detail' => 'user=' . ($seed['email'] ?? '') . ' / ' . ($seed['password'] ?? ''),
        ];

        SqliteSchemaBootstrap::upsertMeta($pdo, 'hybrid_phase', 'D');
        SqliteSchemaBootstrap::upsertMeta($pdo, 'branch_uuid', (string) ($identity['branch_uuid'] ?? ''));
        SqliteSchemaBootstrap::upsertMeta($pdo, 'device_uuid', (string) ($identity['device_uuid'] ?? ''));
        SqliteSchemaBootstrap::upsertMeta($pdo, 'appliance_installed_at', gmdate('c'));
        SqliteSchemaBootstrap::upsertMeta($pdo, 'appliance_version', BranchAppliancePaths::readVersion());

        // Verify installation
        $verify = $this->verifyInstallation($pdo, $seed, $identity);
        $steps[] = ['id' => 'verify_installation', 'ok' => $verify['ok'], 'detail' => $verify['detail']];
        if (!$verify['ok']) {
            return ['ok' => false, 'steps' => $steps, 'report' => $verify];
        }

        $report = [
            'sqlite' => $sqlitePath,
            'serve_env' => $serveEnv,
            'branch_uuid' => $identity['branch_uuid'] ?? '',
            'device_uuid' => $identity['device_uuid'] ?? '',
            'login_email' => $seed['email'] ?? '',
            'login_password' => $seed['password'] ?? '',
            'tables' => $tables,
            'version' => BranchAppliancePaths::readVersion(),
            'cold_start' => true,
            'internet_required' => false,
        ];
        @file_put_contents(
            BranchAppliancePaths::root() . '/diagnostics/last-install.json',
            json_encode(['ok' => true, 'steps' => $steps, 'report' => $report], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
        );

        return ['ok' => true, 'steps' => $steps, 'report' => $report];
    }

    /**
     * @param array<string,mixed> $seed
     * @param array<string,mixed> $identity
     * @return array{ok:bool,detail:string}
     */
    private function verifyInstallation(PDO $pdo, array $seed, array $identity): array
    {
        $checks = [];
        $checks['sqlite_file'] = is_file(HybridRuntime::sqlitePath());
        $checks['serve_env'] = is_file(BranchAppliancePaths::serveEnv());
        $checks['runtime_branch'] = HybridRuntime::shouldUseSqlite();
        $checks['sync_enabled'] = HybridSyncConfig::enabled();
        $checks['admin_user'] = ((int) ($seed['user_id'] ?? 0)) > 0;
        $checks['branch_uuid'] = (($identity['branch_uuid'] ?? '') !== '');
        $integrity = (string) $pdo->query('PRAGMA integrity_check')->fetchColumn();
        $checks['integrity'] = strtoupper($integrity) === 'OK';
        $ok = !in_array(false, $checks, true);

        return ['ok' => $ok, 'detail' => json_encode($checks) ?: ''];
    }
}
