<?php
/**
 * PERF-P1 — Generate classmap for multi-class PHP bags so Bootstrap can stop eager require_once.
 * Run: php rateb-erp/tools/generate-erp-classmap.php
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$outFile = $root . '/app/Core/generated-classmap.php';

$scanDirs = [
    $root . '/app/controllers',
    $root . '/app/models',
    $root . '/app/services',
    $root . '/app/helpers',
    $root . '/app/Core',
    $root . '/app/Support',
    $root . '/app/Website',
];

$map = [];
$filesScanned = 0;
$multiFiles = 0;

$iterator = function (string $dir) use (&$iterator): Generator {
    if (!is_dir($dir)) {
        return;
    }
    $dh = opendir($dir);
    if ($dh === false) {
        return;
    }
    while (($entry = readdir($dh)) !== false) {
        if ($entry === '.' || $entry === '..') {
            continue;
        }
        $path = $dir . DIRECTORY_SEPARATOR . $entry;
        if (is_dir($path)) {
            yield from $iterator($path);
            continue;
        }
        if (substr($entry, -4) !== '.php') {
            continue;
        }
        yield $path;
    }
    closedir($dh);
};

foreach ($scanDirs as $dir) {
    foreach ($iterator($dir) as $path) {
        $filesScanned++;
        $code = file_get_contents($path);
        if ($code === false) {
            continue;
        }
        if (!preg_match('/namespace\s+([^;]+);/', $code, $nsMatch)) {
            continue;
        }
        $ns = trim($nsMatch[1]);
        preg_match_all('/^\s*(?:final\s+|abstract\s+)?class\s+(\w+)/m', $code, $cm);
        $classes = $cm[1] ?? [];
        if (count($classes) === 0) {
            continue;
        }
        $bn = basename($path, '.php');
        /* Map multi-class bags AND single-class files whose filename ≠ class name
         * (e.g. BusinessControllers.php → ExecutiveDashboardController). */
        if (count($classes) === 1 && strcasecmp($classes[0], $bn) === 0) {
            continue;
        }
        if (count($classes) > 1) {
            $multiFiles++;
        }
        $rel = str_replace('\\', '/', substr($path, strlen($root)));
        if ($rel === '' || $rel[0] !== '/') {
            $rel = '/' . ltrim($rel, '/');
        }
        /* Windows paths: strip drive if present after root strip */
        if (preg_match('#^[A-Za-z]:/#', $rel)) {
            $rel = str_replace('\\', '/', substr($path, strlen(str_replace('\\', '/', $root))));
            if ($rel === '' || $rel[0] !== '/') {
                $rel = '/' . ltrim(str_replace('\\', '/', $rel), '/');
            }
        }
        foreach ($classes as $short) {
            $fqcn = $ns . '\\' . $short;
            $map[$fqcn] = $rel;
        }
    }
}

ksort($map);

$export = var_export($map, true);
$generated = <<<PHP
<?php
/**
 * AUTO-GENERATED by tools/generate-erp-classmap.php — do not edit by hand.
 * Multi-class bag → file map for PERF-P1 lazy Bootstrap (no eager require_once).
 */
declare(strict_types=1);

return {$export};

PHP;

if (file_put_contents($outFile, $generated) === false) {
    fwrite(STDERR, "Failed writing {$outFile}\n");
    exit(1);
}

fwrite(STDOUT, json_encode([
    'ok' => true,
    'out' => $outFile,
    'files_scanned' => $filesScanned,
    'multi_class_files' => $multiFiles,
    'mapped_classes' => count($map),
], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n");
