<?php
declare(strict_types=1);

/**
 * Help Center article blueprints. Expanded into full bilingual articles by HelpContentBuilder.
 *
 * Each module defines a cycle (flow) + concrete article blueprints.
 *
 * @return array<string, array{flow_ar:list<string>,flow_en:list<string>,overview_ar:string,overview_en:string,start_ar:list<string>,start_en:list<string>,articles:list<array<string,mixed>>}>
 */
return [
    'dashboard' => [
        'flow_ar' => ['فتح لوحة التحكم', 'مراجعة المؤشرات', 'استخدام الاختصارات', 'الانتقال للوحدة'],
        'flow_en' => ['Open dashboard', 'Review KPIs', 'Use shortcuts', 'Jump to module'],
        'overview_ar' => 'لوحة التحكم تعطيك صورة سريعة عن أداء الشركة والاختصارات لأهم العمليات.',
        'overview_en' => 'The dashboard gives a quick view of company performance and shortcuts to key operations.',
        'start_ar' => ['سجّل الدخول وافتح لوحة التحكم', 'راجع بطاقات الملخص', 'استخدم أزرار الإجراءات السريعة'],
        'start_en' => ['Sign in and open the dashboard', 'Review summary cards', 'Use quick-action buttons'],
        'articles' => [
            ['slug' => 'dashboard-overview', 'title_ar' => 'نظرة عامة على لوحة التحكم', 'title_en' => 'Dashboard overview', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['لوحة التحكم', 'dashboard', 'kpi', 'مؤشرات'], 'icon' => 'fa-gauge-high'],
            ['slug' => 'dashboard-quick-actions', 'title_ar' => 'الاختصارات والإجراءات السريعة', 'title_en' => 'Quick actions', 'difficulty' => 'beginner', 'minutes' => 2, 'keywords' => ['اختصار', 'إضافة مستخدم', 'quick action'], 'icon' => 'fa-bolt'],
            ['slug' => 'dashboard-charts', 'title_ar' => 'قراءة الرسوم البيانية', 'title_en' => 'Reading charts', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['رسم', 'chart', 'نمو', 'growth'], 'icon' => 'fa-chart-column', 'audience' => 'manager'],
        ],
    ],
    'sales-screen' => [
        'flow_ar' => ['عميل', 'بيع', 'فاتورة', 'دفع', 'خصم المخزون', 'تقرير'],
        'flow_en' => ['Customer', 'Sale', 'Invoice', 'Payment', 'Stock deduct', 'Report'],
        'overview_ar' => 'شاشة البيع تمكّنك من إتمام عملية بيع كاملة بسرعة مع تحديث المخزون تلقائياً.',
        'overview_en' => 'The sales screen lets you complete a full sale quickly with automatic stock updates.',
        'start_ar' => ['افتح شاشة البيع', 'اختر العميل أو بيع نقدي', 'أضف الأصناف وأكمل الدفع'],
        'start_en' => ['Open the sales screen', 'Select customer or cash sale', 'Add items and complete payment'],
        'articles' => [
            ['slug' => 'sales-cycle', 'title_ar' => 'دورة المبيعات', 'title_en' => 'Sales cycle', 'difficulty' => 'beginner', 'minutes' => 5, 'keywords' => ['مبيعات', 'فاتورة', 'بيع', 'sales', 'invoice'], 'icon' => 'fa-arrows-spin'],
            ['slug' => 'sales-create-invoice', 'title_ar' => 'إنشاء فاتورة بيع', 'title_en' => 'Create a sales invoice', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['فاتورة بيع', 'sales invoice', 'فاتورة'], 'icon' => 'fa-file-invoice'],
            ['slug' => 'sales-payment', 'title_ar' => 'تسجيل الدفع في البيع', 'title_en' => 'Record sales payment', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['دفع', 'payment', 'نقد', 'بطاقة'], 'icon' => 'fa-credit-card'],
        ],
    ],
    'branches' => [
        'flow_ar' => ['إنشاء فرع', 'تعيين صلاحيات', 'مخزون الفرع', 'تحويل بين الفروع', 'تقارير الفرع'],
        'flow_en' => ['Create branch', 'Assign access', 'Branch stock', 'Inter-branch transfer', 'Branch reports'],
        'overview_ar' => 'وحدة الفروع تدير مواقع العمل المتعددة مع فصل الصلاحيات والمخزون والتقارير.',
        'overview_en' => 'Branches manage multi-location operations with separated access, stock, and reports.',
        'start_ar' => ['أنشئ الفرع الجديد', 'اربط المستخدمين بالفرع', 'فعّل فلتر الفرع من الشريط العلوي'],
        'start_en' => ['Create the new branch', 'Link users to the branch', 'Enable the branch filter in the top bar'],
        'articles' => [
            ['slug' => 'branches-create', 'title_ar' => 'إضافة فرع جديد', 'title_en' => 'Add a new branch', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['فرع', 'branch', 'إضافة فرع'], 'icon' => 'fa-store'],
            ['slug' => 'branches-access', 'title_ar' => 'صلاحيات الوصول للفروع', 'title_en' => 'Branch access permissions', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['صلاحية فرع', 'branch access'], 'icon' => 'fa-user-lock', 'audience' => 'admin'],
            ['slug' => 'branches-transfer', 'title_ar' => 'التحويل بين الفروع', 'title_en' => 'Inter-branch transfers', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['تحويل فرع', 'branch transfer'], 'icon' => 'fa-right-left'],
        ],
    ],
    'purchases' => [
        'flow_ar' => ['طلب شراء', 'موافقة', 'RFQ', 'اختيار المورد', 'أمر شراء', 'الاستلام', 'الفاتورة', 'الدفع'],
        'flow_en' => ['Purchase request', 'Approval', 'RFQ', 'Supplier selection', 'Purchase order', 'Receipt', 'Invoice', 'Payment'],
        'overview_ar' => 'المشتريات تغطي الدورة الكاملة من الحاجة حتى الدفع مع ضوابط الموافقة والموردين.',
        'overview_en' => 'Purchases covers the full cycle from need to payment with approvals and supplier controls.',
        'start_ar' => ['أنشئ طلب شراء', 'انتظر الموافقة', 'حوّل الطلب إلى أمر شراء بعد اختيار المورد'],
        'start_en' => ['Create a purchase request', 'Wait for approval', 'Convert to PO after supplier selection'],
        'articles' => [
            ['slug' => 'purchases-cycle', 'title_ar' => 'دورة المشتريات', 'title_en' => 'Purchasing cycle', 'difficulty' => 'beginner', 'minutes' => 6, 'keywords' => ['دورة المشتريات', 'مشتريات', 'procurement', 'purchase cycle'], 'icon' => 'fa-arrows-spin'],
            ['slug' => 'purchases-request', 'title_ar' => 'كيف أنشئ طلب شراء؟', 'title_en' => 'How do I create a purchase request?', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['طلب شراء', 'purchase request', 'PR'], 'icon' => 'fa-file-circle-plus'],
            ['slug' => 'purchases-rfq', 'title_ar' => 'كيف أنشئ RFQ؟', 'title_en' => 'How do I create an RFQ?', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['RFQ', 'طلب عرض سعر', 'quotation request'], 'icon' => 'fa-envelope-open-text'],
            ['slug' => 'purchases-order', 'title_ar' => 'كيف أنشئ أمر شراء؟', 'title_en' => 'How do I create a purchase order?', 'difficulty' => 'beginner', 'minutes' => 5, 'keywords' => ['أمر شراء', 'purchase order', 'PO'], 'icon' => 'fa-file-invoice-dollar'],
            ['slug' => 'purchases-receipt', 'title_ar' => 'كيف أسجل الاستلام؟', 'title_en' => 'How do I record goods receipt?', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['استلام', 'receipt', 'GRN'], 'icon' => 'fa-box-open'],
            ['slug' => 'purchases-supplier-invoice', 'title_ar' => 'كيف أتعامل مع فاتورة المورد؟', 'title_en' => 'How do I handle a supplier invoice?', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['فاتورة مورد', 'supplier invoice', 'فاتورة'], 'icon' => 'fa-file-invoice'],
        ],
    ],
    'inventory' => [
        'flow_ar' => ['إضافة صنف', 'مستودع', 'حركة مخزون', 'تحويل', 'جرد', 'تسوية'],
        'flow_en' => ['Add item', 'Warehouse', 'Stock movement', 'Transfer', 'Audit', 'Adjustment'],
        'overview_ar' => 'المخزون يدير الأصناف والكميات عبر المستودعات مع الحركات والجرد والتسويات.',
        'overview_en' => 'Inventory manages items and quantities across warehouses with movements, audits, and adjustments.',
        'start_ar' => ['أضف صنفاً جديداً', 'أنشئ مستودعاً', 'سجّل حركة مخزون أو تحويل'],
        'start_en' => ['Add a new item', 'Create a warehouse', 'Record a movement or transfer'],
        'articles' => [
            ['slug' => 'inventory-cycle', 'title_ar' => 'دورة المخزون', 'title_en' => 'Inventory cycle', 'difficulty' => 'beginner', 'minutes' => 5, 'keywords' => ['مخزون', 'inventory', 'دورة'], 'icon' => 'fa-arrows-spin'],
            ['slug' => 'inventory-add-item', 'title_ar' => 'إضافة صنف', 'title_en' => 'Add an item', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['صنف', 'منتج', 'item', 'product'], 'icon' => 'fa-cube'],
            ['slug' => 'inventory-warehouse', 'title_ar' => 'إنشاء مستودع', 'title_en' => 'Create a warehouse', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['مستودع', 'warehouse'], 'icon' => 'fa-warehouse'],
            ['slug' => 'inventory-transfer', 'title_ar' => 'تحويل مخزون', 'title_en' => 'Stock transfer', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['تحويل مخزون', 'stock transfer', 'تحويل'], 'icon' => 'fa-right-left'],
            ['slug' => 'inventory-audit', 'title_ar' => 'الجرد', 'title_en' => 'Inventory audit', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['جرد', 'audit', 'count'], 'icon' => 'fa-clipboard-list'],
            ['slug' => 'inventory-adjustment', 'title_ar' => 'التسويات', 'title_en' => 'Stock adjustments', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['تسوية', 'adjustment', 'فروقات'], 'icon' => 'fa-scale-balanced'],
        ],
    ],
    'pos' => [
        'flow_ar' => ['فتح جلسة', 'بيع', 'دفع', 'إرجاع', 'إغلاق جلسة', 'تقرير'],
        'flow_en' => ['Open session', 'Sale', 'Payment', 'Return', 'Close session', 'Report'],
        'overview_ar' => 'نقطة البيع تدير عمليات الكاشير اليومية مع الجلسات والعوائد والولاء.',
        'overview_en' => 'POS manages daily cashier operations with sessions, returns, and loyalty.',
        'start_ar' => ['افتح جلسة نقطة البيع', 'نفّذ عملية بيع تجريبية', 'أغلق الجلسة وراجع التقرير'],
        'start_en' => ['Open a POS session', 'Run a test sale', 'Close the session and review the report'],
        'articles' => [
            ['slug' => 'pos-session', 'title_ar' => 'فتح وإغلاق جلسة نقطة البيع', 'title_en' => 'Open and close a POS session', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['جلسة', 'session', 'كاشير', 'POS'], 'icon' => 'fa-clock'],
            ['slug' => 'pos-sale', 'title_ar' => 'إتمام عملية بيع من نقطة البيع', 'title_en' => 'Complete a POS sale', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['بيع POS', 'checkout', 'نقطة البيع'], 'icon' => 'fa-cart-plus'],
            ['slug' => 'pos-return', 'title_ar' => 'مرتجع نقطة البيع', 'title_en' => 'POS return', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['مرتجع', 'return', 'استرجاع'], 'icon' => 'fa-rotate-left'],
        ],
    ],
    'logistics' => [
        'flow_ar' => ['إنشاء شحنة', 'تعيين سائق', 'تتبع', 'تسليم', 'تأكيد الاستلام'],
        'flow_en' => ['Create shipment', 'Assign driver', 'Track', 'Deliver', 'Confirm receipt'],
        'overview_ar' => 'الخدمات اللوجستية تربط الطلبات بالشحن والتسليم وتتبع الحالة.',
        'overview_en' => 'Logistics links orders to shipping, delivery, and status tracking.',
        'start_ar' => ['أنشئ شحنة جديدة', 'عيّن سائقاً', 'تابع حالة التسليم'],
        'start_en' => ['Create a shipment', 'Assign a driver', 'Track delivery status'],
        'articles' => [
            ['slug' => 'logistics-shipment', 'title_ar' => 'إنشاء شحنة', 'title_en' => 'Create a shipment', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['شحنة', 'shipment', 'توصيل'], 'icon' => 'fa-truck'],
            ['slug' => 'logistics-driver', 'title_ar' => 'تعيين السائق وتتبعه', 'title_en' => 'Assign and track a driver', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['سائق', 'driver', 'تتبع'], 'icon' => 'fa-id-card'],
            ['slug' => 'logistics-delivery', 'title_ar' => 'تأكيد التسليم', 'title_en' => 'Confirm delivery', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['تسليم', 'delivery'], 'icon' => 'fa-circle-check'],
        ],
    ],
    'suppliers' => [
        'flow_ar' => ['إضافة مورد', 'تصنيف', 'تقييم', 'تواصل', 'ربط بأمر شراء'],
        'flow_en' => ['Add supplier', 'Classify', 'Evaluate', 'Communicate', 'Link to PO'],
        'overview_ar' => 'الموردون هم أساس دورة المشتريات؛ هنا تضيفهم وتقيمهم وتتابع التواصل معهم.',
        'overview_en' => 'Suppliers underpin purchasing; add, evaluate, and communicate with them here.',
        'start_ar' => ['أضف مورداً جديداً', 'أكمل البيانات الأساسية', 'اربطه بطلب أو أمر شراء'],
        'start_en' => ['Add a new supplier', 'Complete basic details', 'Link them to a PR or PO'],
        'articles' => [
            ['slug' => 'suppliers-add', 'title_ar' => 'إضافة مورد جديد', 'title_en' => 'Add a new supplier', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['مورد', 'إضافة مورد', 'supplier', 'كيف أضيف مورد'], 'icon' => 'fa-user-plus'],
            ['slug' => 'suppliers-evaluate', 'title_ar' => 'تقييم المورد', 'title_en' => 'Evaluate a supplier', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['تقييم مورد', 'supplier evaluation', 'KPI'], 'icon' => 'fa-star'],
            ['slug' => 'suppliers-comms', 'title_ar' => 'التواصل مع الموردين', 'title_en' => 'Supplier communications', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['تواصل مورد', 'supplier comms'], 'icon' => 'fa-comments'],
        ],
    ],
    'hr' => [
        'flow_ar' => ['موظف', 'حضور', 'إجازة', 'طلب', 'راتب', 'اعتماد'],
        'flow_en' => ['Employee', 'Attendance', 'Leave', 'Request', 'Payroll', 'Approval'],
        'overview_ar' => 'الموارد البشرية تدير دورة حياة الموظف من التعيين حتى الرواتب والاعتمادات.',
        'overview_en' => 'HR manages the employee lifecycle from onboarding to payroll and approvals.',
        'start_ar' => ['أضف موظفاً', 'سجّل الحضور', 'أنشئ طلب إجازة وانتظر الاعتماد'],
        'start_en' => ['Add an employee', 'Record attendance', 'Create a leave request and await approval'],
        'articles' => [
            ['slug' => 'hr-cycle', 'title_ar' => 'دورة الموارد البشرية', 'title_en' => 'HR cycle', 'difficulty' => 'beginner', 'minutes' => 5, 'keywords' => ['موارد بشرية', 'HR', 'موظف'], 'icon' => 'fa-arrows-spin'],
            ['slug' => 'hr-add-employee', 'title_ar' => 'إضافة موظف', 'title_en' => 'Add an employee', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['موظف', 'employee', 'تعيين'], 'icon' => 'fa-user-plus'],
            ['slug' => 'hr-attendance', 'title_ar' => 'تسجيل الحضور', 'title_en' => 'Record attendance', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['حضور', 'attendance'], 'icon' => 'fa-fingerprint'],
            ['slug' => 'hr-leave', 'title_ar' => 'طلب إجازة', 'title_en' => 'Leave request', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['إجازة', 'leave', 'vacation'], 'icon' => 'fa-calendar-days'],
        ],
    ],
    'recruitment' => [
        'flow_ar' => ['وظيفة', 'نشر', 'مرشح', 'مقابلة', 'عرض', 'تعيين'],
        'flow_en' => ['Job', 'Publish', 'Candidate', 'Interview', 'Offer', 'Hire'],
        'overview_ar' => 'التوظيف يدير مسار التوظيف من إعلان الوظيفة حتى تعيين المرشح.',
        'overview_en' => 'Recruitment manages hiring from job posting to candidate onboarding.',
        'start_ar' => ['أنشئ وظيفة شاغرة', 'أضف المرشحين', 'حدّث مراحل التوظيف'],
        'start_en' => ['Create an open job', 'Add candidates', 'Update hiring stages'],
        'articles' => [
            ['slug' => 'recruitment-job', 'title_ar' => 'إنشاء وظيفة شاغرة', 'title_en' => 'Create a job opening', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['وظيفة', 'job', 'شاغر'], 'icon' => 'fa-briefcase'],
            ['slug' => 'recruitment-candidate', 'title_ar' => 'إدارة المرشحين', 'title_en' => 'Manage candidates', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['مرشح', 'candidate'], 'icon' => 'fa-user-group'],
            ['slug' => 'recruitment-hire', 'title_ar' => 'تعيين مرشح', 'title_en' => 'Hire a candidate', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['تعيين', 'hire', 'عرض عمل'], 'icon' => 'fa-handshake'],
        ],
    ],
    'crm' => [
        'flow_ar' => ['عميل', 'فرصة', 'عرض سعر', 'متابعة', 'إغلاق صفقة', 'تقرير'],
        'flow_en' => ['Customer', 'Opportunity', 'Quote', 'Follow-up', 'Close deal', 'Report'],
        'overview_ar' => 'CRM يساعدك على إدارة العملاء والفرص التجارية من أول تواصل حتى إغلاق الصفقة.',
        'overview_en' => 'CRM helps manage customers and opportunities from first contact to closed deal.',
        'start_ar' => ['أضف عميلاً', 'أنشئ فرصة بيع', 'أرسل عرض سعر وتابع الحالة'],
        'start_en' => ['Add a customer', 'Create an opportunity', 'Send a quote and track status'],
        'articles' => [
            ['slug' => 'crm-customer', 'title_ar' => 'إضافة عميل في CRM', 'title_en' => 'Add a CRM customer', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['عميل', 'customer', 'CRM'], 'icon' => 'fa-address-book'],
            ['slug' => 'crm-opportunity', 'title_ar' => 'إنشاء فرصة بيع', 'title_en' => 'Create a sales opportunity', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['فرصة', 'opportunity', 'صفقة'], 'icon' => 'fa-bullseye'],
            ['slug' => 'crm-quote', 'title_ar' => 'عروض الأسعار في CRM', 'title_en' => 'CRM quotations', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['عرض سعر', 'quotation', 'quote'], 'icon' => 'fa-file-signature'],
        ],
    ],
    'projects' => [
        'flow_ar' => ['مشروع', 'مهام', 'فريق', 'متابعة تقدم', 'تسليم'],
        'flow_en' => ['Project', 'Tasks', 'Team', 'Track progress', 'Deliver'],
        'overview_ar' => 'المشاريع تنظم العمل بالمهام والجداول ومتابعة الإنجاز.',
        'overview_en' => 'Projects organize work with tasks, schedules, and progress tracking.',
        'start_ar' => ['أنشئ مشروعاً', 'أضف المهام', 'تابع نسب الإنجاز'],
        'start_en' => ['Create a project', 'Add tasks', 'Track completion'],
        'articles' => [
            ['slug' => 'projects-create', 'title_ar' => 'إنشاء مشروع', 'title_en' => 'Create a project', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['مشروع', 'project'], 'icon' => 'fa-folder-plus'],
            ['slug' => 'projects-tasks', 'title_ar' => 'إدارة مهام المشروع', 'title_en' => 'Manage project tasks', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['مهمة', 'task'], 'icon' => 'fa-list-check'],
            ['slug' => 'projects-progress', 'title_ar' => 'متابعة تقدم المشروع', 'title_en' => 'Track project progress', 'difficulty' => 'intermediate', 'minutes' => 3, 'keywords' => ['تقدم', 'progress', 'milestone'], 'icon' => 'fa-chart-simple'],
        ],
    ],
    'approvals' => [
        'flow_ar' => ['طلب', 'مسار اعتماد', 'مراجع', 'موافقة/رفض', 'إشعار', 'أرشيف'],
        'flow_en' => ['Request', 'Workflow', 'Reviewer', 'Approve/Reject', 'Notify', 'Archive'],
        'overview_ar' => 'الموافقات تضبط الاعتمادات الإدارية عبر مسارات واضحة وشفافة.',
        'overview_en' => 'Approvals control administrative authorizations through clear workflows.',
        'start_ar' => ['افتح الطلبات المعلقة', 'راجع التفاصيل', 'وافق أو ارفض مع ملاحظة'],
        'start_en' => ['Open pending requests', 'Review details', 'Approve or reject with a note'],
        'articles' => [
            ['slug' => 'approvals-pending', 'title_ar' => 'معالجة الطلبات المعلقة', 'title_en' => 'Handle pending approvals', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['موافقة', 'approval', 'معلق'], 'icon' => 'fa-inbox'],
            ['slug' => 'approvals-workflow', 'title_ar' => 'فهم مسار الاعتماد', 'title_en' => 'Understand approval workflows', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['مسار', 'workflow', 'اعتماد'], 'icon' => 'fa-route', 'audience' => 'manager'],
            ['slug' => 'approvals-delegate', 'title_ar' => 'تفويض الموافقات', 'title_en' => 'Delegate approvals', 'difficulty' => 'advanced', 'minutes' => 4, 'keywords' => ['تفويض', 'delegate'], 'icon' => 'fa-user-check', 'audience' => 'manager'],
        ],
    ],
    'manufacturing' => [
        'flow_ar' => ['وصفة إنتاج', 'أمر تصنيع', 'صرف مواد', 'إنتاج', 'إدخال تام', 'تكلفة'],
        'flow_en' => ['BOM', 'Work order', 'Issue materials', 'Produce', 'Finished goods', 'Costing'],
        'overview_ar' => 'التصنيع يربط المواد الخام بأوامر الإنتاج والمنتجات التامة.',
        'overview_en' => 'Manufacturing links raw materials to work orders and finished goods.',
        'start_ar' => ['عرّف وصفة الإنتاج', 'أنشئ أمر تصنيع', 'صرف المواد وسجّل الإنتاج'],
        'start_en' => ['Define a BOM', 'Create a work order', 'Issue materials and record production'],
        'articles' => [
            ['slug' => 'mfg-bom', 'title_ar' => 'إنشاء وصفة إنتاج (BOM)', 'title_en' => 'Create a BOM', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['BOM', 'وصفة', 'تصنيع'], 'icon' => 'fa-sitemap'],
            ['slug' => 'mfg-work-order', 'title_ar' => 'أمر تصنيع', 'title_en' => 'Manufacturing work order', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['أمر تصنيع', 'work order'], 'icon' => 'fa-industry'],
            ['slug' => 'mfg-issue', 'title_ar' => 'صرف مواد للإنتاج', 'title_en' => 'Issue materials to production', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['صرف مواد', 'issue materials'], 'icon' => 'fa-boxes-packing'],
        ],
    ],
    'payroll' => [
        'flow_ar' => ['موظفين', 'بدلات/خصومات', 'مسير رواتب', 'مراجعة', 'اعتماد', 'صرف'],
        'flow_en' => ['Employees', 'Allowances/Deductions', 'Payroll run', 'Review', 'Approve', 'Pay'],
        'overview_ar' => 'منصة الرواتب تحتسب الرواتب والبدلات والخصومات وتعتمد الصرف.',
        'overview_en' => 'Payroll calculates salaries, allowances, and deductions, then approves payout.',
        'start_ar' => ['راجع بيانات الموظفين', 'أنشئ مسير رواتب', 'اعتمد الصرف بعد المراجعة'],
        'start_en' => ['Review employee data', 'Create a payroll run', 'Approve payout after review'],
        'articles' => [
            ['slug' => 'payroll-run', 'title_ar' => 'إنشاء مسير رواتب', 'title_en' => 'Create a payroll run', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['راتب', 'payroll', 'مسير'], 'icon' => 'fa-money-check-dollar', 'audience' => 'manager'],
            ['slug' => 'payroll-allowances', 'title_ar' => 'البدلات والخصومات', 'title_en' => 'Allowances and deductions', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['بدل', 'خصم', 'allowance', 'deduction'], 'icon' => 'fa-plus-minus', 'audience' => 'manager'],
            ['slug' => 'payroll-approve', 'title_ar' => 'اعتماد وصرف الرواتب', 'title_en' => 'Approve and pay salaries', 'difficulty' => 'advanced', 'minutes' => 4, 'keywords' => ['صرف راتب', 'payroll approve'], 'icon' => 'fa-stamp', 'audience' => 'admin'],
        ],
    ],
    'quality' => [
        'flow_ar' => ['معيار', 'فحص', 'عدم مطابقة', 'إجراء تصحيحي', 'تدقيق', 'إغلاق'],
        'flow_en' => ['Standard', 'Inspection', 'Nonconformance', 'Corrective action', 'Audit', 'Close'],
        'overview_ar' => 'الجودة تضمن الالتزام بالمعايير عبر الفحص والتدقيق والإجراءات التصحيحية.',
        'overview_en' => 'Quality ensures standards via inspections, audits, and corrective actions.',
        'start_ar' => ['سجّل فحصاً', 'افتح عدم مطابقة عند الحاجة', 'تابع الإجراء التصحيحي حتى الإغلاق'],
        'start_en' => ['Record an inspection', 'Open a nonconformance if needed', 'Track corrective action to closure'],
        'articles' => [
            ['slug' => 'qms-inspection', 'title_ar' => 'تسجيل فحص جودة', 'title_en' => 'Record a quality inspection', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['فحص', 'inspection', 'جودة'], 'icon' => 'fa-magnifying-glass'],
            ['slug' => 'qms-ncr', 'title_ar' => 'عدم المطابقة', 'title_en' => 'Nonconformance', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['عدم مطابقة', 'NCR', 'nonconformance'], 'icon' => 'fa-triangle-exclamation'],
            ['slug' => 'qms-audit', 'title_ar' => 'تدقيق الجودة', 'title_en' => 'Quality audit', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['تدقيق', 'audit'], 'icon' => 'fa-clipboard-check'],
        ],
    ],
    'bi' => [
        'flow_ar' => ['اختيار لوحة', 'تصفية الفترة', 'تحليل مؤشر', 'تصدير', 'مشاركة'],
        'flow_en' => ['Pick dashboard', 'Filter period', 'Analyze KPI', 'Export', 'Share'],
        'overview_ar' => 'ذكاء الأعمال يحوّل بيانات ERP إلى لوحات وتقارير لدعم القرار.',
        'overview_en' => 'BI turns ERP data into dashboards and reports for decision support.',
        'start_ar' => ['افتح ذكاء الأعمال', 'اختر لوحة مناسبة', 'صفِّ الفترة وراجع المؤشرات'],
        'start_en' => ['Open BI', 'Pick a dashboard', 'Filter the period and review KPIs'],
        'articles' => [
            ['slug' => 'bi-dashboards', 'title_ar' => 'استكشاف لوحات ذكاء الأعمال', 'title_en' => 'Explore BI dashboards', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['BI', 'لوحة', 'تحليل', 'dashboard'], 'icon' => 'fa-chart-pie', 'audience' => 'manager'],
            ['slug' => 'bi-filters', 'title_ar' => 'التصفية حسب الفترة والفرع', 'title_en' => 'Filter by period and branch', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['فلتر', 'filter', 'فترة'], 'icon' => 'fa-filter', 'audience' => 'manager'],
            ['slug' => 'bi-export', 'title_ar' => 'تصدير التقارير التحليلية', 'title_en' => 'Export analytical reports', 'difficulty' => 'intermediate', 'minutes' => 3, 'keywords' => ['تصدير', 'export', 'تقرير'], 'icon' => 'fa-file-export', 'audience' => 'manager'],
        ],
    ],
    'accounting' => [
        'flow_ar' => ['دليل حسابات', 'قيد يومية', 'فاتورة', 'سند', 'مراجعة', 'تقارير مالية'],
        'flow_en' => ['Chart of accounts', 'Journal entry', 'Invoice', 'Voucher', 'Review', 'Financial reports'],
        'overview_ar' => 'قسم الحسابات يدير القيود والفواتير والسندات والتقارير المالية.',
        'overview_en' => 'Accounting manages journals, invoices, vouchers, and financial reports.',
        'start_ar' => ['راجع دليل الحسابات', 'أنشئ قيداً أو فاتورة', 'راجع التقارير المالية'],
        'start_en' => ['Review the chart of accounts', 'Create a journal or invoice', 'Review financial reports'],
        'articles' => [
            ['slug' => 'accounting-coa', 'title_ar' => 'دليل الحسابات', 'title_en' => 'Chart of accounts', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['دليل حسابات', 'chart of accounts', 'حساب'], 'icon' => 'fa-sitemap'],
            ['slug' => 'accounting-journal', 'title_ar' => 'إنشاء قيد يومية', 'title_en' => 'Create a journal entry', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['قيد', 'journal', 'يومية'], 'icon' => 'fa-book'],
            ['slug' => 'accounting-invoice', 'title_ar' => 'فواتير الحسابات', 'title_en' => 'Accounting invoices', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['فاتورة', 'invoice', 'محاسبة'], 'icon' => 'fa-file-invoice-dollar'],
            ['slug' => 'accounting-reports', 'title_ar' => 'التقارير المالية', 'title_en' => 'Financial reports', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['تقرير مالي', 'ميزان', 'trial balance'], 'icon' => 'fa-chart-bar', 'audience' => 'manager'],
        ],
    ],
    'contracts-assets' => [
        'flow_ar' => ['عقد/أصل', 'تسجيل', 'متابعة', 'صيانة/تجديد', 'إهلاك', 'أرشفة'],
        'flow_en' => ['Contract/Asset', 'Register', 'Track', 'Maintain/Renew', 'Depreciate', 'Archive'],
        'overview_ar' => 'العقود والأصول تتبّع الالتزامات والممتلكات عبر دورة حياتها.',
        'overview_en' => 'Contracts and assets track commitments and property across their lifecycle.',
        'start_ar' => ['سجّل عقداً أو أصلاً', 'حدّد تواريخ التجديد/الصيانة', 'راجع الإهلاك عند الحاجة'],
        'start_en' => ['Register a contract or asset', 'Set renewal/maintenance dates', 'Review depreciation when needed'],
        'articles' => [
            ['slug' => 'contracts-create', 'title_ar' => 'إنشاء عقد', 'title_en' => 'Create a contract', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['عقد', 'contract'], 'icon' => 'fa-file-contract'],
            ['slug' => 'assets-register', 'title_ar' => 'تسجيل أصل', 'title_en' => 'Register an asset', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['أصل', 'asset'], 'icon' => 'fa-building'],
            ['slug' => 'assets-depreciation', 'title_ar' => 'إهلاك الأصول', 'title_en' => 'Asset depreciation', 'difficulty' => 'advanced', 'minutes' => 5, 'keywords' => ['إهلاك', 'depreciation'], 'icon' => 'fa-chart-line', 'audience' => 'manager'],
        ],
    ],
    'access-control' => [
        'flow_ar' => ['مستخدم', 'دور', 'صلاحيات', 'تعيين', 'مراجعة وصول', 'تدقيق'],
        'flow_en' => ['User', 'Role', 'Permissions', 'Assign', 'Access review', 'Audit'],
        'overview_ar' => 'التحكم بالوصول يحدد من يرى وماذا يفعل داخل النظام عبر الأدوار والصلاحيات.',
        'overview_en' => 'Access control defines who can see and do what via roles and permissions.',
        'start_ar' => ['أنشئ مستخدماً', 'عيّن دوراً مناسباً', 'راجع الصلاحيات قبل التفعيل'],
        'start_en' => ['Create a user', 'Assign an appropriate role', 'Review permissions before activation'],
        'articles' => [
            ['slug' => 'access-add-user', 'title_ar' => 'إضافة مستخدم', 'title_en' => 'Add a user', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['مستخدم', 'user', 'إضافة مستخدم'], 'icon' => 'fa-user-plus', 'audience' => 'admin'],
            ['slug' => 'access-roles', 'title_ar' => 'إدارة الأدوار والصلاحيات', 'title_en' => 'Manage roles and permissions', 'difficulty' => 'intermediate', 'minutes' => 5, 'keywords' => ['دور', 'صلاحية', 'role', 'permission'], 'icon' => 'fa-key', 'audience' => 'admin'],
            ['slug' => 'access-audit', 'title_ar' => 'مراجعة سجلات الوصول', 'title_en' => 'Review access audit logs', 'difficulty' => 'advanced', 'minutes' => 4, 'keywords' => ['تدقيق', 'audit log'], 'icon' => 'fa-shield', 'audience' => 'admin'],
        ],
    ],
    'notifications' => [
        'flow_ar' => ['حدث', 'إشعار', 'قناة', 'قراءة', 'إجراء', 'أرشفة'],
        'flow_en' => ['Event', 'Notification', 'Channel', 'Read', 'Act', 'Archive'],
        'overview_ar' => 'الإشعارات تبقيك على اطلاع بالأحداث المهمة داخل النظام.',
        'overview_en' => 'Notifications keep you informed about important system events.',
        'start_ar' => ['افتح مركز الإشعارات', 'راجع العناصر غير المقروءة', 'اتخذ الإجراء المطلوب'],
        'start_en' => ['Open the notification center', 'Review unread items', 'Take the required action'],
        'articles' => [
            ['slug' => 'notifications-center', 'title_ar' => 'استخدام مركز الإشعارات', 'title_en' => 'Using the notification center', 'difficulty' => 'beginner', 'minutes' => 2, 'keywords' => ['إشعار', 'notification', 'تنبيه'], 'icon' => 'fa-bell'],
            ['slug' => 'notifications-preferences', 'title_ar' => 'تفضيلات الإشعارات', 'title_en' => 'Notification preferences', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['تفضيلات', 'preferences', 'بريد'], 'icon' => 'fa-sliders'],
        ],
    ],
    'profile' => [
        'flow_ar' => ['فتح الملف', 'تحديث البيانات', 'اللغة', 'الأمان', 'حفظ'],
        'flow_en' => ['Open profile', 'Update details', 'Language', 'Security', 'Save'],
        'overview_ar' => 'إعدادات الملف تتيح تحديث بياناتك الشخصية واللغة وإعدادات الأمان.',
        'overview_en' => 'Profile settings let you update personal details, language, and security.',
        'start_ar' => ['افتح إعدادات الملف', 'حدّث الاسم أو الهاتف', 'احفظ التغييرات'],
        'start_en' => ['Open profile settings', 'Update name or phone', 'Save changes'],
        'articles' => [
            ['slug' => 'profile-update', 'title_ar' => 'تحديث بيانات الملف الشخصي', 'title_en' => 'Update your profile', 'difficulty' => 'beginner', 'minutes' => 2, 'keywords' => ['ملف', 'profile', 'حساب'], 'icon' => 'fa-user'],
            ['slug' => 'profile-language', 'title_ar' => 'تغيير لغة الواجهة', 'title_en' => 'Change interface language', 'difficulty' => 'beginner', 'minutes' => 2, 'keywords' => ['لغة', 'language', 'عربي', 'English'], 'icon' => 'fa-language'],
            ['slug' => 'profile-2fa', 'title_ar' => 'تفعيل التحقق بخطوتين', 'title_en' => 'Enable two-factor authentication', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['2FA', 'أمان', 'security'], 'icon' => 'fa-shield-halved'],
        ],
    ],
    'website' => [
        'flow_ar' => ['صفحة', 'محتوى', 'نشر', 'بوابة', 'مراجعة'],
        'flow_en' => ['Page', 'Content', 'Publish', 'Portal', 'Review'],
        'overview_ar' => 'وحدة الموقع تدير محتوى الموقع العام والبوابات المرتبطة بالشركة.',
        'overview_en' => 'Website manages public site content and company-linked portals.',
        'start_ar' => ['افتح إدارة الموقع', 'عدّل صفحة', 'انشر بعد المراجعة'],
        'start_en' => ['Open website admin', 'Edit a page', 'Publish after review'],
        'articles' => [
            ['slug' => 'website-pages', 'title_ar' => 'إدارة صفحات الموقع', 'title_en' => 'Manage website pages', 'difficulty' => 'beginner', 'minutes' => 4, 'keywords' => ['موقع', 'website', 'صفحة'], 'icon' => 'fa-globe', 'audience' => 'manager'],
            ['slug' => 'website-publish', 'title_ar' => 'نشر المحتوى', 'title_en' => 'Publish content', 'difficulty' => 'beginner', 'minutes' => 3, 'keywords' => ['نشر', 'publish'], 'icon' => 'fa-upload', 'audience' => 'manager'],
            ['slug' => 'website-portal', 'title_ar' => 'بوابات الشركة', 'title_en' => 'Company portals', 'difficulty' => 'intermediate', 'minutes' => 4, 'keywords' => ['بوابة', 'portal'], 'icon' => 'fa-door-open', 'audience' => 'manager'],
        ],
    ],
];
