<?php
declare(strict_types=1);

/**
 * In-app Help Center — module catalog (source of truth for UI cards + context mapping).
 *
 * @return list<array{
 *   slug:string,icon:string,accent:string,sort:int,
 *   title_ar:string,title_en:string,desc_ar:string,desc_en:string,
 *   audience:string,route_hints:list<string>,module_gate:?string
 * }>
 */
return [
    [
        'slug' => 'dashboard',
        'icon' => 'fa-gauge-high',
        'accent' => 'sky',
        'sort' => 10,
        'title_ar' => 'لوحة التحكم',
        'title_en' => 'Dashboard',
        'desc_ar' => 'نظرة عامة على مؤشرات الأداء والاختصارات السريعة.',
        'desc_en' => 'Overview of KPIs and quick actions.',
        'audience' => 'all',
        'route_hints' => ['admin', 'admin/executive-dashboard'],
        'module_gate' => null,
    ],
    [
        'slug' => 'sales-screen',
        'icon' => 'fa-cash-register',
        'accent' => 'green',
        'sort' => 20,
        'title_ar' => 'شاشة البيع',
        'title_en' => 'Sales Screen',
        'desc_ar' => 'إتمام عمليات البيع وإصدار الفواتير بسرعة.',
        'desc_en' => 'Complete sales and issue invoices quickly.',
        'audience' => 'all',
        'route_hints' => ['pos/register', 'pos/v2', 'admin/ops/pos/register'],
        'module_gate' => 'pos',
    ],
    [
        'slug' => 'branches',
        'icon' => 'fa-store',
        'accent' => 'teal',
        'sort' => 30,
        'title_ar' => 'الفروع',
        'title_en' => 'Branches',
        'desc_ar' => 'إدارة الفروع والصلاحيات والتحويلات بينها.',
        'desc_en' => 'Manage branches, access, and inter-branch transfers.',
        'audience' => 'all',
        'route_hints' => ['branches', 'branch-dashboard', 'branch-transfers', 'branch-financial'],
        'module_gate' => 'branches',
    ],
    [
        'slug' => 'purchases',
        'icon' => 'fa-cart-shopping',
        'accent' => 'amber',
        'sort' => 40,
        'title_ar' => 'المشتريات',
        'title_en' => 'Purchases',
        'desc_ar' => 'دورة المشتريات من الطلب حتى الدفع.',
        'desc_en' => 'Procurement cycle from request to payment.',
        'audience' => 'all',
        'route_hints' => ['purchase-requests', 'purchase-orders', 'rfq', 'quotations', 'tenders', 'eproc', 'procurement'],
        'module_gate' => 'procurement',
    ],
    [
        'slug' => 'inventory',
        'icon' => 'fa-boxes-stacked',
        'accent' => 'blue',
        'sort' => 50,
        'title_ar' => 'المخزون',
        'title_en' => 'Inventory',
        'desc_ar' => 'الأصناف والمستودعات والحركات والجرد.',
        'desc_en' => 'Items, warehouses, movements, and audits.',
        'audience' => 'all',
        'route_hints' => ['inventory', 'warehouses', 'warehouse-transfers', 'stock-movements', 'inventory-batches', 'inventory-audits', 'product-categories'],
        'module_gate' => 'inventory',
    ],
    [
        'slug' => 'pos',
        'icon' => 'fa-shop',
        'accent' => 'emerald',
        'sort' => 60,
        'title_ar' => 'نقطة البيع',
        'title_en' => 'Point of Sale',
        'desc_ar' => 'إدارة الجلسات والكاشير والعوائد والولاء.',
        'desc_en' => 'Sessions, cashiers, returns, and loyalty.',
        'audience' => 'all',
        'route_hints' => ['admin/ops/pos', 'admin/pos', '/pos'],
        'module_gate' => 'pos',
    ],
    [
        'slug' => 'logistics',
        'icon' => 'fa-truck-fast',
        'accent' => 'orange',
        'sort' => 70,
        'title_ar' => 'الخدمات اللوجستية',
        'title_en' => 'Logistics',
        'desc_ar' => 'الشحنات والتوصيل وتتبع السائقين.',
        'desc_en' => 'Shipments, delivery, and driver tracking.',
        'audience' => 'all',
        'route_hints' => ['logistics'],
        'module_gate' => 'logistics',
    ],
    [
        'slug' => 'suppliers',
        'icon' => 'fa-truck-field',
        'accent' => 'yellow',
        'sort' => 80,
        'title_ar' => 'الموردون',
        'title_en' => 'Suppliers',
        'desc_ar' => 'إضافة الموردين وتقييمهم ومتابعة التواصل.',
        'desc_en' => 'Onboard, evaluate, and communicate with suppliers.',
        'audience' => 'all',
        'route_hints' => ['suppliers', 'supplier-comms', 'supplier-evaluations', 'supplier-kpi', 'supplier-classifications'],
        'module_gate' => 'suppliers',
    ],
    [
        'slug' => 'hr',
        'icon' => 'fa-users',
        'accent' => 'pink',
        'sort' => 90,
        'title_ar' => 'الموارد البشرية',
        'title_en' => 'Human Resources',
        'desc_ar' => 'الموظفون والحضور والإجازات والطلبات.',
        'desc_en' => 'Employees, attendance, leave, and requests.',
        'audience' => 'all',
        'route_hints' => ['hr', 'hrm', 'admin/hr'],
        'module_gate' => 'hr',
    ],
    [
        'slug' => 'recruitment',
        'icon' => 'fa-user-plus',
        'accent' => 'rose',
        'sort' => 100,
        'title_ar' => 'التوظيف',
        'title_en' => 'Recruitment',
        'desc_ar' => 'الوظائف والمرشحون ومراحل التوظيف.',
        'desc_en' => 'Jobs, candidates, and hiring stages.',
        'audience' => 'all',
        'route_hints' => ['recruitment'],
        'module_gate' => 'recruitment',
    ],
    [
        'slug' => 'crm',
        'icon' => 'fa-handshake',
        'accent' => 'cyan',
        'sort' => 110,
        'title_ar' => 'إدارة علاقات العملاء',
        'title_en' => 'CRM',
        'desc_ar' => 'العملاء والفرص والعروض والمتابعة.',
        'desc_en' => 'Customers, opportunities, quotes, and follow-ups.',
        'audience' => 'all',
        'route_hints' => ['crm'],
        'module_gate' => 'crm',
    ],
    [
        'slug' => 'projects',
        'icon' => 'fa-diagram-project',
        'accent' => 'orange',
        'sort' => 120,
        'title_ar' => 'المشاريع',
        'title_en' => 'Projects',
        'desc_ar' => 'تخطيط المشاريع والمهام والتقدم.',
        'desc_en' => 'Plan projects, tasks, and progress.',
        'audience' => 'all',
        'route_hints' => ['projects'],
        'module_gate' => 'projects',
    ],
    [
        'slug' => 'approvals',
        'icon' => 'fa-clipboard-check',
        'accent' => 'violet',
        'sort' => 130,
        'title_ar' => 'الموافقات',
        'title_en' => 'Approvals',
        'desc_ar' => 'مسارات الاعتماد والطلبات المعلقة.',
        'desc_en' => 'Approval workflows and pending requests.',
        'audience' => 'all',
        'route_hints' => ['approvals', 'workflows', 'oversight/approvals'],
        'module_gate' => 'approvals',
    ],
    [
        'slug' => 'manufacturing',
        'icon' => 'fa-industry',
        'accent' => 'red',
        'sort' => 140,
        'title_ar' => 'التصنيع',
        'title_en' => 'Manufacturing',
        'desc_ar' => 'أوامر التصنيع ووصفات الإنتاج والمواد.',
        'desc_en' => 'Work orders, BOMs, and materials.',
        'audience' => 'all',
        'route_hints' => ['mfg', 'manufacturing'],
        'module_gate' => 'manufacturing',
    ],
    [
        'slug' => 'payroll',
        'icon' => 'fa-money-check-dollar',
        'accent' => 'fuchsia',
        'sort' => 150,
        'title_ar' => 'منصة الرواتب المؤسسية',
        'title_en' => 'Enterprise Payroll',
        'desc_ar' => 'احتساب الرواتب والبدلات والخصومات.',
        'desc_en' => 'Payroll runs, allowances, and deductions.',
        'audience' => 'manager',
        'route_hints' => ['payroll', 'hrm'],
        'module_gate' => 'payroll',
    ],
    [
        'slug' => 'quality',
        'icon' => 'fa-certificate',
        'accent' => 'teal',
        'sort' => 160,
        'title_ar' => 'منصة الجودة المؤسسية',
        'title_en' => 'Quality Management',
        'desc_ar' => 'عمليات الجودة والتدقيق وعدم المطابقة.',
        'desc_en' => 'Quality processes, audits, and nonconformances.',
        'audience' => 'all',
        'route_hints' => ['qms', 'quality'],
        'module_gate' => 'quality',
    ],
    [
        'slug' => 'bi',
        'icon' => 'fa-chart-line',
        'accent' => 'indigo',
        'sort' => 170,
        'title_ar' => 'ذكاء الأعمال',
        'title_en' => 'Business Intelligence',
        'desc_ar' => 'لوحات تحليلية وتقارير لاتخاذ القرار.',
        'desc_en' => 'Analytics dashboards and decision reports.',
        'audience' => 'manager',
        'route_hints' => ['bi', 'analytics'],
        'module_gate' => 'bi',
    ],
    [
        'slug' => 'accounting',
        'icon' => 'fa-calculator',
        'accent' => 'purple',
        'sort' => 180,
        'title_ar' => 'قسم الحسابات',
        'title_en' => 'Accounting',
        'desc_ar' => 'القيود والفواتير والحسابات والتقارير المالية.',
        'desc_en' => 'Journals, invoices, ledgers, and financial reports.',
        'audience' => 'all',
        'route_hints' => ['accounting', 'chart-of-accounts', 'journal-entries', 'cash-vouchers', 'invoices', 'fiscal-periods', 'bank-accounts', 'cost-centers'],
        'module_gate' => 'accounting',
    ],
    [
        'slug' => 'contracts-assets',
        'icon' => 'fa-file-contract',
        'accent' => 'slate',
        'sort' => 190,
        'title_ar' => 'العقود / الأصول',
        'title_en' => 'Contracts / Assets',
        'desc_ar' => 'إدارة العقود والأصول والصيانة والإهلاك.',
        'desc_en' => 'Contracts, assets, maintenance, and depreciation.',
        'audience' => 'all',
        'route_hints' => ['contracts', 'assets', 'contract-renewals', 'asset-maintenance', 'asset-assignments', 'asset-depreciation', 'eam'],
        'module_gate' => 'assets',
    ],
    [
        'slug' => 'access-control',
        'icon' => 'fa-shield-halved',
        'accent' => 'red',
        'sort' => 200,
        'title_ar' => 'التحكم بالوصول',
        'title_en' => 'Access Control',
        'desc_ar' => 'المستخدمون والأدوار والصلاحيات.',
        'desc_en' => 'Users, roles, and permissions.',
        'audience' => 'admin',
        'route_hints' => ['access-control', 'users', 'roles', 'permissions', 'admin/users', 'admin/roles'],
        'module_gate' => null,
    ],
    [
        'slug' => 'notifications',
        'icon' => 'fa-bell',
        'accent' => 'amber',
        'sort' => 210,
        'title_ar' => 'الإشعارات',
        'title_en' => 'Notifications',
        'desc_ar' => 'تنبيهات النظام والبريد والقوالب.',
        'desc_en' => 'System alerts, email, and templates.',
        'audience' => 'all',
        'route_hints' => ['notifications', 'email-templates', 'sms-templates'],
        'module_gate' => null,
    ],
    [
        'slug' => 'profile',
        'icon' => 'fa-user-gear',
        'accent' => 'sky',
        'sort' => 220,
        'title_ar' => 'إعدادات الملف',
        'title_en' => 'Profile Settings',
        'desc_ar' => 'بيانات الحساب واللغة والأمان.',
        'desc_en' => 'Account details, language, and security.',
        'audience' => 'all',
        'route_hints' => ['profile'],
        'module_gate' => null,
    ],
    [
        'slug' => 'website',
        'icon' => 'fa-globe',
        'accent' => 'cyan',
        'sort' => 230,
        'title_ar' => 'الموقع',
        'title_en' => 'Website',
        'desc_ar' => 'محتوى الموقع والصفحات والبوابات.',
        'desc_en' => 'Website content, pages, and portals.',
        'audience' => 'manager',
        'route_hints' => ['website', 'admin/cms'],
        'module_gate' => 'website',
    ],
];
