-- RATEB ERP — Phase 19A Enterprise Assets & Maintenance Platform (ONLINE)
-- Additive EAM layer. Does NOT alter legacy rateb_assets / AssetDevice* / Offline Foundation.
-- Optional link: legacy_asset_id → rateb_assets(id).
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS rateb_eam_asset_categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    name_ar VARCHAR(160) NULL,
    parent_id INT UNSIGNED NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_cat_uuid (public_uuid),
    UNIQUE KEY uq_eam_cat_code (company_id, code),
    INDEX idx_eam_cat_company (company_id, deleted_at),
    CONSTRAINT fk_eam_cat_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_manufacturers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    name_ar VARCHAR(160) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_mfr_uuid (public_uuid),
    UNIQUE KEY uq_eam_mfr_code (company_id, code),
    INDEX idx_eam_mfr_company (company_id, deleted_at),
    CONSTRAINT fk_eam_mfr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_vendors (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    name_ar VARCHAR(160) NULL,
    supplier_id INT UNSIGNED NULL,
    phone VARCHAR(40) NULL,
    email VARCHAR(190) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_vnd_uuid (public_uuid),
    UNIQUE KEY uq_eam_vnd_code (company_id, code),
    INDEX idx_eam_vnd_company (company_id, deleted_at),
    CONSTRAINT fk_eam_vnd_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_locations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    name_ar VARCHAR(160) NULL,
    parent_id INT UNSIGNED NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_loc_uuid (public_uuid),
    UNIQUE KEY uq_eam_loc_code (company_id, code),
    INDEX idx_eam_loc_company (company_id, deleted_at),
    CONSTRAINT fk_eam_loc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_asset_models (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    manufacturer_id INT UNSIGNED NULL,
    category_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    name_ar VARCHAR(160) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_mdl_uuid (public_uuid),
    UNIQUE KEY uq_eam_mdl_code (company_id, code),
    INDEX idx_eam_mdl_company (company_id, deleted_at),
    CONSTRAINT fk_eam_mdl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_mdl_mfr FOREIGN KEY (manufacturer_id) REFERENCES rateb_eam_manufacturers(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_mdl_cat FOREIGN KEY (category_id) REFERENCES rateb_eam_asset_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_assets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_no VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    category_id INT UNSIGNED NULL,
    model_id INT UNSIGNED NULL,
    manufacturer_id INT UNSIGNED NULL,
    vendor_id INT UNSIGNED NULL,
    location_id INT UNSIGNED NULL,
    legacy_asset_id INT UNSIGNED NULL,
    serial_no VARCHAR(120) NULL,
    barcode VARCHAR(120) NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
    purchase_date DATE NULL,
    purchase_cost DECIMAL(14,2) NULL,
    current_value DECIMAL(14,2) NULL,
    currency_code CHAR(3) NULL,
    useful_life_months INT UNSIGNED NULL,
    salvage_value DECIMAL(14,2) NULL,
    depreciation_method VARCHAR(40) NULL,
    placed_in_service_date DATE NULL,
    owner_user_id INT UNSIGNED NULL,
    custodian_user_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_ast_uuid (public_uuid),
    UNIQUE KEY uq_eam_ast_no (company_id, asset_no),
    INDEX idx_eam_ast_company (company_id, deleted_at),
    INDEX idx_eam_ast_workflow (company_id, workflow_status),
    INDEX idx_eam_ast_legacy (legacy_asset_id),
    CONSTRAINT fk_eam_ast_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_ast_cat FOREIGN KEY (category_id) REFERENCES rateb_eam_asset_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_ast_mdl FOREIGN KEY (model_id) REFERENCES rateb_eam_asset_models(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_ast_mfr FOREIGN KEY (manufacturer_id) REFERENCES rateb_eam_manufacturers(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_ast_vnd FOREIGN KEY (vendor_id) REFERENCES rateb_eam_vendors(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_ast_loc FOREIGN KEY (location_id) REFERENCES rateb_eam_locations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_asset_assignments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    assignee_user_id INT UNSIGNED NOT NULL,
    role_label VARCHAR(80) NULL,
    assigned_at DATETIME NOT NULL,
    released_at DATETIME NULL,
    status ENUM('active','released') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_asg_uuid (public_uuid),
    INDEX idx_eam_asg_asset (company_id, asset_id),
    CONSTRAINT fk_eam_asg_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_asg_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_asset_transfers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    from_location_id INT UNSIGNED NULL,
    to_location_id INT UNSIGNED NULL,
    from_branch_id INT UNSIGNED NULL,
    to_branch_id INT UNSIGNED NULL,
    transfer_at DATETIME NOT NULL,
    status ENUM('draft','completed','cancelled') NOT NULL DEFAULT 'draft',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_tr_uuid (public_uuid),
    INDEX idx_eam_tr_asset (company_id, asset_id),
    CONSTRAINT fk_eam_tr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_tr_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_maintenance_plans (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    plan_type ENUM('preventive','corrective','inspection','other') NOT NULL DEFAULT 'preventive',
    frequency_days INT UNSIGNED NULL,
    next_due_date DATE NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_mpl_uuid (public_uuid),
    UNIQUE KEY uq_eam_mpl_code (company_id, code),
    INDEX idx_eam_mpl_asset (company_id, asset_id),
    CONSTRAINT fk_eam_mpl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_mpl_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_maintenance_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    request_no VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    request_type ENUM('preventive','corrective','inspection','other') NOT NULL DEFAULT 'corrective',
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'new',
    priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
    requested_by INT UNSIGNED NULL,
    scheduled_at DATETIME NULL,
    completed_at DATETIME NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_mrq_uuid (public_uuid),
    UNIQUE KEY uq_eam_mrq_no (company_id, request_no),
    INDEX idx_eam_mrq_asset (company_id, asset_id),
    INDEX idx_eam_mrq_workflow (company_id, workflow_status),
    CONSTRAINT fk_eam_mrq_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_mrq_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_work_orders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    request_id INT UNSIGNED NULL,
    plan_id INT UNSIGNED NULL,
    work_order_no VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    work_type ENUM('preventive','corrective','inspection','other') NOT NULL DEFAULT 'corrective',
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'new',
    assignee_user_id INT UNSIGNED NULL,
    scheduled_start DATETIME NULL,
    scheduled_end DATETIME NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    labor_hours DECIMAL(10,2) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_wo_uuid (public_uuid),
    UNIQUE KEY uq_eam_wo_no (company_id, work_order_no),
    INDEX idx_eam_wo_asset (company_id, asset_id),
    INDEX idx_eam_wo_workflow (company_id, workflow_status),
    CONSTRAINT fk_eam_wo_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_wo_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_wo_req FOREIGN KEY (request_id) REFERENCES rateb_eam_maintenance_requests(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_wo_plan FOREIGN KEY (plan_id) REFERENCES rateb_eam_maintenance_plans(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_checklists (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    checklist_type ENUM('inspection','maintenance','other') NOT NULL DEFAULT 'inspection',
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_chk_uuid (public_uuid),
    UNIQUE KEY uq_eam_chk_code (company_id, code),
    CONSTRAINT fk_eam_chk_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_checklist_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    checklist_id INT UNSIGNED NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    item_text VARCHAR(255) NOT NULL,
    is_required TINYINT(1) NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_cki_uuid (public_uuid),
    INDEX idx_eam_cki_chk (checklist_id, sort_order),
    CONSTRAINT fk_eam_cki_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_cki_chk FOREIGN KEY (checklist_id) REFERENCES rateb_eam_checklists(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_inspections (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    checklist_id INT UNSIGNED NULL,
    work_order_id INT UNSIGNED NULL,
    inspection_no VARCHAR(40) NOT NULL,
    inspected_at DATETIME NOT NULL,
    result ENUM('pass','fail','conditional','na') NOT NULL DEFAULT 'pass',
    inspector_user_id INT UNSIGNED NULL,
    notes TEXT NULL,
    status ENUM('draft','completed','cancelled') NOT NULL DEFAULT 'draft',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_insp_uuid (public_uuid),
    UNIQUE KEY uq_eam_insp_no (company_id, inspection_no),
    INDEX idx_eam_insp_asset (company_id, asset_id),
    CONSTRAINT fk_eam_insp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_insp_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_insp_chk FOREIGN KEY (checklist_id) REFERENCES rateb_eam_checklists(id) ON DELETE SET NULL,
    CONSTRAINT fk_eam_insp_wo FOREIGN KEY (work_order_id) REFERENCES rateb_eam_work_orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_meter_readings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    meter_name VARCHAR(80) NOT NULL DEFAULT 'hours',
    reading_value DECIMAL(14,2) NOT NULL,
    reading_at DATETIME NOT NULL,
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_mtr_uuid (public_uuid),
    INDEX idx_eam_mtr_asset (company_id, asset_id, reading_at),
    CONSTRAINT fk_eam_mtr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_mtr_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_warranties (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    provider_name VARCHAR(160) NULL,
    policy_no VARCHAR(80) NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    coverage_notes TEXT NULL,
    status ENUM('active','expired','void') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_war_uuid (public_uuid),
    INDEX idx_eam_war_asset (company_id, asset_id),
    CONSTRAINT fk_eam_war_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_war_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_insurance (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    insurer_name VARCHAR(160) NULL,
    policy_no VARCHAR(80) NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    coverage_amount DECIMAL(14,2) NULL,
    currency_code CHAR(3) NULL,
    status ENUM('active','expired','cancelled') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_ins_uuid (public_uuid),
    INDEX idx_eam_ins_asset (company_id, asset_id),
    CONSTRAINT fk_eam_ins_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_ins_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_spare_part_refs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NULL,
    part_sku VARCHAR(80) NULL,
    part_name VARCHAR(190) NOT NULL,
    inventory_item_id INT UNSIGNED NULL,
    qty_on_hand DECIMAL(14,2) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_spr_uuid (public_uuid),
    INDEX idx_eam_spr_asset (company_id, asset_id),
    CONSTRAINT fk_eam_spr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_spr_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_parts_consumption (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    work_order_id INT UNSIGNED NOT NULL,
    spare_part_id INT UNSIGNED NULL,
    part_name VARCHAR(190) NOT NULL,
    quantity DECIMAL(14,2) NOT NULL DEFAULT 1.00,
    unit_cost DECIMAL(14,2) NULL,
    consumed_at DATETIME NOT NULL,
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_pc_uuid (public_uuid),
    INDEX idx_eam_pc_wo (company_id, work_order_id),
    CONSTRAINT fk_eam_pc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_pc_wo FOREIGN KEY (work_order_id) REFERENCES rateb_eam_work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_pc_spr FOREIGN KEY (spare_part_id) REFERENCES rateb_eam_spare_part_refs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_document_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    related_type VARCHAR(40) NOT NULL,
    related_id INT UNSIGNED NOT NULL,
    document_id INT UNSIGNED NULL,
    title VARCHAR(190) NOT NULL,
    doc_type VARCHAR(40) NULL,
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_doc_uuid (public_uuid),
    INDEX idx_eam_doc_related (company_id, related_type, related_id),
    CONSTRAINT fk_eam_doc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    related_type VARCHAR(40) NULL,
    related_id INT UNSIGNED NULL,
    meta_json JSON NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_eam_tl_uuid (public_uuid),
    INDEX idx_eam_tl_asset (company_id, asset_id, created_at),
    CONSTRAINT fk_eam_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_activities (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    asset_id INT UNSIGNED NOT NULL,
    activity_type VARCHAR(40) NOT NULL DEFAULT 'note',
    subject VARCHAR(190) NOT NULL,
    body TEXT NULL,
    activity_at DATETIME NULL,
    owner_user_id INT UNSIGNED NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_act_uuid (public_uuid),
    INDEX idx_eam_act_asset (company_id, asset_id),
    CONSTRAINT fk_eam_act_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_act_asset FOREIGN KEY (asset_id) REFERENCES rateb_eam_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    related_type VARCHAR(40) NOT NULL,
    related_id INT UNSIGNED NOT NULL,
    body TEXT NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_cmt_uuid (public_uuid),
    INDEX idx_eam_cmt_related (company_id, related_type, related_id),
    CONSTRAINT fk_eam_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eam_tag_uuid (public_uuid),
    UNIQUE KEY uq_eam_tag_code (company_id, code),
    CONSTRAINT fk_eam_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_entity_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    tag_id INT UNSIGNED NOT NULL,
    related_type VARCHAR(40) NOT NULL,
    related_id INT UNSIGNED NOT NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_eam_etag (company_id, tag_id, related_type, related_id),
    CONSTRAINT fk_eam_etag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eam_etag_tag FOREIGN KEY (tag_id) REFERENCES rateb_eam_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eam_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    entity_type ENUM('asset','maintenance_request','work_order') NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    asset_id INT UNSIGNED NULL,
    from_status VARCHAR(40) NOT NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_eam_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eam_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View Assets Platform', 'عرض منصة الأصول', 'assets.view', 'assets', 'View enterprise assets platform', 'عرض منصة الأصول المؤسسية'),
('Create Assets Platform', 'إنشاء منصة الأصول', 'assets.create', 'assets', 'Create enterprise asset records', 'إنشاء سجلات منصة الأصول'),
('Update Assets Platform', 'تحديث منصة الأصول', 'assets.update', 'assets', 'Update enterprise asset records', 'تحديث سجلات منصة الأصول'),
('Delete Assets Platform', 'حذف منصة الأصول', 'assets.delete', 'assets', 'Soft-delete enterprise asset records', 'حذف ناعم لسجلات منصة الأصول'),
('Assign Assets Platform', 'تعيين منصة الأصول', 'assets.assign', 'assets', 'Assign asset custodians', 'تعيين حراس الأصول'),
('Transfer Assets Platform', 'نقل منصة الأصول', 'assets.transfer', 'assets', 'Transfer assets between locations', 'نقل الأصول بين المواقع'),
('Assets Maintenance', 'صيانة الأصول', 'assets.maintenance', 'assets', 'Manage maintenance requests and work orders', 'إدارة طلبات الصيانة وأوامر العمل'),
('Assets Inspection', 'فحص الأصول', 'assets.inspection', 'assets', 'Manage inspections and checklists', 'إدارة الفحوصات وقوائم التحقق'),
('Assets Admin', 'إدارة كاملة لمنصة الأصول', 'assets.admin', 'assets', 'Full enterprise assets administration', 'إدارة كاملة لمنصة الأصول'),
('Manage Assets Platform', 'إدارة منصة الأصول', 'assets.manage', 'assets', 'All enterprise assets operations', 'جميع عمليات منصة الأصول')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'assets.view', 'assets.create', 'assets.update', 'assets.delete', 'assets.assign',
    'assets.transfer', 'assets.maintenance', 'assets.inspection', 'assets.admin', 'assets.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
