-- RATEB ERP — Phase 21A Enterprise Procurement & Supplier Collaboration Platform (ONLINE)
-- Additive EPROC layer. Does NOT alter legacy rateb_purchase_* / rateb_rfq / rateb_suppliers /
-- ProcurementService / Offline Foundation / Inventory / Accounting / Approval tables.
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    parent_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_cat_uuid (public_uuid),
    UNIQUE KEY uq_eproc_cat_code (company_id, code),
    INDEX idx_eproc_cat_company (company_id, deleted_at),
    CONSTRAINT fk_eproc_cat_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_profiles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    legacy_supplier_id INT UNSIGNED NULL,
    category_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    legal_name VARCHAR(190) NULL,
    tax_number VARCHAR(60) NULL,
    country_code CHAR(2) NULL,
    city VARCHAR(120) NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(60) NULL,
    website VARCHAR(190) NULL,
    risk_level ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    qualification_status VARCHAR(40) NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_sup_uuid (public_uuid),
    UNIQUE KEY uq_eproc_sup_code (company_id, code),
    INDEX idx_eproc_sup_company (company_id, deleted_at),
    INDEX idx_eproc_sup_workflow (company_id, workflow_status),
    INDEX idx_eproc_sup_legacy (company_id, legacy_supplier_id),
    CONSTRAINT fk_eproc_sup_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_sup_category FOREIGN KEY (category_id) REFERENCES rateb_eproc_supplier_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_contacts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    title VARCHAR(120) NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(60) NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_contact_uuid (public_uuid),
    INDEX idx_eproc_contact_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_contact_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_contact_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_certifications (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    cert_type VARCHAR(80) NOT NULL,
    cert_number VARCHAR(80) NULL,
    issued_at DATE NULL,
    expires_at DATE NULL,
    issuer VARCHAR(160) NULL,
    status ENUM('valid','expired','revoked','pending') NOT NULL DEFAULT 'pending',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_cert_uuid (public_uuid),
    INDEX idx_eproc_cert_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_cert_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_cert_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_sla (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    metric_key VARCHAR(60) NOT NULL DEFAULT 'on_time_delivery',
    target_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    unit VARCHAR(20) NULL,
    period_days INT UNSIGNED NOT NULL DEFAULT 30,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_sla_uuid (public_uuid),
    UNIQUE KEY uq_eproc_sla_code (company_id, code),
    INDEX idx_eproc_sla_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_sla_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_sla_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_scorecards (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    period_label VARCHAR(40) NOT NULL,
    quality_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    delivery_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    price_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    service_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    overall_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_sc_uuid (public_uuid),
    INDEX idx_eproc_sc_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_sc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_sc_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_performance (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    metric_key VARCHAR(60) NOT NULL,
    metric_value DECIMAL(14,4) NOT NULL DEFAULT 0,
    period_start DATE NULL,
    period_end DATE NULL,
    notes TEXT NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_perf_uuid (public_uuid),
    INDEX idx_eproc_perf_profile (company_id, profile_id, metric_key),
    CONSTRAINT fk_eproc_perf_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_perf_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_risk (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    risk_code VARCHAR(40) NOT NULL,
    risk_level ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    mitigation TEXT NULL,
    status ENUM('open','mitigated','accepted','closed') NOT NULL DEFAULT 'open',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_risk_uuid (public_uuid),
    INDEX idx_eproc_risk_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_risk_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_risk_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_blacklist (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    reason VARCHAR(255) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    status ENUM('active','lifted','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_bl_uuid (public_uuid),
    INDEX idx_eproc_bl_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_bl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_bl_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_supplier_qualification (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    checklist_json JSON NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    decided_at DATETIME NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_qual_uuid (public_uuid),
    UNIQUE KEY uq_eproc_qual_code (company_id, code),
    INDEX idx_eproc_qual_profile (company_id, profile_id),
    INDEX idx_eproc_qual_workflow (company_id, workflow_status),
    CONSTRAINT fk_eproc_qual_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_qual_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_document_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    document_id INT UNSIGNED NULL,
    file_name VARCHAR(190) NULL,
    mime_type VARCHAR(80) NULL,
    title VARCHAR(190) NULL,
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_doc_uuid (public_uuid),
    INDEX idx_eproc_doc_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_doc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_portal_invites (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NOT NULL,
    email VARCHAR(190) NOT NULL,
    invite_token CHAR(64) NOT NULL,
    expires_at DATETIME NULL,
    accepted_at DATETIME NULL,
    status ENUM('pending','accepted','revoked','expired') NOT NULL DEFAULT 'pending',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_portal_uuid (public_uuid),
    UNIQUE KEY uq_eproc_portal_token (invite_token),
    INDEX idx_eproc_portal_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_portal_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_portal_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_collaboration (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NULL,
    related_type VARCHAR(40) NULL,
    related_id INT UNSIGNED NULL,
    subject VARCHAR(190) NOT NULL,
    body TEXT NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'open',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_collab_uuid (public_uuid),
    INDEX idx_eproc_collab_company (company_id, workflow_status),
    INDEX idx_eproc_collab_profile (company_id, profile_id),
    CONSTRAINT fk_eproc_collab_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_collab_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_rfq_templates (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    body_template TEXT NULL,
    default_days INT UNSIGNED NOT NULL DEFAULT 14,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_rfqt_uuid (public_uuid),
    UNIQUE KEY uq_eproc_rfqt_code (company_id, code),
    INDEX idx_eproc_rfqt_company (company_id, deleted_at),
    CONSTRAINT fk_eproc_rfqt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_tenders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    legacy_tender_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    opens_at DATETIME NULL,
    closes_at DATETIME NULL,
    budget_amount DECIMAL(14,2) NULL,
    currency_code CHAR(3) NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_tender_uuid (public_uuid),
    UNIQUE KEY uq_eproc_tender_code (company_id, code),
    INDEX idx_eproc_tender_workflow (company_id, workflow_status),
    CONSTRAINT fk_eproc_tender_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_tender_bids (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    tender_id INT UNSIGNED NOT NULL,
    profile_id INT UNSIGNED NULL,
    bid_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NULL,
    score DECIMAL(5,2) NULL,
    notes TEXT NULL,
    status ENUM('submitted','shortlisted','accepted','rejected','withdrawn') NOT NULL DEFAULT 'submitted',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_bid_uuid (public_uuid),
    INDEX idx_eproc_bid_tender (company_id, tender_id),
    CONSTRAINT fk_eproc_bid_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_bid_tender FOREIGN KEY (tender_id) REFERENCES rateb_eproc_tenders(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_bid_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_bid_comparisons (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    tender_id INT UNSIGNED NOT NULL,
    title VARCHAR(190) NOT NULL,
    comparison_json JSON NULL,
    recommended_bid_id INT UNSIGNED NULL,
    status ENUM('draft','finalized','archived') NOT NULL DEFAULT 'draft',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_cmp_uuid (public_uuid),
    INDEX idx_eproc_cmp_tender (company_id, tender_id),
    CONSTRAINT fk_eproc_cmp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_cmp_tender FOREIGN KEY (tender_id) REFERENCES rateb_eproc_tenders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_contracts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    legacy_contract_id INT UNSIGNED NULL,
    profile_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    starts_at DATE NULL,
    ends_at DATE NULL,
    value_amount DECIMAL(14,2) NULL,
    currency_code CHAR(3) NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_ctr_uuid (public_uuid),
    UNIQUE KEY uq_eproc_ctr_code (company_id, code),
    INDEX idx_eproc_ctr_workflow (company_id, workflow_status),
    CONSTRAINT fk_eproc_ctr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_ctr_profile FOREIGN KEY (profile_id) REFERENCES rateb_eproc_supplier_profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_calendar_events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    event_type VARCHAR(40) NOT NULL DEFAULT 'general',
    title VARCHAR(190) NOT NULL,
    starts_at DATETIME NOT NULL,
    ends_at DATETIME NULL,
    related_type VARCHAR(40) NULL,
    related_id INT UNSIGNED NULL,
    status ENUM('scheduled','done','cancelled') NOT NULL DEFAULT 'scheduled',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_cal_uuid (public_uuid),
    INDEX idx_eproc_cal_company (company_id, starts_at),
    CONSTRAINT fk_eproc_cal_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_spend_snapshots (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    period_label VARCHAR(40) NOT NULL,
    category_key VARCHAR(60) NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NULL,
    meta_json JSON NULL,
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_spend_uuid (public_uuid),
    INDEX idx_eproc_spend_company (company_id, period_label),
    CONSTRAINT fk_eproc_spend_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_approval_links (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    eap_request_id INT UNSIGNED NULL,
    legacy_instance_id INT UNSIGNED NULL,
    link_status ENUM('pending','linked','closed') NOT NULL DEFAULT 'pending',
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_alink_uuid (public_uuid),
    INDEX idx_eproc_alink_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_alink_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    message VARCHAR(255) NOT NULL,
    meta_json JSON NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_eproc_tl_company (company_id, created_at),
    INDEX idx_eproc_tl_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_audit (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    action VARCHAR(60) NOT NULL,
    message VARCHAR(255) NOT NULL,
    meta_json JSON NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_eproc_audit_company (company_id, created_at),
    CONSTRAINT fk_eproc_audit_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_assignments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    assignee_user_id INT UNSIGNED NOT NULL,
    role_label VARCHAR(80) NULL,
    status ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_asg_uuid (public_uuid),
    INDEX idx_eproc_asg_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_asg_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    body TEXT NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_cmt_uuid (public_uuid),
    INDEX idx_eproc_cmt_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_tag_uuid (public_uuid),
    UNIQUE KEY uq_eproc_tag_code (company_id, code),
    CONSTRAINT fk_eproc_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_entity_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    tag_id INT UNSIGNED NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_eproc_etag_uuid (public_uuid),
    UNIQUE KEY uq_eproc_etag_link (company_id, tag_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_etag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_eproc_etag_tag FOREIGN KEY (tag_id) REFERENCES rateb_eproc_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_eproc_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_eproc_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_eproc_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View Procurement Platform', 'عرض منصة المشتريات', 'procurement.view', 'procurement', 'View enterprise procurement platform', 'عرض منصة المشتريات المؤسسية'),
('Create Procurement Platform', 'إنشاء سجلات المشتريات', 'procurement.create', 'procurement', 'Create enterprise procurement records', 'إنشاء سجلات منصة المشتريات'),
('Update Procurement Platform', 'تحديث سجلات المشتريات', 'procurement.update', 'procurement', 'Update enterprise procurement records', 'تحديث سجلات منصة المشتريات'),
('Submit Procurement Platform', 'تقديم طلبات المشتريات', 'procurement.submit', 'procurement', 'Submit procurement workflow transitions', 'تقديم انتقالات سير عمل المشتريات'),
('Procurement Suppliers', 'موردو المنصة', 'procurement.supplier', 'procurement', 'Manage enterprise supplier collaboration', 'إدارة تعاون الموردين المؤسسي'),
('Procurement Tenders', 'مناقصات المنصة', 'procurement.tender', 'procurement', 'Manage enterprise tenders and bids', 'إدارة المناقصات والعروض'),
('Procurement Contracts', 'عقود المنصة', 'procurement.contract', 'procurement', 'Manage enterprise contract lifecycle', 'إدارة دورة حياة العقود'),
('Procurement Portal', 'بوابة الموردين', 'procurement.portal', 'procurement', 'Manage supplier portal invites', 'إدارة دعوات بوابة الموردين'),
('Procurement Admin', 'إدارة منصة المشتريات', 'procurement.admin', 'procurement', 'Full enterprise procurement administration', 'إدارة كاملة لمنصة المشتريات')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'procurement.view', 'procurement.create', 'procurement.update', 'procurement.submit',
    'procurement.supplier', 'procurement.tender', 'procurement.contract', 'procurement.portal',
    'procurement.admin', 'procurement.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
