-- RATEB ERP — Phase 22A Enterprise Manufacturing (MRP) Platform (ONLINE)
-- Additive MFG layer (rateb_mfg_*). Does NOT alter Inventory / Procurement / Projects /
-- Assets / Accounting / Offline Foundation / Queue / Replay / SDK / IndexedDB.
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS rateb_mfg_products (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    inventory_item_id INT UNSIGNED NULL,
    uom VARCHAR(40) NULL DEFAULT 'EA',
    product_type ENUM('finished','semi_finished','raw','phantom') NOT NULL DEFAULT 'finished',
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_prod_uuid (public_uuid),
    UNIQUE KEY uq_mfg_prod_code (company_id, code),
    INDEX idx_mfg_prod_company (company_id, deleted_at),
    INDEX idx_mfg_prod_workflow (company_id, workflow_status),
    INDEX idx_mfg_prod_item (company_id, inventory_item_id),
    CONSTRAINT fk_mfg_prod_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_product_variants (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    product_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    sku VARCHAR(80) NULL,
    inventory_item_id INT UNSIGNED NULL,
    attributes_json TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_var_uuid (public_uuid),
    UNIQUE KEY uq_mfg_var_code (company_id, product_id, code),
    INDEX idx_mfg_var_product (company_id, product_id),
    CONSTRAINT fk_mfg_var_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_var_product FOREIGN KEY (product_id) REFERENCES rateb_mfg_products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_boms (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    product_id INT UNSIGNED NOT NULL,
    variant_id INT UNSIGNED NULL,
    description TEXT NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_bom_uuid (public_uuid),
    UNIQUE KEY uq_mfg_bom_code (company_id, code),
    INDEX idx_mfg_bom_product (company_id, product_id),
    INDEX idx_mfg_bom_workflow (company_id, workflow_status),
    CONSTRAINT fk_mfg_bom_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_bom_product FOREIGN KEY (product_id) REFERENCES rateb_mfg_products(id) ON DELETE RESTRICT,
    CONSTRAINT fk_mfg_bom_variant FOREIGN KEY (variant_id) REFERENCES rateb_mfg_product_variants(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_bom_versions (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    bom_id INT UNSIGNED NOT NULL,
    version_label VARCHAR(40) NOT NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 0,
    effective_from DATE NULL,
    effective_to DATE NULL,
    scrap_percent DECIMAL(8,4) NOT NULL DEFAULT 0,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_bomv_uuid (public_uuid),
    UNIQUE KEY uq_mfg_bomv_label (company_id, bom_id, version_label),
    INDEX idx_mfg_bomv_bom (company_id, bom_id),
    CONSTRAINT fk_mfg_bomv_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_bomv_bom FOREIGN KEY (bom_id) REFERENCES rateb_mfg_boms(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_bom_lines (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    bom_version_id INT UNSIGNED NOT NULL,
    line_no INT UNSIGNED NOT NULL DEFAULT 1,
    component_product_id INT UNSIGNED NULL,
    component_variant_id INT UNSIGNED NULL,
    inventory_item_id INT UNSIGNED NULL,
    component_code VARCHAR(40) NULL,
    component_name VARCHAR(190) NOT NULL,
    qty_per DECIMAL(18,6) NOT NULL DEFAULT 1,
    uom VARCHAR(40) NULL DEFAULT 'EA',
    scrap_percent DECIMAL(8,4) NOT NULL DEFAULT 0,
    is_optional TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_boml_uuid (public_uuid),
    INDEX idx_mfg_boml_ver (company_id, bom_version_id),
    CONSTRAINT fk_mfg_boml_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_boml_ver FOREIGN KEY (bom_version_id) REFERENCES rateb_mfg_bom_versions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_work_centers (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    capacity_hours_day DECIMAL(10,2) NOT NULL DEFAULT 8,
    cost_per_hour DECIMAL(14,4) NOT NULL DEFAULT 0,
    warehouse_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_wc_uuid (public_uuid),
    UNIQUE KEY uq_mfg_wc_code (company_id, code),
    INDEX idx_mfg_wc_company (company_id, deleted_at),
    CONSTRAINT fk_mfg_wc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_machines (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    work_center_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    eam_asset_id INT UNSIGNED NULL,
    capacity_hours_day DECIMAL(10,2) NOT NULL DEFAULT 8,
    status ENUM('active','inactive','archived','maintenance') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_mach_uuid (public_uuid),
    UNIQUE KEY uq_mfg_mach_code (company_id, code),
    INDEX idx_mfg_mach_wc (company_id, work_center_id),
    INDEX idx_mfg_mach_asset (company_id, eam_asset_id),
    CONSTRAINT fk_mfg_mach_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_mach_wc FOREIGN KEY (work_center_id) REFERENCES rateb_mfg_work_centers(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_routings (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    product_id INT UNSIGNED NULL,
    bom_id INT UNSIGNED NULL,
    description TEXT NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_rt_uuid (public_uuid),
    UNIQUE KEY uq_mfg_rt_code (company_id, code),
    INDEX idx_mfg_rt_product (company_id, product_id),
    CONSTRAINT fk_mfg_rt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_rt_product FOREIGN KEY (product_id) REFERENCES rateb_mfg_products(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_rt_bom FOREIGN KEY (bom_id) REFERENCES rateb_mfg_boms(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_routing_operations (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    routing_id INT UNSIGNED NOT NULL,
    seq_no INT UNSIGNED NOT NULL DEFAULT 10,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    work_center_id INT UNSIGNED NULL,
    machine_id INT UNSIGNED NULL,
    setup_minutes DECIMAL(10,2) NOT NULL DEFAULT 0,
    run_minutes_per_unit DECIMAL(12,4) NOT NULL DEFAULT 0,
    queue_minutes DECIMAL(10,2) NOT NULL DEFAULT 0,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_op_uuid (public_uuid),
    UNIQUE KEY uq_mfg_op_code (company_id, routing_id, code),
    INDEX idx_mfg_op_routing (company_id, routing_id),
    CONSTRAINT fk_mfg_op_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_op_routing FOREIGN KEY (routing_id) REFERENCES rateb_mfg_routings(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_op_wc FOREIGN KEY (work_center_id) REFERENCES rateb_mfg_work_centers(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_op_machine FOREIGN KEY (machine_id) REFERENCES rateb_mfg_machines(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_production_orders (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    variant_id INT UNSIGNED NULL,
    bom_id INT UNSIGNED NULL,
    bom_version_id INT UNSIGNED NULL,
    routing_id INT UNSIGNED NULL,
    qty_planned DECIMAL(18,6) NOT NULL DEFAULT 1,
    qty_completed DECIMAL(18,6) NOT NULL DEFAULT 0,
    qty_scrap DECIMAL(18,6) NOT NULL DEFAULT 0,
    uom VARCHAR(40) NULL DEFAULT 'EA',
    warehouse_id INT UNSIGNED NULL,
    project_id INT UNSIGNED NULL,
    planned_start DATE NULL,
    planned_end DATE NULL,
    actual_start DATETIME NULL,
    actual_end DATETIME NULL,
    priority INT NOT NULL DEFAULT 50,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_po_uuid (public_uuid),
    UNIQUE KEY uq_mfg_po_code (company_id, code),
    INDEX idx_mfg_po_company (company_id, deleted_at),
    INDEX idx_mfg_po_workflow (company_id, workflow_status),
    INDEX idx_mfg_po_product (company_id, product_id),
    INDEX idx_mfg_po_project (company_id, project_id),
    CONSTRAINT fk_mfg_po_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_po_product FOREIGN KEY (product_id) REFERENCES rateb_mfg_products(id) ON DELETE RESTRICT,
    CONSTRAINT fk_mfg_po_variant FOREIGN KEY (variant_id) REFERENCES rateb_mfg_product_variants(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_po_bom FOREIGN KEY (bom_id) REFERENCES rateb_mfg_boms(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_po_bomv FOREIGN KEY (bom_version_id) REFERENCES rateb_mfg_bom_versions(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_po_routing FOREIGN KEY (routing_id) REFERENCES rateb_mfg_routings(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_work_orders (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    routing_operation_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    work_center_id INT UNSIGNED NULL,
    machine_id INT UNSIGNED NULL,
    seq_no INT UNSIGNED NOT NULL DEFAULT 10,
    qty_planned DECIMAL(18,6) NOT NULL DEFAULT 1,
    qty_completed DECIMAL(18,6) NOT NULL DEFAULT 0,
    planned_start DATETIME NULL,
    planned_end DATETIME NULL,
    actual_start DATETIME NULL,
    actual_end DATETIME NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_wo_uuid (public_uuid),
    UNIQUE KEY uq_mfg_wo_code (company_id, code),
    INDEX idx_mfg_wo_po (company_id, production_order_id),
    INDEX idx_mfg_wo_workflow (company_id, workflow_status),
    CONSTRAINT fk_mfg_wo_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_wo_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_wo_op FOREIGN KEY (routing_operation_id) REFERENCES rateb_mfg_routing_operations(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_wo_wc FOREIGN KEY (work_center_id) REFERENCES rateb_mfg_work_centers(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_wo_machine FOREIGN KEY (machine_id) REFERENCES rateb_mfg_machines(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_capacity_plans (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    work_center_id INT UNSIGNED NOT NULL,
    plan_date DATE NOT NULL,
    available_hours DECIMAL(10,2) NOT NULL DEFAULT 8,
    booked_hours DECIMAL(10,2) NOT NULL DEFAULT 0,
    status ENUM('open','locked','archived') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_cap_uuid (public_uuid),
    UNIQUE KEY uq_mfg_cap_day (company_id, work_center_id, plan_date),
    INDEX idx_mfg_cap_date (company_id, plan_date),
    CONSTRAINT fk_mfg_cap_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_cap_wc FOREIGN KEY (work_center_id) REFERENCES rateb_mfg_work_centers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_production_calendar (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    title VARCHAR(190) NOT NULL,
    event_type VARCHAR(40) NOT NULL DEFAULT 'shift',
    event_date DATE NOT NULL,
    start_time TIME NULL,
    end_time TIME NULL,
    work_center_id INT UNSIGNED NULL,
    is_holiday TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_cal_uuid (public_uuid),
    INDEX idx_mfg_cal_date (company_id, event_date),
    CONSTRAINT fk_mfg_cal_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_cal_wc FOREIGN KEY (work_center_id) REFERENCES rateb_mfg_work_centers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_schedules (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    work_order_id INT UNSIGNED NULL,
    work_center_id INT UNSIGNED NULL,
    scheduled_start DATETIME NOT NULL,
    scheduled_end DATETIME NOT NULL,
    schedule_status VARCHAR(40) NOT NULL DEFAULT 'planned',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_sch_uuid (public_uuid),
    INDEX idx_mfg_sch_po (company_id, production_order_id),
    INDEX idx_mfg_sch_start (company_id, scheduled_start),
    CONSTRAINT fk_mfg_sch_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_sch_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_sch_wo FOREIGN KEY (work_order_id) REFERENCES rateb_mfg_work_orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_sch_wc FOREIGN KEY (work_center_id) REFERENCES rateb_mfg_work_centers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_material_reservations (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    bom_line_id INT UNSIGNED NULL,
    inventory_item_id INT UNSIGNED NULL,
    component_name VARCHAR(190) NOT NULL,
    qty_reserved DECIMAL(18,6) NOT NULL DEFAULT 0,
    warehouse_id INT UNSIGNED NULL,
    reservation_status VARCHAR(40) NOT NULL DEFAULT 'reserved',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_res_uuid (public_uuid),
    INDEX idx_mfg_res_po (company_id, production_order_id),
    INDEX idx_mfg_res_item (company_id, inventory_item_id),
    CONSTRAINT fk_mfg_res_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_res_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_res_line FOREIGN KEY (bom_line_id) REFERENCES rateb_mfg_bom_lines(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_material_consumptions (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    work_order_id INT UNSIGNED NULL,
    reservation_id INT UNSIGNED NULL,
    inventory_item_id INT UNSIGNED NULL,
    component_name VARCHAR(190) NOT NULL,
    qty_consumed DECIMAL(18,6) NOT NULL DEFAULT 0,
    uom VARCHAR(40) NULL DEFAULT 'EA',
    warehouse_id INT UNSIGNED NULL,
    batch_code VARCHAR(80) NULL,
    serial_code VARCHAR(80) NULL,
    consumed_at DATETIME NULL,
    status ENUM('posted','void','archived') NOT NULL DEFAULT 'posted',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_cons_uuid (public_uuid),
    INDEX idx_mfg_cons_po (company_id, production_order_id),
    CONSTRAINT fk_mfg_cons_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_cons_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_cons_wo FOREIGN KEY (work_order_id) REFERENCES rateb_mfg_work_orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_mfg_cons_res FOREIGN KEY (reservation_id) REFERENCES rateb_mfg_material_reservations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_finished_goods_receipts (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    variant_id INT UNSIGNED NULL,
    inventory_item_id INT UNSIGNED NULL,
    qty_received DECIMAL(18,6) NOT NULL DEFAULT 0,
    uom VARCHAR(40) NULL DEFAULT 'EA',
    warehouse_id INT UNSIGNED NULL,
    batch_code VARCHAR(80) NULL,
    serial_code VARCHAR(80) NULL,
    received_at DATETIME NULL,
    status ENUM('posted','void','archived') NOT NULL DEFAULT 'posted',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_fgr_uuid (public_uuid),
    INDEX idx_mfg_fgr_po (company_id, production_order_id),
    CONSTRAINT fk_mfg_fgr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_fgr_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_fgr_product FOREIGN KEY (product_id) REFERENCES rateb_mfg_products(id) ON DELETE RESTRICT,
    CONSTRAINT fk_mfg_fgr_variant FOREIGN KEY (variant_id) REFERENCES rateb_mfg_product_variants(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_scrap_records (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    work_order_id INT UNSIGNED NULL,
    qty_scrap DECIMAL(18,6) NOT NULL DEFAULT 0,
    uom VARCHAR(40) NULL DEFAULT 'EA',
    reason_code VARCHAR(40) NULL,
    reason TEXT NULL,
    scrap_at DATETIME NULL,
    status ENUM('posted','void','archived') NOT NULL DEFAULT 'posted',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_scrap_uuid (public_uuid),
    INDEX idx_mfg_scrap_po (company_id, production_order_id),
    CONSTRAINT fk_mfg_scrap_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_scrap_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_scrap_wo FOREIGN KEY (work_order_id) REFERENCES rateb_mfg_work_orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_quality_checks (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    work_order_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    check_type VARCHAR(40) NOT NULL DEFAULT 'in_process',
    result_status VARCHAR(40) NOT NULL DEFAULT 'pending',
    checklist_json TEXT NULL,
    checked_at DATETIME NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_qc_uuid (public_uuid),
    UNIQUE KEY uq_mfg_qc_code (company_id, code),
    INDEX idx_mfg_qc_po (company_id, production_order_id),
    CONSTRAINT fk_mfg_qc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_qc_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_qc_wo FOREIGN KEY (work_order_id) REFERENCES rateb_mfg_work_orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_production_costs (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    production_order_id INT UNSIGNED NOT NULL,
    cost_type VARCHAR(40) NOT NULL DEFAULT 'material',
    amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NULL DEFAULT 'SAR',
    cost_center_id INT UNSIGNED NULL,
    accounting_ref VARCHAR(80) NULL,
    cost_date DATE NULL,
    status ENUM('draft','posted','void','archived') NOT NULL DEFAULT 'draft',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_cost_uuid (public_uuid),
    INDEX idx_mfg_cost_po (company_id, production_order_id),
    INDEX idx_mfg_cost_type (company_id, cost_type),
    CONSTRAINT fk_mfg_cost_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_cost_po FOREIGN KEY (production_order_id) REFERENCES rateb_mfg_production_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_timeline (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NULL,
    body TEXT NULL,
    meta_json TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_tl_uuid (public_uuid),
    INDEX idx_mfg_tl_entity (company_id, entity_type, entity_id),
    INDEX idx_mfg_tl_created (company_id, created_at),
    CONSTRAINT fk_mfg_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_assignments (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    assignee_user_id INT UNSIGNED NOT NULL,
    role_label VARCHAR(80) NULL,
    status ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_asg_uuid (public_uuid),
    INDEX idx_mfg_asg_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_mfg_asg_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_comments (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    body TEXT NOT NULL,
    status ENUM('active','hidden','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_cmt_uuid (public_uuid),
    INDEX idx_mfg_cmt_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_mfg_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_attachments_meta (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    file_name VARCHAR(190) NOT NULL,
    mime_type VARCHAR(120) NULL,
    file_size INT UNSIGNED NULL,
    storage_key VARCHAR(255) NULL,
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_att_uuid (public_uuid),
    INDEX idx_mfg_att_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_mfg_att_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_tags (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_tag_uuid (public_uuid),
    UNIQUE KEY uq_mfg_tag_code (company_id, code),
    CONSTRAINT fk_mfg_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_entity_tags (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    tag_id INT UNSIGNED NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_etag_uuid (public_uuid),
    UNIQUE KEY uq_mfg_etag_link (company_id, tag_id, entity_type, entity_id),
    CONSTRAINT fk_mfg_etag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mfg_etag_tag FOREIGN KEY (tag_id) REFERENCES rateb_mfg_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rateb_mfg_status_history (    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mfg_sh_uuid (public_uuid),
    INDEX idx_mfg_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_mfg_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View Manufacturing', 'عرض التصنيع', 'manufacturing.view', 'manufacturing', 'View enterprise manufacturing platform', 'عرض منصة التصنيع المؤسسية'),
('Create Manufacturing', 'إنشاء التصنيع', 'manufacturing.create', 'manufacturing', 'Create manufacturing records', 'إنشاء سجلات التصنيع'),
('Update Manufacturing', 'تحديث التصنيع', 'manufacturing.update', 'manufacturing', 'Update manufacturing records', 'تحديث سجلات التصنيع'),
('Submit Manufacturing', 'تقديم التصنيع', 'manufacturing.submit', 'manufacturing', 'Submit manufacturing workflow transitions', 'تقديم انتقالات سير عمل التصنيع'),
('Manufacturing BOM', 'قوائم المواد', 'manufacturing.bom', 'manufacturing', 'Manage BOMs and versions', 'إدارة قوائم المواد والإصدارات'),
('Manufacturing Planning', 'تخطيط التصنيع', 'manufacturing.planning', 'manufacturing', 'Capacity, calendar, and scheduling', 'السعة والتقويم والجدولة'),
('Manufacturing Shop Floor', 'أرضية المصنع', 'manufacturing.shopfloor', 'manufacturing', 'Production and work orders, materials', 'أوامر الإنتاج والعمل والمواد'),
('Manufacturing Quality', 'جودة التصنيع', 'manufacturing.quality', 'manufacturing', 'Quality checks and scrap', 'فحوصات الجودة والخردة'),
('Manufacturing Admin', 'إدارة التصنيع', 'manufacturing.admin', 'manufacturing', 'Full manufacturing administration', 'إدارة كاملة للتصنيع'),
('Manage Manufacturing', 'إدارة منصة التصنيع', 'manufacturing.manage', 'manufacturing', 'All manufacturing operations', 'جميع عمليات التصنيع')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'manufacturing.view', 'manufacturing.create', 'manufacturing.update', 'manufacturing.submit',
    'manufacturing.bom', 'manufacturing.planning', 'manufacturing.shopfloor', 'manufacturing.quality',
    'manufacturing.admin', 'manufacturing.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
