-- RATEB ERP — Phase 23A Enterprise Human Resources Platform (ONLINE)
-- Additive HRMS layer (rateb_hrm_*). Does NOT alter rateb_employees / rateb_hr_* /
-- attendance / leave / payroll / Offline Foundation / Queue / Replay / SDK / IndexedDB.
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS rateb_hrm_departments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    parent_id INT UNSIGNED NULL,
    manager_profile_id INT UNSIGNED NULL,
    description TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_dept_uuid (public_uuid),
    UNIQUE KEY uq_hrm_dept_code (company_id, code),
    INDEX idx_hrm_dept_company (company_id, deleted_at),
    CONSTRAINT fk_hrm_dept_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_positions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    department_id INT UNSIGNED NULL,
    grade_id INT UNSIGNED NULL,
    description TEXT NULL,
    legacy_job_title_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_pos_uuid (public_uuid),
    UNIQUE KEY uq_hrm_pos_code (company_id, code),
    INDEX idx_hrm_pos_dept (company_id, department_id),
    CONSTRAINT fk_hrm_pos_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_grades (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    level_rank INT NOT NULL DEFAULT 1,
    min_salary DECIMAL(14,2) NULL,
    max_salary DECIMAL(14,2) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_grade_uuid (public_uuid),
    UNIQUE KEY uq_hrm_grade_code (company_id, code),
    INDEX idx_hrm_grade_company (company_id, deleted_at),
    CONSTRAINT fk_hrm_grade_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_locations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    address TEXT NULL,
    city VARCHAR(120) NULL,
    country_code CHAR(2) NULL,
    legacy_workplace_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_loc_uuid (public_uuid),
    UNIQUE KEY uq_hrm_loc_code (company_id, code),
    INDEX idx_hrm_loc_company (company_id, deleted_at),
    CONSTRAINT fk_hrm_loc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_org_units (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    parent_id INT UNSIGNED NULL,
    department_id INT UNSIGNED NULL,
    unit_type VARCHAR(40) NOT NULL DEFAULT 'unit',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_org_uuid (public_uuid),
    UNIQUE KEY uq_hrm_org_code (company_id, code),
    INDEX idx_hrm_org_parent (company_id, parent_id),
    CONSTRAINT fk_hrm_org_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_employee_profiles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    legacy_employee_id INT UNSIGNED NULL,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    first_name_ar VARCHAR(120) NULL,
    last_name_ar VARCHAR(120) NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(40) NULL,
    department_id INT UNSIGNED NULL,
    position_id INT UNSIGNED NULL,
    grade_id INT UNSIGNED NULL,
    location_id INT UNSIGNED NULL,
    org_unit_id INT UNSIGNED NULL,
    manager_profile_id INT UNSIGNED NULL,
    hire_date DATE NULL,
    termination_date DATE NULL,
    employment_type VARCHAR(40) NULL DEFAULT 'full_time',
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_emp_uuid (public_uuid),
    UNIQUE KEY uq_hrm_emp_code (company_id, code),
    INDEX idx_hrm_emp_legacy (company_id, legacy_employee_id),
    INDEX idx_hrm_emp_workflow (company_id, workflow_status),
    INDEX idx_hrm_emp_dept (company_id, department_id),
    CONSTRAINT fk_hrm_emp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_employee_documents_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    doc_type VARCHAR(40) NOT NULL DEFAULT 'general',
    title VARCHAR(190) NOT NULL,
    file_name VARCHAR(190) NULL,
    mime_type VARCHAR(120) NULL,
    file_size INT UNSIGNED NULL,
    storage_key VARCHAR(255) NULL,
    issued_at DATE NULL,
    expires_at DATE NULL,
    legacy_document_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_doc_uuid (public_uuid),
    INDEX idx_hrm_doc_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_doc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_employee_contacts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    contact_type VARCHAR(40) NOT NULL DEFAULT 'personal',
    label VARCHAR(80) NULL,
    value VARCHAR(190) NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_ec_uuid (public_uuid),
    INDEX idx_hrm_ec_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_ec_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_dependents (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    full_name VARCHAR(190) NOT NULL,
    relationship VARCHAR(40) NOT NULL DEFAULT 'child',
    birth_date DATE NULL,
    national_id VARCHAR(80) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_dep_uuid (public_uuid),
    INDEX idx_hrm_dep_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_dep_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_emergency_contacts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    full_name VARCHAR(190) NOT NULL,
    relationship VARCHAR(40) NULL,
    phone VARCHAR(40) NOT NULL,
    email VARCHAR(190) NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_emc_uuid (public_uuid),
    INDEX idx_hrm_emc_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_emc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_certifications (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NULL,
    name VARCHAR(190) NOT NULL,
    issuer VARCHAR(190) NULL,
    issued_at DATE NULL,
    expires_at DATE NULL,
    credential_id VARCHAR(80) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_cert_uuid (public_uuid),
    INDEX idx_hrm_cert_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_cert_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_licenses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NULL,
    name VARCHAR(190) NOT NULL,
    license_number VARCHAR(80) NULL,
    issued_at DATE NULL,
    expires_at DATE NULL,
    authority VARCHAR(190) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_lic_uuid (public_uuid),
    INDEX idx_hrm_lic_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_lic_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_skills (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    category VARCHAR(80) NULL,
    proficiency VARCHAR(40) NULL DEFAULT 'intermediate',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_skill_uuid (public_uuid),
    INDEX idx_hrm_skill_emp (company_id, employee_profile_id),
    INDEX idx_hrm_skill_code (company_id, code),
    CONSTRAINT fk_hrm_skill_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_languages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    language_name VARCHAR(80) NOT NULL,
    proficiency VARCHAR(40) NOT NULL DEFAULT 'intermediate',
    is_native TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_lang_uuid (public_uuid),
    INDEX idx_hrm_lang_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_lang_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_training (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    title_ar VARCHAR(190) NULL,
    provider VARCHAR(190) NULL,
    location_id INT UNSIGNED NULL,
    planned_start DATE NULL,
    planned_end DATE NULL,
    hours DECIMAL(8,2) NOT NULL DEFAULT 0,
    capacity INT UNSIGNED NULL,
    description TEXT NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_trn_uuid (public_uuid),
    UNIQUE KEY uq_hrm_trn_code (company_id, code),
    INDEX idx_hrm_trn_workflow (company_id, workflow_status),
    CONSTRAINT fk_hrm_trn_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_training_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    training_id INT UNSIGNED NOT NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    result_status VARCHAR(40) NOT NULL DEFAULT 'enrolled',
    score DECIMAL(8,2) NULL,
    completed_at DATE NULL,
    certificate_ref VARCHAR(80) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_trnh_uuid (public_uuid),
    UNIQUE KEY uq_hrm_trnh_link (company_id, training_id, employee_profile_id),
    INDEX idx_hrm_trnh_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_trnh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_performance_reviews (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    reviewer_profile_id INT UNSIGNED NULL,
    period_start DATE NULL,
    period_end DATE NULL,
    overall_score DECIMAL(8,2) NULL,
    summary TEXT NULL,
    workflow_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_perf_uuid (public_uuid),
    UNIQUE KEY uq_hrm_perf_code (company_id, code),
    INDEX idx_hrm_perf_emp (company_id, employee_profile_id),
    INDEX idx_hrm_perf_workflow (company_id, workflow_status),
    CONSTRAINT fk_hrm_perf_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_goals (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    review_id INT UNSIGNED NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    target_date DATE NULL,
    progress_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    goal_status VARCHAR(40) NOT NULL DEFAULT 'open',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_goal_uuid (public_uuid),
    INDEX idx_hrm_goal_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_goal_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_competencies (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    category VARCHAR(80) NULL,
    level_score DECIMAL(5,2) NULL,
    description TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_comp_uuid (public_uuid),
    INDEX idx_hrm_comp_emp (company_id, employee_profile_id),
    INDEX idx_hrm_comp_code (company_id, code),
    CONSTRAINT fk_hrm_comp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_disciplinary_actions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    action_type VARCHAR(40) NOT NULL DEFAULT 'warning',
    title VARCHAR(190) NOT NULL,
    action_date DATE NULL,
    severity_date DATE NULL,
    description TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_disc_uuid (public_uuid),
    UNIQUE KEY uq_hrm_disc_code (company_id, code),
    INDEX idx_hrm_disc_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_disc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_rewards (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    reward_type VARCHAR(40) NOT NULL DEFAULT 'recognition',
    title VARCHAR(190) NOT NULL,
    reward_date DATE NULL,
    amount DECIMAL(14,2) NULL,
    description TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_rew_uuid (public_uuid),
    UNIQUE KEY uq_hrm_rew_code (company_id, code),
    INDEX idx_hrm_rew_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_rew_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_transfers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    from_department_id INT UNSIGNED NULL,
    to_department_id INT UNSIGNED NULL,
    from_position_id INT UNSIGNED NULL,
    to_position_id INT UNSIGNED NULL,
    from_location_id INT UNSIGNED NULL,
    to_location_id INT UNSIGNED NULL,
    effective_date DATE NULL,
    transfer_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    reason TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_xfer_uuid (public_uuid),
    UNIQUE KEY uq_hrm_xfer_code (company_id, code),
    INDEX idx_hrm_xfer_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_xfer_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_promotions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    employee_profile_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    from_position_id INT UNSIGNED NULL,
    to_position_id INT UNSIGNED NULL,
    from_grade_id INT UNSIGNED NULL,
    to_grade_id INT UNSIGNED NULL,
    effective_date DATE NULL,
    promotion_status VARCHAR(40) NOT NULL DEFAULT 'draft',
    reason TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_promo_uuid (public_uuid),
    UNIQUE KEY uq_hrm_promo_code (company_id, code),
    INDEX idx_hrm_promo_emp (company_id, employee_profile_id),
    CONSTRAINT fk_hrm_promo_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_assignments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    assignee_user_id INT UNSIGNED NOT NULL,
    role_label VARCHAR(80) NULL,
    status ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_asg_uuid (public_uuid),
    INDEX idx_hrm_asg_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_hrm_asg_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_notes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    title VARCHAR(190) NULL,
    body TEXT NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_note_uuid (public_uuid),
    INDEX idx_hrm_note_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_hrm_note_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    body TEXT NOT NULL,
    status ENUM('active','hidden','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_cmt_uuid (public_uuid),
    INDEX idx_hrm_cmt_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_hrm_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NULL,
    body TEXT NULL,
    meta_json TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_tl_uuid (public_uuid),
    INDEX idx_hrm_tl_entity (company_id, entity_type, entity_id),
    INDEX idx_hrm_tl_created (company_id, created_at),
    CONSTRAINT fk_hrm_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_tag_uuid (public_uuid),
    UNIQUE KEY uq_hrm_tag_code (company_id, code),
    CONSTRAINT fk_hrm_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_entity_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    tag_id INT UNSIGNED NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_etag_uuid (public_uuid),
    UNIQUE KEY uq_hrm_etag_link (company_id, tag_id, entity_type, entity_id),
    CONSTRAINT fk_hrm_etag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_hrm_etag_tag FOREIGN KEY (tag_id) REFERENCES rateb_hrm_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_hrm_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_hrm_sh_uuid (public_uuid),
    INDEX idx_hrm_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_hrm_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View HR', 'عرض الموارد البشرية', 'hr.view', 'hr', 'View human resources', 'عرض الموارد البشرية'),
('Create HR', 'إنشاء الموارد البشرية', 'hr.create', 'hr', 'Create HR enterprise records', 'إنشاء سجلات الموارد البشرية المؤسسية'),
('Update HR', 'تحديث الموارد البشرية', 'hr.update', 'hr', 'Update HR enterprise records', 'تحديث سجلات الموارد البشرية المؤسسية'),
('Delete HR', 'حذف الموارد البشرية', 'hr.delete', 'hr', 'Soft-delete HR enterprise records', 'حذف ناعم لسجلات الموارد البشرية'),
('HR Training', 'التدريب', 'hr.training', 'hr', 'Manage training programs', 'إدارة برامج التدريب'),
('HR Performance', 'الأداء', 'hr.performance', 'hr', 'Manage performance reviews', 'إدارة تقييمات الأداء'),
('HR Promotions', 'الترقيات', 'hr.promotions', 'hr', 'Manage promotions', 'إدارة الترقيات'),
('HR Transfers', 'النقل', 'hr.transfers', 'hr', 'Manage transfers', 'إدارة النقل'),
('HR Admin', 'إدارة الموارد البشرية المتقدمة', 'hr.admin', 'hr', 'Full HRMS administration', 'إدارة كاملة لمنصة الموارد البشرية'),
('Manage HR', 'إدارة الموارد البشرية', 'hr.manage', 'hr', 'All HR operations', 'جميع عمليات الموارد البشرية')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'hr.view', 'hr.create', 'hr.update', 'hr.delete', 'hr.training', 'hr.performance',
    'hr.promotions', 'hr.transfers', 'hr.admin', 'hr.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');