-- RATEB ERP — Phase 24A Enterprise Payroll Platform (ONLINE)
-- Additive payroll layer (rateb_payroll_*). Does NOT alter rateb_payroll_periods / rateb_payroll_lines /
-- rateb_hr_payroll_* / attendance / leave / accounting GL / Offline Foundation / Queue / Replay / SDK / IndexedDB.
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS rateb_payroll_salary_structures (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'SAR',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_sstruct_uuid (public_uuid),
    UNIQUE KEY uq_pay_sstruct_code (company_id, code),
    INDEX idx_pay_sstruct_company (company_id, deleted_at),
    CONSTRAINT fk_pay_sstruct_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_salary_components (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    structure_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    component_type ENUM('earning','deduction') NOT NULL DEFAULT 'earning',
    calc_method ENUM('fixed','percent_basic','percent_gross','formula') NOT NULL DEFAULT 'fixed',
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    percent_value DECIMAL(8,4) NULL,
    earning_type_id INT UNSIGNED NULL,
    deduction_type_id INT UNSIGNED NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_scomp_uuid (public_uuid),
    UNIQUE KEY uq_pay_scomp_code (company_id, structure_id, code),
    INDEX idx_pay_scomp_struct (company_id, structure_id),
    CONSTRAINT fk_pay_scomp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_scomp_struct FOREIGN KEY (structure_id) REFERENCES rateb_payroll_salary_structures(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_earning_types (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    taxable TINYINT(1) NOT NULL DEFAULT 1,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_earn_uuid (public_uuid),
    UNIQUE KEY uq_pay_earn_code (company_id, code),
    INDEX idx_pay_earn_company (company_id, deleted_at),
    CONSTRAINT fk_pay_earn_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_deduction_types (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    statutory TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_ded_uuid (public_uuid),
    UNIQUE KEY uq_pay_ded_code (company_id, code),
    INDEX idx_pay_ded_company (company_id, deleted_at),
    CONSTRAINT fk_pay_ded_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_employee_salary (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    structure_id INT UNSIGNED NULL,
    basic_salary DECIMAL(14,2) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NOT NULL DEFAULT 'SAR',
    effective_from DATE NULL,
    effective_to DATE NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_emp_sal_uuid (public_uuid),
    INDEX idx_pay_emp_sal_profile (company_id, hrm_employee_profile_id),
    INDEX idx_pay_emp_sal_legacy (company_id, legacy_employee_id),
    CONSTRAINT fk_pay_emp_sal_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_emp_sal_struct FOREIGN KEY (structure_id) REFERENCES rateb_payroll_salary_structures(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_cycles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    frequency ENUM('weekly','biweekly','monthly','quarterly','annual') NOT NULL DEFAULT 'monthly',
    start_day TINYINT UNSIGNED NOT NULL DEFAULT 1,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_cycle_uuid (public_uuid),
    UNIQUE KEY uq_pay_cycle_code (company_id, code),
    INDEX idx_pay_cycle_company (company_id, deleted_at),
    CONSTRAINT fk_pay_cycle_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_run_periods (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    cycle_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    pay_date DATE NULL,
    legacy_payroll_period_id INT UNSIGNED NULL,
    status ENUM('open','closed','archived') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_runp_uuid (public_uuid),
    UNIQUE KEY uq_pay_runp_code (company_id, code),
    INDEX idx_pay_runp_cycle (company_id, cycle_id, period_start),
    CONSTRAINT fk_pay_runp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_runp_cycle FOREIGN KEY (cycle_id) REFERENCES rateb_payroll_cycles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_batches (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    cycle_id INT UNSIGNED NULL,
    run_period_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    title_ar VARCHAR(190) NULL,
    period_start DATE NULL,
    period_end DATE NULL,
    pay_date DATE NULL,
    workflow_status ENUM('draft','prepared','calculated','reviewed','approved','posted','closed','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    total_gross DECIMAL(16,2) NOT NULL DEFAULT 0,
    total_deductions DECIMAL(16,2) NOT NULL DEFAULT 0,
    total_net DECIMAL(16,2) NOT NULL DEFAULT 0,
    employee_count INT UNSIGNED NOT NULL DEFAULT 0,
    accounting_post_ref VARCHAR(120) NULL,
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_batch_uuid (public_uuid),
    UNIQUE KEY uq_pay_batch_code (company_id, code),
    INDEX idx_pay_batch_wf (company_id, workflow_status, deleted_at),
    CONSTRAINT fk_pay_batch_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_batch_cycle FOREIGN KEY (cycle_id) REFERENCES rateb_payroll_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_pay_batch_runp FOREIGN KEY (run_period_id) REFERENCES rateb_payroll_run_periods(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NOT NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    employee_salary_id INT UNSIGNED NULL,
    basic_salary DECIMAL(14,2) NOT NULL DEFAULT 0,
    gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    deduction_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    attendance_ref VARCHAR(80) NULL,
    leave_ref VARCHAR(80) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_item_uuid (public_uuid),
    INDEX idx_pay_item_batch (company_id, batch_id),
    INDEX idx_pay_item_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_item_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_item_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_item_emp_sal FOREIGN KEY (employee_salary_id) REFERENCES rateb_payroll_employee_salary(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_payslips (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NOT NULL,
    payroll_item_id INT UNSIGNED NOT NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    payslip_number VARCHAR(40) NOT NULL,
    period_start DATE NULL,
    period_end DATE NULL,
    pay_date DATE NULL,
    gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    deduction_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    workflow_status ENUM('draft','issued','acknowledged','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_pslip_uuid (public_uuid),
    UNIQUE KEY uq_pay_pslip_no (company_id, payslip_number),
    INDEX idx_pay_pslip_batch (company_id, batch_id),
    CONSTRAINT fk_pay_pslip_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_pslip_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_pslip_item FOREIGN KEY (payroll_item_id) REFERENCES rateb_payroll_items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_overtime (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    overtime_date DATE NOT NULL,
    hours DECIMAL(8,2) NOT NULL DEFAULT 0,
    rate_multiplier DECIMAL(6,2) NOT NULL DEFAULT 1.5,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    attendance_ref VARCHAR(80) NULL,
    status ENUM('pending','approved','paid','rejected','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_ot_uuid (public_uuid),
    INDEX idx_pay_ot_emp (company_id, hrm_employee_profile_id, overtime_date),
    CONSTRAINT fk_pay_ot_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_ot_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_bonuses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    bonus_date DATE NULL,
    status ENUM('pending','approved','paid','cancelled','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_bonus_uuid (public_uuid),
    INDEX idx_pay_bonus_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_bonus_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_bonus_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_commissions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    commission_date DATE NULL,
    status ENUM('pending','approved','paid','cancelled','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_comm_uuid (public_uuid),
    INDEX idx_pay_comm_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_comm_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_comm_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_loans (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    principal_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    outstanding_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    installment_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    installments_total INT UNSIGNED NOT NULL DEFAULT 0,
    installments_paid INT UNSIGNED NOT NULL DEFAULT 0,
    start_date DATE NULL,
    status ENUM('active','paused','closed','written_off','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_loan_uuid (public_uuid),
    UNIQUE KEY uq_pay_loan_code (company_id, code),
    INDEX idx_pay_loan_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_loan_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_loan_installments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    loan_id INT UNSIGNED NOT NULL,
    batch_id INT UNSIGNED NULL,
    installment_no INT UNSIGNED NOT NULL DEFAULT 1,
    due_date DATE NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    status ENUM('pending','paid','skipped','cancelled','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_loan_inst_uuid (public_uuid),
    INDEX idx_pay_loan_inst_loan (company_id, loan_id, due_date),
    CONSTRAINT fk_pay_loan_inst_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_loan_inst_loan FOREIGN KEY (loan_id) REFERENCES rateb_payroll_loans(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_loan_inst_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_advances (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    advance_date DATE NOT NULL,
    recovery_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    status ENUM('pending','approved','recovered','cancelled','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_adv_uuid (public_uuid),
    UNIQUE KEY uq_pay_adv_code (company_id, code),
    INDEX idx_pay_adv_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_adv_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_adv_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_reimbursements (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    expense_date DATE NULL,
    status ENUM('pending','approved','paid','rejected','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_reimb_uuid (public_uuid),
    INDEX idx_pay_reimb_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_reimb_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_reimb_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_settlements (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    settlement_type ENUM('final','partial','eos') NOT NULL DEFAULT 'final',
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    settlement_date DATE NULL,
    status ENUM('draft','approved','paid','archived') NOT NULL DEFAULT 'draft',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_settle_uuid (public_uuid),
    INDEX idx_pay_settle_emp (company_id, hrm_employee_profile_id),
    CONSTRAINT fk_pay_settle_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_settle_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_adjustments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    batch_id INT UNSIGNED NULL,
    payroll_item_id INT UNSIGNED NULL,
    hrm_employee_profile_id INT UNSIGNED NULL,
    legacy_employee_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    adjustment_type ENUM('earning','deduction','correction') NOT NULL DEFAULT 'correction',
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    reason VARCHAR(255) NULL,
    status ENUM('pending','applied','reversed','archived') NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_adj_uuid (public_uuid),
    INDEX idx_pay_adj_batch (company_id, batch_id),
    CONSTRAINT fk_pay_adj_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_adj_batch FOREIGN KEY (batch_id) REFERENCES rateb_payroll_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_pay_adj_item FOREIGN KEY (payroll_item_id) REFERENCES rateb_payroll_items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_notes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_note_uuid (public_uuid),
    INDEX idx_pay_note_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_pay_note_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    comment_text TEXT NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_comment_uuid (public_uuid),
    INDEX idx_pay_comment_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_pay_comment_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_tl_uuid (public_uuid),
    INDEX idx_pay_tl_company (company_id, created_at),
    INDEX idx_pay_tl_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_pay_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_attachments_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    doc_type VARCHAR(40) NOT NULL DEFAULT 'attachment',
    title VARCHAR(190) NOT NULL,
    file_name VARCHAR(255) NULL,
    mime_type VARCHAR(120) NULL,
    file_size INT UNSIGNED NULL,
    storage_key VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_att_uuid (public_uuid),
    INDEX idx_pay_att_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_pay_att_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_sh_uuid (public_uuid),
    INDEX idx_pay_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_pay_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_assignments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    assignee_user_id INT UNSIGNED NULL,
    role_label VARCHAR(80) NULL,
    status ENUM('active','completed','cancelled','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_assign_uuid (public_uuid),
    INDEX idx_pay_assign_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_pay_assign_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_payroll_audit (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    action VARCHAR(60) NOT NULL,
    payload_json JSON NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_pay_audit_uuid (public_uuid),
    INDEX idx_pay_audit_entity (company_id, entity_type, entity_id, created_at),
    CONSTRAINT fk_pay_audit_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View Payroll', 'عرض الرواتب', 'payroll.view', 'payroll', 'View enterprise payroll', 'عرض منصة الرواتب المؤسسية'),
('Create Payroll', 'إنشاء الرواتب', 'payroll.create', 'payroll', 'Create payroll records', 'إنشاء سجلات الرواتب'),
('Calculate Payroll', 'حساب الرواتب', 'payroll.calculate', 'payroll', 'Run payroll calculations', 'تشغيل حسابات الرواتب'),
('Review Payroll', 'مراجعة الرواتب', 'payroll.review', 'payroll', 'Review payroll batches', 'مراجعة دفعات الرواتب'),
('Approve Payroll', 'اعتماد الرواتب', 'payroll.approve', 'payroll', 'Approve payroll batches', 'اعتماد دفعات الرواتب'),
('Post Payroll', 'ترحيل الرواتب', 'payroll.post', 'payroll', 'Post payroll (no auto GL)', 'ترحيل الرواتب (بدون قيود تلقائية)'),
('Payroll Admin', 'إدارة الرواتب المتقدمة', 'payroll.admin', 'payroll', 'Full payroll administration', 'إدارة كاملة لمنصة الرواتب'),
('Manage Payroll', 'إدارة الرواتب', 'payroll.manage', 'payroll', 'All payroll operations', 'جميع عمليات الرواتب')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'payroll.view', 'payroll.create', 'payroll.calculate', 'payroll.review',
    'payroll.approve', 'payroll.post', 'payroll.admin', 'payroll.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
