-- RATEB ERP — Phase 25A Enterprise Quality Management Platform (ONLINE)
-- Additive QMS layer (rateb_qms_*). Does NOT alter rateb_mfg_quality_checks /
-- rateb_eam_inspections / Offline Foundation / Queue / Replay / SDK / IndexedDB.
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS rateb_qms_programs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    owner_user_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_prog_uuid (public_uuid),
    UNIQUE KEY uq_qms_prog_code (company_id, code),
    INDEX idx_qms_prog_company (company_id, deleted_at),
    CONSTRAINT fk_qms_prog_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_plans (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    program_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    scope_text TEXT NULL,
    effective_from DATE NULL,
    effective_to DATE NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_plan_uuid (public_uuid),
    UNIQUE KEY uq_qms_plan_code (company_id, code),
    INDEX idx_qms_plan_company (company_id, deleted_at),
    CONSTRAINT fk_qms_plan_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_plan_prog FOREIGN KEY (program_id) REFERENCES rateb_qms_programs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_standards (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    standard_ref VARCHAR(120) NULL,
    revision VARCHAR(40) NULL,
    description TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_std_uuid (public_uuid),
    UNIQUE KEY uq_qms_std_code (company_id, code),
    INDEX idx_qms_std_company (company_id, deleted_at),
    CONSTRAINT fk_qms_std_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_checklists (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    plan_id INT UNSIGNED NULL,
    standard_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    checklist_type VARCHAR(40) NOT NULL DEFAULT 'inspection',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_chk_uuid (public_uuid),
    UNIQUE KEY uq_qms_chk_code (company_id, code),
    INDEX idx_qms_chk_company (company_id, deleted_at),
    CONSTRAINT fk_qms_chk_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_chk_plan FOREIGN KEY (plan_id) REFERENCES rateb_qms_plans(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_chk_std FOREIGN KEY (standard_id) REFERENCES rateb_qms_standards(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_checklist_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    checklist_id INT UNSIGNED NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    item_code VARCHAR(40) NULL,
    item_text VARCHAR(255) NOT NULL,
    is_required TINYINT(1) NOT NULL DEFAULT 1,
    pass_criteria VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_chki_uuid (public_uuid),
    INDEX idx_qms_chki_chk (company_id, checklist_id, sort_order),
    CONSTRAINT fk_qms_chki_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_chki_chk FOREIGN KEY (checklist_id) REFERENCES rateb_qms_checklists(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_inspections (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    plan_id INT UNSIGNED NULL,
    checklist_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    title_ar VARCHAR(190) NULL,
    planned_at DATETIME NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    inspector_user_id INT UNSIGNED NULL,
    mfg_quality_check_id INT UNSIGNED NULL,
    eam_inspection_id INT UNSIGNED NULL,
    result_summary VARCHAR(40) NULL,
    workflow_status ENUM('planned','scheduled','in_progress','completed','approved','archived') NOT NULL DEFAULT 'planned',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_insp_uuid (public_uuid),
    UNIQUE KEY uq_qms_insp_code (company_id, code),
    INDEX idx_qms_insp_wf (company_id, workflow_status, deleted_at),
    CONSTRAINT fk_qms_insp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_insp_plan FOREIGN KEY (plan_id) REFERENCES rateb_qms_plans(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_insp_chk FOREIGN KEY (checklist_id) REFERENCES rateb_qms_checklists(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_results (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    inspection_id INT UNSIGNED NOT NULL,
    checklist_item_id INT UNSIGNED NULL,
    result_value VARCHAR(120) NULL,
    result_status ENUM('pass','fail','na','pending') NOT NULL DEFAULT 'pending',
    measured_value DECIMAL(14,4) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_res_uuid (public_uuid),
    INDEX idx_qms_res_insp (company_id, inspection_id),
    CONSTRAINT fk_qms_res_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_res_insp FOREIGN KEY (inspection_id) REFERENCES rateb_qms_inspections(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_defects (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    inspection_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    defect_type VARCHAR(60) NULL,
    quantity DECIMAL(14,2) NOT NULL DEFAULT 1,
    status ENUM('open','contained','closed','archived') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_def_uuid (public_uuid),
    UNIQUE KEY uq_qms_def_code (company_id, code),
    INDEX idx_qms_def_insp (company_id, inspection_id),
    CONSTRAINT fk_qms_def_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_def_insp FOREIGN KEY (inspection_id) REFERENCES rateb_qms_inspections(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_nonconformities (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    inspection_id INT UNSIGNED NULL,
    defect_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    detected_at DATE NULL,
    status ENUM('open','under_review','contained','closed','archived') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_nc_uuid (public_uuid),
    UNIQUE KEY uq_qms_nc_code (company_id, code),
    INDEX idx_qms_nc_company (company_id, deleted_at),
    CONSTRAINT fk_qms_nc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_nc_insp FOREIGN KEY (inspection_id) REFERENCES rateb_qms_inspections(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_nc_def FOREIGN KEY (defect_id) REFERENCES rateb_qms_defects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_root_causes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    nonconformity_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    analysis_method VARCHAR(60) NULL,
    description TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_rc_uuid (public_uuid),
    INDEX idx_qms_rc_nc (company_id, nonconformity_id),
    CONSTRAINT fk_qms_rc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_rc_nc FOREIGN KEY (nonconformity_id) REFERENCES rateb_qms_nonconformities(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_corrective_actions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    nonconformity_id INT UNSIGNED NULL,
    root_cause_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    assignee_user_id INT UNSIGNED NULL,
    due_date DATE NULL,
    verified_at DATETIME NULL,
    workflow_status ENUM('draft','assigned','in_progress','verified','closed','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_ca_uuid (public_uuid),
    UNIQUE KEY uq_qms_ca_code (company_id, code),
    INDEX idx_qms_ca_wf (company_id, workflow_status, deleted_at),
    CONSTRAINT fk_qms_ca_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_ca_nc FOREIGN KEY (nonconformity_id) REFERENCES rateb_qms_nonconformities(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_ca_rc FOREIGN KEY (root_cause_id) REFERENCES rateb_qms_root_causes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_preventive_actions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    nonconformity_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    assignee_user_id INT UNSIGNED NULL,
    due_date DATE NULL,
    workflow_status ENUM('draft','assigned','in_progress','verified','closed','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_pa_uuid (public_uuid),
    UNIQUE KEY uq_qms_pa_code (company_id, code),
    INDEX idx_qms_pa_wf (company_id, workflow_status, deleted_at),
    CONSTRAINT fk_qms_pa_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_pa_nc FOREIGN KEY (nonconformity_id) REFERENCES rateb_qms_nonconformities(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_audits (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    program_id INT UNSIGNED NULL,
    standard_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    audit_type ENUM('internal','external','supplier','process') NOT NULL DEFAULT 'internal',
    planned_start DATE NULL,
    planned_end DATE NULL,
    lead_auditor_user_id INT UNSIGNED NULL,
    workflow_status ENUM('planned','scheduled','in_progress','completed','approved','archived') NOT NULL DEFAULT 'planned',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_aud_uuid (public_uuid),
    UNIQUE KEY uq_qms_aud_code (company_id, code),
    INDEX idx_qms_aud_wf (company_id, workflow_status, deleted_at),
    CONSTRAINT fk_qms_aud_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_aud_prog FOREIGN KEY (program_id) REFERENCES rateb_qms_programs(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_aud_std FOREIGN KEY (standard_id) REFERENCES rateb_qms_standards(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_audit_findings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    audit_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    finding_type ENUM('major','minor','observation','opportunity') NOT NULL DEFAULT 'observation',
    description TEXT NULL,
    status ENUM('open','closed','archived') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_af_uuid (public_uuid),
    INDEX idx_qms_af_aud (company_id, audit_id),
    CONSTRAINT fk_qms_af_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_qms_af_aud FOREIGN KEY (audit_id) REFERENCES rateb_qms_audits(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_complaints (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    complainant VARCHAR(190) NULL,
    complaint_date DATE NULL,
    description TEXT NULL,
    severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    status ENUM('open','investigating','resolved','closed','archived') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_cmp_uuid (public_uuid),
    UNIQUE KEY uq_qms_cmp_code (company_id, code),
    INDEX idx_qms_cmp_company (company_id, deleted_at),
    CONSTRAINT fk_qms_cmp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_supplier_quality (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    supplier_name VARCHAR(190) NOT NULL,
    legacy_supplier_id INT UNSIGNED NULL,
    eproc_profile_id INT UNSIGNED NULL,
    score DECIMAL(5,2) NULL,
    rating VARCHAR(40) NULL,
    last_review_date DATE NULL,
    status ENUM('active','probation','blocked','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_sq_uuid (public_uuid),
    UNIQUE KEY uq_qms_sq_code (company_id, code),
    INDEX idx_qms_sq_company (company_id, deleted_at),
    CONSTRAINT fk_qms_sq_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_training (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    training_date DATE NULL,
    audience VARCHAR(190) NULL,
    hrm_training_id INT UNSIGNED NULL,
    status ENUM('planned','completed','cancelled','archived') NOT NULL DEFAULT 'planned',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_trn_uuid (public_uuid),
    UNIQUE KEY uq_qms_trn_code (company_id, code),
    INDEX idx_qms_trn_company (company_id, deleted_at),
    CONSTRAINT fk_qms_trn_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_documents_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    doc_type VARCHAR(40) NOT NULL DEFAULT 'attachment',
    title VARCHAR(190) NOT NULL,
    file_name VARCHAR(255) NULL,
    mime_type VARCHAR(120) NULL,
    file_size INT UNSIGNED NULL,
    storage_key VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_doc_uuid (public_uuid),
    INDEX idx_qms_doc_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_qms_doc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    comment_text TEXT NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_cmt_uuid (public_uuid),
    INDEX idx_qms_cmt_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_qms_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_assignments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    assignee_user_id INT UNSIGNED NULL,
    role_label VARCHAR(80) NULL,
    status ENUM('active','completed','cancelled','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_asg_uuid (public_uuid),
    INDEX idx_qms_asg_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_qms_asg_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_tl_uuid (public_uuid),
    INDEX idx_qms_tl_company (company_id, created_at),
    INDEX idx_qms_tl_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_qms_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_sh_uuid (public_uuid),
    INDEX idx_qms_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_qms_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_qms_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_qms_tag_uuid (public_uuid),
    UNIQUE KEY uq_qms_tag_code (company_id, code),
    CONSTRAINT fk_qms_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View Quality', 'عرض الجودة', 'quality.view', 'quality', 'View quality management', 'عرض إدارة الجودة'),
('Create Quality', 'إنشاء الجودة', 'quality.create', 'quality', 'Create quality records', 'إنشاء سجلات الجودة'),
('Update Quality', 'تحديث الجودة', 'quality.update', 'quality', 'Update quality records', 'تحديث سجلات الجودة'),
('Inspect Quality', 'فحص الجودة', 'quality.inspect', 'quality', 'Run quality inspections', 'تنفيذ فحوصات الجودة'),
('Audit Quality', 'تدقيق الجودة', 'quality.audit', 'quality', 'Manage quality audits', 'إدارة تدقيقات الجودة'),
('Corrective Actions', 'الإجراءات التصحيحية', 'quality.corrective', 'quality', 'Manage corrective actions', 'إدارة الإجراءات التصحيحية'),
('Preventive Actions', 'الإجراءات الوقائية', 'quality.preventive', 'quality', 'Manage preventive actions', 'إدارة الإجراءات الوقائية'),
('Quality Admin', 'إدارة الجودة المتقدمة', 'quality.admin', 'quality', 'Full quality administration', 'إدارة كاملة لمنصة الجودة'),
('Manage Quality', 'إدارة الجودة', 'quality.manage', 'quality', 'All quality operations', 'جميع عمليات الجودة')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'quality.view', 'quality.create', 'quality.update', 'quality.inspect',
    'quality.audit', 'quality.corrective', 'quality.preventive', 'quality.admin', 'quality.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
