-- RATEB ERP — Phase 26A Enterprise Document Management Platform (ONLINE)
-- Additive DMS layer (rateb_dms_*). Does NOT alter rateb_documents / DocumentService /
-- Offline Foundation / Queue / Replay / SDK / IndexedDB.
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS rateb_dms_repositories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    storage_driver VARCHAR(40) NOT NULL DEFAULT 'local',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_repo_uuid (public_uuid),
    UNIQUE KEY uq_dms_repo_code (company_id, code),
    INDEX idx_dms_repo_company (company_id, deleted_at),
    CONSTRAINT fk_dms_repo_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_folders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    repository_id INT UNSIGNED NOT NULL,
    parent_folder_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    path_text VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_folder_uuid (public_uuid),
    UNIQUE KEY uq_dms_folder_code (company_id, repository_id, code),
    INDEX idx_dms_folder_repo (company_id, repository_id, deleted_at),
    INDEX idx_dms_folder_parent (company_id, parent_folder_id),
    CONSTRAINT fk_dms_folder_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_folder_repo FOREIGN KEY (repository_id) REFERENCES rateb_dms_repositories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_documents (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    repository_id INT UNSIGNED NOT NULL,
    folder_id INT UNSIGNED NULL,
    category_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    title_ar VARCHAR(190) NULL,
    document_type VARCHAR(60) NULL,
    mime_type VARCHAR(120) NULL,
    file_extension VARCHAR(20) NULL,
    current_version_no INT UNSIGNED NOT NULL DEFAULT 1,
    workflow_status ENUM('draft','checked_in','review','approved','published','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    checked_out_by INT UNSIGNED NULL,
    checked_out_at DATETIME NULL,
    published_at DATETIME NULL,
    legacy_document_id INT UNSIGNED NULL,
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_doc_uuid (public_uuid),
    UNIQUE KEY uq_dms_doc_code (company_id, code),
    INDEX idx_dms_doc_wf (company_id, workflow_status, deleted_at),
    INDEX idx_dms_doc_repo (company_id, repository_id, folder_id),
    INDEX idx_dms_doc_search (company_id, title(80), deleted_at),
    CONSTRAINT fk_dms_doc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_doc_repo FOREIGN KEY (repository_id) REFERENCES rateb_dms_repositories(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_doc_folder FOREIGN KEY (folder_id) REFERENCES rateb_dms_folders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_versions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    version_no INT UNSIGNED NOT NULL DEFAULT 1,
    storage_path VARCHAR(500) NULL,
    storage_driver VARCHAR(40) NOT NULL DEFAULT 'local',
    file_size BIGINT UNSIGNED NULL,
    checksum_sha256 CHAR(64) NULL,
    change_summary VARCHAR(255) NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 1,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_ver_uuid (public_uuid),
    UNIQUE KEY uq_dms_ver_no (company_id, document_id, version_no),
    INDEX idx_dms_ver_doc (company_id, document_id, is_current),
    CONSTRAINT fk_dms_ver_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_ver_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_document_metadata (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    meta_key VARCHAR(80) NOT NULL,
    meta_value TEXT NULL,
    value_type VARCHAR(20) NOT NULL DEFAULT 'string',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_meta_uuid (public_uuid),
    UNIQUE KEY uq_dms_meta_key (company_id, document_id, meta_key),
    INDEX idx_dms_meta_doc (company_id, document_id),
    CONSTRAINT fk_dms_meta_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_meta_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_checkouts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    checked_out_at DATETIME NOT NULL,
    due_at DATETIME NULL,
    checked_in_at DATETIME NULL,
    checkout_status ENUM('open','returned','expired') NOT NULL DEFAULT 'open',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_chk_uuid (public_uuid),
    INDEX idx_dms_chk_doc (company_id, document_id, checkout_status),
    CONSTRAINT fk_dms_chk_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_chk_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_shares (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    share_token CHAR(64) NOT NULL,
    shared_with_user_id INT UNSIGNED NULL,
    shared_with_email VARCHAR(190) NULL,
    permission_level ENUM('view','download','edit') NOT NULL DEFAULT 'view',
    expires_at DATETIME NULL,
    share_status ENUM('active','revoked','expired') NOT NULL DEFAULT 'active',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_share_uuid (public_uuid),
    UNIQUE KEY uq_dms_share_token (share_token),
    INDEX idx_dms_share_doc (company_id, document_id, share_status),
    CONSTRAINT fk_dms_share_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_share_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_permissions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    resource_type ENUM('repository','folder','document') NOT NULL DEFAULT 'document',
    resource_id INT UNSIGNED NOT NULL,
    grantee_type ENUM('user','role','branch') NOT NULL DEFAULT 'user',
    grantee_id INT UNSIGNED NOT NULL,
    permission_slug VARCHAR(60) NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_perm_uuid (public_uuid),
    INDEX idx_dms_perm_res (company_id, resource_type, resource_id),
    INDEX idx_dms_perm_grantee (company_id, grantee_type, grantee_id),
    CONSTRAINT fk_dms_perm_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_retention_policies (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    retention_days INT UNSIGNED NOT NULL DEFAULT 365,
    action_on_expiry ENUM('archive','delete','review') NOT NULL DEFAULT 'archive',
    applies_to VARCHAR(60) NOT NULL DEFAULT 'document',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_retpol_uuid (public_uuid),
    UNIQUE KEY uq_dms_retpol_code (company_id, code),
    INDEX idx_dms_retpol_company (company_id, deleted_at),
    CONSTRAINT fk_dms_retpol_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_retention_jobs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    policy_id INT UNSIGNED NOT NULL,
    document_id INT UNSIGNED NULL,
    job_status ENUM('pending','running','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
    scheduled_at DATETIME NULL,
    completed_at DATETIME NULL,
    result_summary VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_retjob_uuid (public_uuid),
    INDEX idx_dms_retjob_policy (company_id, policy_id, job_status),
    CONSTRAINT fk_dms_retjob_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_retjob_policy FOREIGN KEY (policy_id) REFERENCES rateb_dms_retention_policies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_legal_holds (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NULL,
    folder_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    hold_reason TEXT NULL,
    hold_status ENUM('active','released','expired') NOT NULL DEFAULT 'active',
    effective_from DATE NULL,
    effective_to DATE NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_hold_uuid (public_uuid),
    UNIQUE KEY uq_dms_hold_code (company_id, code),
    INDEX idx_dms_hold_doc (company_id, document_id, hold_status),
    CONSTRAINT fk_dms_hold_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    name_ar VARCHAR(120) NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_cat_uuid (public_uuid),
    UNIQUE KEY uq_dms_cat_code (company_id, code),
    CONSTRAINT fk_dms_cat_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_tag_uuid (public_uuid),
    UNIQUE KEY uq_dms_tag_code (company_id, code),
    CONSTRAINT fk_dms_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_document_links (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    linked_entity_type VARCHAR(60) NOT NULL,
    linked_entity_id INT UNSIGNED NOT NULL,
    link_role VARCHAR(40) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_link_uuid (public_uuid),
    INDEX idx_dms_link_entity (company_id, linked_entity_type, linked_entity_id),
    INDEX idx_dms_link_doc (company_id, document_id),
    CONSTRAINT fk_dms_link_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_link_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_document_relations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    source_document_id INT UNSIGNED NOT NULL,
    target_document_id INT UNSIGNED NOT NULL,
    relation_type ENUM('parent','child','related','supersedes','version_of') NOT NULL DEFAULT 'related',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_rel_uuid (public_uuid),
    INDEX idx_dms_rel_src (company_id, source_document_id),
    INDEX idx_dms_rel_tgt (company_id, target_document_id),
    CONSTRAINT fk_dms_rel_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_rel_src FOREIGN KEY (source_document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_rel_tgt FOREIGN KEY (target_document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_approvals_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    approval_stage VARCHAR(60) NOT NULL,
    approver_user_id INT UNSIGNED NULL,
    approval_status ENUM('pending','approved','rejected','skipped') NOT NULL DEFAULT 'pending',
    decided_at DATETIME NULL,
    legacy_approval_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_appr_uuid (public_uuid),
    INDEX idx_dms_appr_doc (company_id, document_id, approval_status),
    CONSTRAINT fk_dms_appr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_appr_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_signature_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    version_id INT UNSIGNED NULL,
    request_code VARCHAR(40) NOT NULL,
    signer_user_id INT UNSIGNED NULL,
    signer_email VARCHAR(190) NULL,
    request_status ENUM('pending','signed','declined','expired','cancelled') NOT NULL DEFAULT 'pending',
    requested_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_sigreq_uuid (public_uuid),
    UNIQUE KEY uq_dms_sigreq_code (company_id, request_code),
    INDEX idx_dms_sigreq_doc (company_id, document_id, request_status),
    CONSTRAINT fk_dms_sigreq_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_sigreq_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_signature_events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    signature_request_id INT UNSIGNED NOT NULL,
    event_type ENUM('sent','viewed','signed','declined','reminded') NOT NULL DEFAULT 'sent',
    event_at DATETIME NOT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_sigev_uuid (public_uuid),
    INDEX idx_dms_sigev_req (company_id, signature_request_id, event_at),
    CONSTRAINT fk_dms_sigev_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_sigev_req FOREIGN KEY (signature_request_id) REFERENCES rateb_dms_signature_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_audit_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NULL,
    action_type VARCHAR(60) NOT NULL,
    actor_user_id INT UNSIGNED NULL,
    resource_type VARCHAR(40) NULL,
    resource_id INT UNSIGNED NULL,
    detail_text TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_audit_uuid (public_uuid),
    INDEX idx_dms_audit_doc (company_id, document_id, created_at),
    INDEX idx_dms_audit_action (company_id, action_type, created_at),
    CONSTRAINT fk_dms_audit_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_tl_uuid (public_uuid),
    INDEX idx_dms_tl_company (company_id, created_at),
    INDEX idx_dms_tl_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_dms_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    comment_text TEXT NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_cmt_uuid (public_uuid),
    INDEX idx_dms_cmt_doc (company_id, document_id, created_at),
    CONSTRAINT fk_dms_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_cmt_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_favorites (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    user_id INT UNSIGNED NOT NULL,
    document_id INT UNSIGNED NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_fav_uuid (public_uuid),
    UNIQUE KEY uq_dms_fav_user_doc (company_id, user_id, document_id),
    INDEX idx_dms_fav_user (company_id, user_id),
    CONSTRAINT fk_dms_fav_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_fav_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_recent_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    user_id INT UNSIGNED NOT NULL,
    document_id INT UNSIGNED NOT NULL,
    accessed_at DATETIME NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_recent_uuid (public_uuid),
    INDEX idx_dms_recent_user (company_id, user_id, accessed_at),
    CONSTRAINT fk_dms_recent_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_recent_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_search_index (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    document_id INT UNSIGNED NOT NULL,
    title_index VARCHAR(190) NOT NULL,
    content_snippet TEXT NULL,
    tag_text VARCHAR(500) NULL,
    category_text VARCHAR(120) NULL,
    indexed_at DATETIME NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_sidx_uuid (public_uuid),
    UNIQUE KEY uq_dms_sidx_doc (company_id, document_id),
    INDEX idx_dms_sidx_title (company_id, title_index(80)),
    CONSTRAINT fk_dms_sidx_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_dms_sidx_doc FOREIGN KEY (document_id) REFERENCES rateb_dms_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_dms_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_dms_sh_uuid (public_uuid),
    INDEX idx_dms_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_dms_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View Documents', 'عرض المستندات', 'documents.view', 'documents', 'View enterprise documents', 'عرض مستندات المؤسسة'),
('Create Documents', 'إنشاء المستندات', 'documents.create', 'documents', 'Create enterprise documents', 'إنشاء مستندات المؤسسة'),
('Update Documents', 'تحديث المستندات', 'documents.update', 'documents', 'Update enterprise documents', 'تحديث مستندات المؤسسة'),
('Share Documents', 'مشاركة المستندات', 'documents.share', 'documents', 'Share documents externally', 'مشاركة المستندات'),
('Download Documents', 'تنزيل المستندات', 'documents.download', 'documents', 'Download document files', 'تنزيل ملفات المستندات'),
('Document Retention', 'الاحتفاظ بالمستندات', 'documents.retention', 'documents', 'Manage retention policies', 'إدارة سياسات الاحتفاظ'),
('Documents Admin', 'إدارة المستندات المتقدمة', 'documents.admin', 'documents', 'Full DMS administration', 'إدارة كاملة لمنصة المستندات'),
('Manage Documents', 'إدارة المستندات', 'documents.manage', 'documents', 'All document operations', 'جميع عمليات المستندات')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'documents.view', 'documents.create', 'documents.update', 'documents.share',
    'documents.download', 'documents.retention', 'documents.admin', 'documents.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
