-- RATEB ERP — Phase 27A Enterprise Business Intelligence & Analytics Platform (ONLINE)
-- Additive BI layer (rateb_bi_*). Soft-links CRM/Projects/Accounting/HR/Payroll/MFG/Assets/
-- Procurement/Quality/Documents/POS/Inventory/Recruitment only — NEVER ALTER those modules.
-- Offline Foundation / Queue / Replay / SDK / IndexedDB NOT modified (27B deferred).
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS rateb_bi_dashboards (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    dashboard_type ENUM('executive','department','branch','company','custom') NOT NULL DEFAULT 'custom',
    owner_user_id INT UNSIGNED NULL,
    layout_json TEXT NULL,
    workflow_status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    published_at DATETIME NULL,
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_dash_uuid (public_uuid),
    UNIQUE KEY uq_bi_dash_code (company_id, code),
    INDEX idx_bi_dash_wf (company_id, workflow_status, deleted_at),
    INDEX idx_bi_dash_type (company_id, dashboard_type, deleted_at),
    CONSTRAINT fk_bi_dash_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_widgets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    dashboard_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    title_ar VARCHAR(190) NULL,
    widget_type ENUM('kpi','chart','table','list','gauge','text') NOT NULL DEFAULT 'kpi',
    data_source VARCHAR(80) NULL,
    config_json TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_wid_uuid (public_uuid),
    UNIQUE KEY uq_bi_wid_code (company_id, dashboard_id, code),
    INDEX idx_bi_wid_dash (company_id, dashboard_id, sort_order),
    CONSTRAINT fk_bi_wid_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_bi_wid_dash FOREIGN KEY (dashboard_id) REFERENCES rateb_bi_dashboards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_kpis (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    metric_key VARCHAR(80) NOT NULL,
    unit VARCHAR(40) NULL,
    target_value DECIMAL(18,4) NULL,
    direction ENUM('higher_better','lower_better','neutral') NOT NULL DEFAULT 'higher_better',
    source_module VARCHAR(40) NULL,
    formula_text VARCHAR(255) NULL,
    workflow_status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_kpi_uuid (public_uuid),
    UNIQUE KEY uq_bi_kpi_code (company_id, code),
    INDEX idx_bi_kpi_wf (company_id, workflow_status, deleted_at),
    INDEX idx_bi_kpi_mod (company_id, source_module),
    CONSTRAINT fk_bi_kpi_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_kpi_snapshots (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    kpi_id INT UNSIGNED NOT NULL,
    snapshot_at DATETIME NOT NULL,
    metric_value DECIMAL(18,4) NOT NULL DEFAULT 0,
    period_key VARCHAR(40) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_ks_uuid (public_uuid),
    INDEX idx_bi_ks_kpi (company_id, kpi_id, snapshot_at),
    CONSTRAINT fk_bi_ks_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_bi_ks_kpi FOREIGN KEY (kpi_id) REFERENCES rateb_bi_kpis(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_reports (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    report_type ENUM('saved','drilldown','department','branch','company','cross_module','trend') NOT NULL DEFAULT 'saved',
    source_module VARCHAR(40) NULL,
    query_meta_json TEXT NULL,
    filters_json TEXT NULL,
    workflow_status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    published_at DATETIME NULL,
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_rpt_uuid (public_uuid),
    UNIQUE KEY uq_bi_rpt_code (company_id, code),
    INDEX idx_bi_rpt_wf (company_id, workflow_status, deleted_at),
    INDEX idx_bi_rpt_type (company_id, report_type, deleted_at),
    CONSTRAINT fk_bi_rpt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_report_runs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    report_id INT UNSIGNED NOT NULL,
    run_status ENUM('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    row_count INT UNSIGNED NULL,
    result_summary VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_run_uuid (public_uuid),
    INDEX idx_bi_run_rpt (company_id, report_id, created_at),
    CONSTRAINT fk_bi_run_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_bi_run_rpt FOREIGN KEY (report_id) REFERENCES rateb_bi_reports(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_datasets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    source_module VARCHAR(40) NOT NULL,
    entity_hint VARCHAR(80) NULL,
    refresh_mode ENUM('manual','scheduled','on_demand') NOT NULL DEFAULT 'manual',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_ds_uuid (public_uuid),
    UNIQUE KEY uq_bi_ds_code (company_id, code),
    INDEX idx_bi_ds_mod (company_id, source_module, deleted_at),
    CONSTRAINT fk_bi_ds_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_dataset_links (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    dataset_id INT UNSIGNED NOT NULL,
    linked_module VARCHAR(40) NOT NULL,
    linked_entity_type VARCHAR(60) NOT NULL,
    linked_entity_id INT UNSIGNED NULL,
    link_role VARCHAR(40) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_dsl_uuid (public_uuid),
    INDEX idx_bi_dsl_ds (company_id, dataset_id),
    INDEX idx_bi_dsl_mod (company_id, linked_module, linked_entity_type),
    CONSTRAINT fk_bi_dsl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_bi_dsl_ds FOREIGN KEY (dataset_id) REFERENCES rateb_bi_datasets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_drilldowns (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    report_id INT UNSIGNED NULL,
    parent_level VARCHAR(60) NOT NULL,
    child_level VARCHAR(60) NOT NULL,
    config_json TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_dd_uuid (public_uuid),
    INDEX idx_bi_dd_rpt (company_id, report_id),
    CONSTRAINT fk_bi_dd_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_bi_dd_rpt FOREIGN KEY (report_id) REFERENCES rateb_bi_reports(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_trends (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    kpi_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    period_grain ENUM('day','week','month','quarter','year') NOT NULL DEFAULT 'month',
    series_json TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_tr_uuid (public_uuid),
    UNIQUE KEY uq_bi_tr_code (company_id, code),
    INDEX idx_bi_tr_kpi (company_id, kpi_id),
    CONSTRAINT fk_bi_tr_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_forecasts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    kpi_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    horizon_periods INT UNSIGNED NOT NULL DEFAULT 3,
    method_hint VARCHAR(60) NULL,
    forecast_json TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_fc_uuid (public_uuid),
    UNIQUE KEY uq_bi_fc_code (company_id, code),
    INDEX idx_bi_fc_kpi (company_id, kpi_id),
    CONSTRAINT fk_bi_fc_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_alerts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    kpi_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    threshold_value DECIMAL(18,4) NULL,
    comparison ENUM('gt','gte','lt','lte','eq') NOT NULL DEFAULT 'gt',
    alert_status ENUM('active','triggered','acknowledged','disabled') NOT NULL DEFAULT 'active',
    last_triggered_at DATETIME NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_al_uuid (public_uuid),
    UNIQUE KEY uq_bi_al_code (company_id, code),
    INDEX idx_bi_al_kpi (company_id, kpi_id, alert_status),
    CONSTRAINT fk_bi_al_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_schedules (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    report_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    cron_hint VARCHAR(80) NULL,
    next_run_at DATETIME NULL,
    schedule_status ENUM('active','paused','completed') NOT NULL DEFAULT 'active',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_sch_uuid (public_uuid),
    UNIQUE KEY uq_bi_sch_code (company_id, code),
    INDEX idx_bi_sch_rpt (company_id, report_id),
    CONSTRAINT fk_bi_sch_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_exports (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    report_id INT UNSIGNED NULL,
    export_format ENUM('csv','xlsx','pdf','json') NOT NULL DEFAULT 'csv',
    export_status ENUM('pending','ready','failed','expired') NOT NULL DEFAULT 'pending',
    storage_path VARCHAR(500) NULL,
    requested_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_exp_uuid (public_uuid),
    INDEX idx_bi_exp_rpt (company_id, report_id, export_status),
    CONSTRAINT fk_bi_exp_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_analytics_scopes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    scope_type ENUM('company','branch','department') NOT NULL DEFAULT 'company',
    scope_ref_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_as_uuid (public_uuid),
    UNIQUE KEY uq_bi_as_code (company_id, code),
    INDEX idx_bi_as_type (company_id, scope_type, deleted_at),
    CONSTRAINT fk_bi_as_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    comment_text TEXT NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_cmt_uuid (public_uuid),
    INDEX idx_bi_cmt_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_bi_cmt_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_tl_uuid (public_uuid),
    INDEX idx_bi_tl_company (company_id, created_at),
    INDEX idx_bi_tl_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_bi_tl_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_sh_uuid (public_uuid),
    INDEX idx_bi_sh_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_bi_sh_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_audit_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    action_type VARCHAR(60) NOT NULL,
    actor_user_id INT UNSIGNED NULL,
    entity_type VARCHAR(40) NULL,
    entity_id INT UNSIGNED NULL,
    detail_text TEXT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_aud_uuid (public_uuid),
    INDEX idx_bi_aud_action (company_id, action_type, created_at),
    CONSTRAINT fk_bi_aud_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_favorites (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    user_id INT UNSIGNED NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_fav_uuid (public_uuid),
    UNIQUE KEY uq_bi_fav_user (company_id, user_id, entity_type, entity_id),
    CONSTRAINT fk_bi_fav_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_bi_tags (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_bi_tag_uuid (public_uuid),
    UNIQUE KEY uq_bi_tag_code (company_id, code),
    CONSTRAINT fk_bi_tag_company FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rateb_permissions (name, name_ar, slug, module, description, description_ar) VALUES
('View BI', 'عرض التحليلات', 'bi.view', 'bi', 'View business intelligence', 'عرض ذكاء الأعمال'),
('Create BI', 'إنشاء التحليلات', 'bi.create', 'bi', 'Create BI dashboards and reports', 'إنشاء لوحات وتقارير التحليلات'),
('Update BI', 'تحديث التحليلات', 'bi.update', 'bi', 'Update BI records', 'تحديث سجلات التحليلات'),
('Publish BI', 'نشر التحليلات', 'bi.publish', 'bi', 'Publish BI dashboards and reports', 'نشر لوحات وتقارير التحليلات'),
('Export BI', 'تصدير التحليلات', 'bi.export', 'bi', 'Export BI reports', 'تصدير تقارير التحليلات'),
('BI Admin', 'إدارة التحليلات المتقدمة', 'bi.admin', 'bi', 'Full BI administration', 'إدارة كاملة لمنصة التحليلات'),
('Manage BI', 'إدارة التحليلات', 'bi.manage', 'bi', 'All BI operations', 'جميع عمليات التحليلات')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module), description = VALUES(description);

INSERT IGNORE INTO rateb_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM rateb_roles r
JOIN rateb_permissions p ON p.slug IN (
    'bi.view', 'bi.create', 'bi.update', 'bi.publish', 'bi.export', 'bi.admin', 'bi.manage'
)
WHERE r.slug IN ('company-full-access', 'super-admin');
