-- Phase 1 — CRM Sales Quotations (additive; no ALTER/DROP on existing CRM tables)
-- Extends classic Phase 17A CRM — does not replace rateb_crm_* foundation.

CREATE TABLE IF NOT EXISTS rateb_crm_quotations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    quotation_no VARCHAR(40) NOT NULL,
    title VARCHAR(190) NOT NULL,
    lead_id INT UNSIGNED NULL,
    opportunity_id INT UNSIGNED NULL,
    customer_id INT UNSIGNED NULL,
    crm_company_id INT UNSIGNED NULL,
    contact_id INT UNSIGNED NULL,
    owner_user_id INT UNSIGNED NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    currency_code CHAR(3) NOT NULL DEFAULT 'SAR',
    subtotal DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    valid_until DATE NULL,
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_crm_quote_uuid (public_uuid),
    UNIQUE KEY uq_crm_quote_no (company_id, quotation_no),
    INDEX idx_crm_quote_company (company_id, deleted_at),
    INDEX idx_crm_quote_status (company_id, status),
    INDEX idx_crm_quote_lead (lead_id),
    INDEX idx_crm_quote_opp (opportunity_id),
    INDEX idx_crm_quote_customer (customer_id),
    INDEX idx_crm_quote_owner (owner_user_id),
    CONSTRAINT fk_crm_quote_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_crm_quote_lead FOREIGN KEY (lead_id) REFERENCES rateb_crm_leads(id) ON DELETE SET NULL,
    CONSTRAINT fk_crm_quote_opp FOREIGN KEY (opportunity_id) REFERENCES rateb_crm_opportunities(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_crm_quotation_lines (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    quotation_id INT UNSIGNED NOT NULL,
    line_no INT UNSIGNED NOT NULL DEFAULT 1,
    item_name VARCHAR(190) NOT NULL,
    description TEXT NULL,
    quantity DECIMAL(14,3) NOT NULL DEFAULT 1.000,
    unit_price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    tax_rate DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
    line_subtotal DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    line_tax DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    sort_order INT NOT NULL DEFAULT 0,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_crm_quote_line_uuid (public_uuid),
    INDEX idx_crm_quote_line_company (company_id, deleted_at),
    INDEX idx_crm_quote_line_parent (quotation_id, sort_order),
    CONSTRAINT fk_crm_quote_line_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_crm_quote_line_quote FOREIGN KEY (quotation_id) REFERENCES rateb_crm_quotations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
