-- Phase 1 — Marketplace foundation (tenant-scoped). Structure only; full commerce in later phases.
-- Distinct from website Theme Marketplace.

CREATE TABLE IF NOT EXISTS rateb_mp_providers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(40) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_provider_uuid (public_uuid),
    UNIQUE KEY uq_mp_provider_code (company_id, code),
    INDEX idx_mp_provider_company (company_id, deleted_at),
    INDEX idx_mp_provider_status (company_id, status),
    CONSTRAINT fk_mp_provider_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    parent_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_cat_uuid (public_uuid),
    UNIQUE KEY uq_mp_cat_code (company_id, code),
    INDEX idx_mp_cat_company (company_id, deleted_at),
    INDEX idx_mp_cat_parent (parent_id),
    CONSTRAINT fk_mp_cat_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_services (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    provider_id INT UNSIGNED NULL,
    category_id INT UNSIGNED NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(190) NOT NULL,
    name_ar VARCHAR(190) NULL,
    description TEXT NULL,
    base_price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    currency_code CHAR(3) NOT NULL DEFAULT 'SAR',
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_svc_uuid (public_uuid),
    UNIQUE KEY uq_mp_svc_code (company_id, code),
    INDEX idx_mp_svc_company (company_id, deleted_at),
    INDEX idx_mp_svc_provider (provider_id),
    INDEX idx_mp_svc_category (category_id),
    CONSTRAINT fk_mp_svc_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mp_svc_provider FOREIGN KEY (provider_id) REFERENCES rateb_mp_providers(id) ON DELETE SET NULL,
    CONSTRAINT fk_mp_svc_category FOREIGN KEY (category_id) REFERENCES rateb_mp_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_service_availability (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    service_id INT UNSIGNED NOT NULL,
    weekday TINYINT UNSIGNED NULL,
    starts_at TIME NULL,
    ends_at TIME NULL,
    capacity INT UNSIGNED NULL,
    is_available TINYINT(1) NOT NULL DEFAULT 1,
    notes VARCHAR(255) NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_avail_uuid (public_uuid),
    INDEX idx_mp_avail_company (company_id, deleted_at),
    INDEX idx_mp_avail_service (service_id),
    CONSTRAINT fk_mp_avail_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mp_avail_service FOREIGN KEY (service_id) REFERENCES rateb_mp_services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_service_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    service_id INT UNSIGNED NULL,
    provider_id INT UNSIGNED NULL,
    customer_id INT UNSIGNED NULL,
    portal_user_id INT UNSIGNED NULL,
    request_no VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    requested_at DATETIME NULL,
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_req_uuid (public_uuid),
    UNIQUE KEY uq_mp_req_no (company_id, request_no),
    INDEX idx_mp_req_company (company_id, deleted_at),
    INDEX idx_mp_req_status (company_id, status),
    CONSTRAINT fk_mp_req_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_orders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    provider_id INT UNSIGNED NULL,
    customer_id INT UNSIGNED NULL,
    service_request_id INT UNSIGNED NULL,
    order_no VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    currency_code CHAR(3) NOT NULL DEFAULT 'SAR',
    subtotal DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    invoice_id INT UNSIGNED NULL,
    payment_id INT UNSIGNED NULL,
    shipment_id INT UNSIGNED NULL,
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_order_uuid (public_uuid),
    UNIQUE KEY uq_mp_order_no (company_id, order_no),
    INDEX idx_mp_order_company (company_id, deleted_at),
    INDEX idx_mp_order_status (company_id, status),
    INDEX idx_mp_order_customer (customer_id),
    CONSTRAINT fk_mp_order_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_order_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    order_id INT UNSIGNED NOT NULL,
    service_id INT UNSIGNED NULL,
    item_name VARCHAR(190) NOT NULL,
    quantity DECIMAL(14,3) NOT NULL DEFAULT 1.000,
    unit_price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    sort_order INT NOT NULL DEFAULT 0,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_order_item_uuid (public_uuid),
    INDEX idx_mp_order_item_company (company_id, deleted_at),
    INDEX idx_mp_order_item_parent (order_id, sort_order),
    CONSTRAINT fk_mp_order_item_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_mp_order_item_order FOREIGN KEY (order_id) REFERENCES rateb_mp_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_reviews (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_uuid CHAR(36) NOT NULL,
    company_id INT UNSIGNED NOT NULL,
    order_id INT UNSIGNED NULL,
    provider_id INT UNSIGNED NULL,
    service_id INT UNSIGNED NULL,
    customer_id INT UNSIGNED NULL,
    rating TINYINT UNSIGNED NOT NULL DEFAULT 5,
    title VARCHAR(190) NULL,
    body TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'published',
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_mp_review_uuid (public_uuid),
    INDEX idx_mp_review_company (company_id, deleted_at),
    INDEX idx_mp_review_provider (provider_id),
    INDEX idx_mp_review_order (order_id),
    CONSTRAINT fk_mp_review_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rateb_mp_timeline (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    title VARCHAR(190) NOT NULL,
    body TEXT NULL,
    related_type VARCHAR(40) NULL,
    related_id INT UNSIGNED NULL,
    order_id INT UNSIGNED NULL,
    provider_id INT UNSIGNED NULL,
    service_id INT UNSIGNED NULL,
    customer_id INT UNSIGNED NULL,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_mp_timeline_company (company_id, created_at),
    INDEX idx_mp_timeline_order (order_id),
    CONSTRAINT fk_mp_timeline_tenant FOREIGN KEY (company_id) REFERENCES rateb_companies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
