<?php
declare(strict_types=1);

require_once __DIR__ . '/php/bootstrap.php';

$token = trim((string)($_GET['token'] ?? ''));
$share = coreai_load_public_share($token);
if ($share === null) {
    http_response_code(404);
}
$appUrl = 'index.php';
/**
 * Branding ensures that every shared improvement promotes CoreAI and drives new users back to the product.
 * إضافة الهوية البصرية تضمن أن كل نتيجة يتم مشاركتها تروّج لـ CoreAI وتجذب مستخدمين جدد.
 */
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CoreAI Shared Result</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <div class="ide-shell">
        <header class="topbar">
            <h1 class="brand">CoreAI Shared Result</h1>
            <div class="status"><?php echo $share ? htmlspecialchars((string)($share['owner_username'] ?? '')) : 'Not found'; ?></div>
        </header>
        <main class="workspace coreai-auth-workspace">
            <section class="editor-panel coreai-auth-panel">
                <div class="editor-header">
                    <span>Public Preview</span>
                </div>
                <div class="coreai-auth-content">
                    <?php if ($share === null): ?>
                        <p>Shared result not found.</p>
                    <?php else: ?>
                        <article class="share-result-card">
                            <div class="share-brand-row">
                                <div class="share-logo-mark">C</div>
                                <div>
                                    <h3 class="share-result-title">CoreAI</h3>
                                    <p class="action-meta">AI that improves your code</p>
                                </div>
                            </div>
                            <div class="share-footer-row">
                                <span class="share-watermark">Generated by CoreAI</span>
                                <a class="share-cta-link" href="<?php echo htmlspecialchars($appUrl); ?>">Try CoreAI</a>
                            </div>
                        </article>
                        <p class="action-meta"><strong>Read-only preview:</strong> execution is disabled on this page.</p>
                        <p><strong>Summary:</strong> <?php echo htmlspecialchars((string)($share['execution_summary'] ?? '')); ?></p>
                        <p><strong>AI Explanation:</strong> <?php echo htmlspecialchars((string)($share['ai_explanation'] ?? '')); ?></p>
                        <?php $card = is_array($share['share_card'] ?? null) ? $share['share_card'] : []; ?>
                        <article class="share-result-card">
                            <h3 class="share-result-title">Improvement Summary</h3>
                            <p class="share-key-summary"><strong>Before vs after:</strong> <?php echo htmlspecialchars((string)($card['diff_summary'] ?? '')); ?></p>
                            <p class="action-meta"><strong>Lines changed:</strong> <?php echo (int)($card['lines_changed'] ?? 0); ?></p>
                            <p class="share-gains"><strong>Performance/Stability:</strong> +<?php echo (int)($card['performance_gain'] ?? 0); ?>% / <?php $sg=(int)($card['stability_gain'] ?? 0); echo ($sg>=0?'+':'') . $sg; ?>%</p>
                        </article>
                        <h3>Before/After Diff</h3>
                        <?php foreach ((array)($share['diff_items'] ?? []) as $item): ?>
                            <?php if (!is_array($item)) { continue; } ?>
                            <article class="plan-group-card">
                                <div class="plan-group-head">
                                    <strong><?php echo htmlspecialchars((string)($item['target'] ?? 'file')); ?></strong>
                                    <span class="action-meta"><?php echo htmlspecialchars((string)($item['operation'] ?? 'modify')); ?></span>
                                </div>
                                <pre class="code-editor" style="height:auto;max-height:280px;"><?php echo htmlspecialchars((string)($item['diff'] ?? '')); ?></pre>
                            </article>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </section>
        </main>
    </div>
</body>
</html>
