<?php
declare(strict_types=1);

/**
 * One-time helper: create config/infra.secrets.php with RATIB_INFRA_SECRET_KEY if missing.
 * Run on server: php modules/infrastructure-marketplace/Cli/infra-ensure-secret-key.php
 */
require_once dirname(__DIR__) . '/bootstrap.php';

use Ratib\InfrastructureMarketplace\Infrastructure\InfraEnvBootstrap;

$root = dirname(__DIR__, 3);
$target = $root . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'infra.secrets.php';

if (is_readable($target)) {
    InfraEnvBootstrap::load();
    echo json_encode([
        'ok' => true,
        'message' => 'config/infra.secrets.php already exists',
        'has_key' => InfraEnvBootstrap::hasSecretKey(),
    ], JSON_UNESCAPED_SLASHES) . PHP_EOL;
    exit(0);
}

$key = bin2hex(random_bytes(32));
$contents = "<?php\n"
    . "declare(strict_types=1);\n\n"
    . "/** Auto-generated by infra-ensure-secret-key.php — do not commit. */\n"
    . "return [\n"
    . "    'RATIB_INFRA_SECRET_KEY' => '" . $key . "',\n"
    . "];\n";

$dir = dirname($target);
if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
    fwrite(STDERR, "Cannot create config directory\n");
    exit(1);
}

if (@file_put_contents($target, $contents, LOCK_EX) === false) {
    fwrite(STDERR, "Cannot write config/infra.secrets.php\n");
    exit(1);
}
@chmod($target, 0600);

InfraEnvBootstrap::load();
echo json_encode([
    'ok' => true,
    'message' => 'Created config/infra.secrets.php',
    'path' => $target,
    'has_key' => InfraEnvBootstrap::hasSecretKey(),
], JSON_UNESCAPED_SLASHES) . PHP_EOL;
