/**
 * Public home page: registration panel, plan/year UI, payment summary.
 * Config from #ratib-home-bootstrap (JSON) set in home.php.
 * EN: Handles user interactions only; business/pricing values are injected from PHP bootstrap JSON.
 * AR: هذا الملف يدير تفاعلات الواجهة فقط؛ قيم التسعير والمنطق الأساسية يتم تمريرها من PHP عبر JSON.
 */
(function () {
    'use strict';

    // EN: Parse bootstrap JSON generated by PHP and normalize defaults.
    // AR: قراءة JSON القادم من PHP وتوحيد القيم الافتراضية.
    function parseBootstrap() {
        var d = {
            checkoutCurrency: 'SAR',
            displayCheckoutCurrency: 'SAR',
            displayNgeniusLabel: 'N-Genius KSA',
            displayUsdRate: 3.75,
            usdToSar: 3.75,
            openRegister: false,
            initialPlan: 'pro',
            initialAmount: null,
            initialYears: 1,
            goldMonth: 4.5,
            goldYear1: 5,
            platinumMonth: 67,
            platinumYear1: 800
        };
        var el = document.getElementById('ratib-home-bootstrap');
        if (!el || !el.textContent) {
            return d;
        }
        try {
            var o = JSON.parse(el.textContent);
            if (o && typeof o === 'object') {
                if (typeof o.checkoutCurrency === 'string') {
                    d.checkoutCurrency = o.checkoutCurrency;
                }
                if (typeof o.usdToSar === 'number' && isFinite(o.usdToSar) && o.usdToSar > 0) {
                    d.usdToSar = o.usdToSar;
                }
                if (typeof o.displayCheckoutCurrency === 'string' && o.displayCheckoutCurrency.trim() !== '') {
                    d.displayCheckoutCurrency = o.displayCheckoutCurrency.trim().toUpperCase();
                }
                if (typeof o.displayNgeniusLabel === 'string' && o.displayNgeniusLabel.trim() !== '') {
                    d.displayNgeniusLabel = o.displayNgeniusLabel.trim();
                }
                if (typeof o.displayUsdRate === 'number' && isFinite(o.displayUsdRate) && o.displayUsdRate > 0) {
                    d.displayUsdRate = o.displayUsdRate;
                }
                if (typeof o.openRegister === 'boolean') {
                    d.openRegister = o.openRegister;
                }
                if (typeof o.initialPlan === 'string') {
                    d.initialPlan = o.initialPlan;
                }
                if (o.initialAmount === null || typeof o.initialAmount === 'number') {
                    d.initialAmount = o.initialAmount;
                }
                if (typeof o.initialYears === 'number') {
                    d.initialYears = o.initialYears;
                }
                if (typeof o.goldMonth === 'number') {
                    d.goldMonth = o.goldMonth;
                }
                if (typeof o.goldYear1 === 'number') {
                    d.goldYear1 = o.goldYear1;
                }
                if (typeof o.platinumMonth === 'number') {
                    d.platinumMonth = o.platinumMonth;
                }
                if (typeof o.platinumYear1 === 'number') {
                    d.platinumYear1 = o.platinumYear1;
                }
            }
        } catch (err) {
            console.error('ratib-home-bootstrap parse error', err);
        }
        return d;
    }

    var HOME = parseBootstrap();
    // EN: Monthly = 0, annual = 1 only; coerce legacy bootstrap values (e.g. years=2 from old URLs already fixed in PHP).
    if (HOME.initialYears > 1) {
        HOME.initialYears = 1;
    }
    window.RATIB_CHECKOUT_CURRENCY = HOME.checkoutCurrency;
    window.RATIB_DISPLAY_CHECKOUT_CURRENCY = HOME.displayCheckoutCurrency;
    window.RATIB_DISPLAY_NGENIUS_LABEL = HOME.displayNgeniusLabel;
    window.RATIB_DISPLAY_USD_RATE = HOME.displayUsdRate;
    window.RATIB_USD_TO_SAR = HOME.usdToSar;
    var openRegister = HOME.openRegister;
    var DISPLAY_MULTIPLIER = 2;
    function formatPayableAmount(value) {
        var n = Number(value);
        if (!isFinite(n) || n <= 0) {
            return '0';
        }
        if (Math.abs(n - Math.round(n)) < 0.0001) {
            return Math.round(n).toLocaleString();
        }
        return n.toFixed(2);
    }
    function formatDisplayAmount(value) {
        var n = Number(value);
        if (!isFinite(n) || n <= 0) {
            return '0';
        }
        return (Math.round(n * DISPLAY_MULTIPLIER)).toLocaleString();
    }
    function formatPromoInline(payable) {
        return '<span class="promo-old">$' + formatDisplayAmount(payable) + '</span> <span class="promo-new">$' + formatPayableAmount(payable) + '</span>';
    }
    // EN: Remove any legacy 2-year buttons if stale markup is served.
    // AR: إزالة أي أزرار مدة قديمة (سنتان) إذا تم تحميل HTML قديم.
    document.querySelectorAll('[data-years]').forEach(function (btn) {
        var yLegacy = parseInt(btn.getAttribute('data-years'), 10);
        if (isFinite(yLegacy) && yLegacy > 1 && btn.parentNode) {
            btn.parentNode.removeChild(btn);
        }
    });

    // EN: Opens registration section and synchronizes hidden pricing fields.
    // AR: فتح قسم التسجيل وتحديث حقول الخطة/السعر المخفية.
    function showRegistrationForm(plan, amount, years) {
        var registerSection = document.getElementById('register');
        if (registerSection) {
            var successMsg = document.getElementById('successMsg');
            var successText = document.getElementById('successText');
            var phpSuccessMsg = document.getElementById('phpSuccessMsg');
            var form = document.getElementById('regForm');

            if (successMsg) {
                successMsg.style.display = 'none';
            }
            if (successText) {
                successText.innerHTML = '';
            }
            if (phpSuccessMsg) {
                phpSuccessMsg.style.display = 'none';
            }

            if (form) {
                form.style.display = 'block';
            }

            if (form) {
                form.reset();
            }

            if (window.history && window.history.replaceState) {
                var url = new URL(window.location.href);
                window.history.replaceState({}, '', url.toString());
            }

            registerSection.style.display = 'flex';
            var inputPlan = document.getElementById('inputPlan');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');
            var paymentBlockWrap = document.getElementById('paymentBlockWrap');
            var btnSubmit = document.getElementById('btnSubmit');
            if (inputPlan) {
                inputPlan.value = plan;
            }
            if (inputPlanAmount) {
                inputPlanAmount.value = amount || '';
            }
            if (inputYears) {
                var yShow = parseInt(years, 10);
                if (!isFinite(yShow) || yShow < 0) {
                    yShow = 1;
                }
                inputYears.value = String(yShow);
            }
            amount = parseFloat(amount) || 0;
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }
            if (paymentBlockWrap) {
                paymentBlockWrap.style.display = amount > 0 ? 'block' : 'none';
            }
            if (btnSubmit) {
                btnSubmit.style.display = 'block';
            }
            if (amount > 0 && typeof updatePaymentSummary === 'function') {
                updatePaymentSummary(amount, years, plan);
            }
            registerSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }
    window.showRegistrationForm = showRegistrationForm;

    // EN: Debounce-like guard to avoid duplicate summary DOM writes.
    // AR: آلية حماية لتقليل التحديثات المتكررة في ملخص الدفع.
    var lastPaymentSummaryUpdate = { subtotal: 0, years: 0, planKey: '', timestamp: 0 };

    // EN: Render pricing summary block (subtotal, tax, total, currency note).
    // AR: إنشاء وعرض ملخص الدفع (المبلغ، الضريبة، الإجمالي، وملاحظة العملة).
    function updatePaymentSummary(subtotal, years, planKeyOpt) {
        var summaryEl = document.querySelector('.payment-summary-box') ||
            document.querySelector('#paymentBlockWrap .payment-summary-box') ||
            document.querySelector('.register-section .form-card .payment-summary-box') ||
            document.querySelector('#paymentSummary');

        if (!summaryEl) {
            console.log('ERROR: Payment summary element not found! subtotal:', subtotal);
            console.log('Tried selectors: .payment-summary-box, #paymentBlockWrap .payment-summary-box');
            return;
        }

        years = parseInt(years, 10);
        if (!isFinite(years) || years < 0) {
            years = 1;
        }
        var inputPlanEl = document.getElementById('inputPlan');
        var planValue = (planKeyOpt != null && String(planKeyOpt).trim() !== '')
            ? String(planKeyOpt).trim().toLowerCase()
            : (inputPlanEl ? (inputPlanEl.value || inputPlanEl.getAttribute('value') || '').trim().toLowerCase() : '');

        var planLabel = 'Gold';
        if (planValue === 'platinum') {
            planLabel = 'Platinum';
        } else if (planValue === 'pro') {
            planLabel = 'Pro';
        } else if (planValue === 'gold') {
            planLabel = 'Gold';
        } else {
            var activeGoldBtn = document.querySelector('.plan-btn-form[data-plan="gold"]');
            var activePlatinumBtn = document.querySelector('.plan-btn-form[data-plan="platinum"]');
            var goldStyle = activeGoldBtn ? (activeGoldBtn.getAttribute('style') || '') : '';
            var platinumStyle = activePlatinumBtn ? (activePlatinumBtn.getAttribute('style') || '') : '';
            var goldActive = goldStyle.indexOf('rgba(212,175,55') !== -1 || goldStyle.indexOf('#d4af37') !== -1;
            var platinumActive = platinumStyle.indexOf('rgba(241,196,15') !== -1 || platinumStyle.indexOf('#f1c40f') !== -1;
            if (platinumActive && !goldActive) {
                planLabel = 'Platinum';
            } else if (goldActive && !platinumActive) {
                planLabel = 'Gold';
            }
        }

        var now = Date.now();
        if (lastPaymentSummaryUpdate.subtotal === subtotal && lastPaymentSummaryUpdate.years === years &&
            lastPaymentSummaryUpdate.planKey === planValue && (now - lastPaymentSummaryUpdate.timestamp) < 100) {
            console.log('Skipping duplicate updatePaymentSummary call for subtotal:', subtotal);
            return;
        }
        lastPaymentSummaryUpdate = { subtotal: subtotal, years: years, planKey: planValue, timestamp: now };

        var tax = subtotal * 0.15;
        var total = subtotal + tax;
        var displayCur = (typeof window.RATIB_DISPLAY_CHECKOUT_CURRENCY === 'string' && window.RATIB_DISPLAY_CHECKOUT_CURRENCY)
            ? String(window.RATIB_DISPLAY_CHECKOUT_CURRENCY).toUpperCase() : 'SAR';
        var gatewayCur = (typeof window.RATIB_CHECKOUT_CURRENCY === 'string' && window.RATIB_CHECKOUT_CURRENCY)
            ? String(window.RATIB_CHECKOUT_CURRENCY).toUpperCase() : 'SAR';
        if (gatewayCur !== 'SAR' && gatewayCur !== 'USD') {
            gatewayCur = 'SAR';
        }
        var usdToDisplay = (typeof window.RATIB_DISPLAY_USD_RATE === 'number' && isFinite(window.RATIB_DISPLAY_USD_RATE) && window.RATIB_DISPLAY_USD_RATE > 0)
            ? window.RATIB_DISPLAY_USD_RATE : 3.75;
        var usdToGateway = (typeof window.RATIB_USD_TO_SAR === 'number' && isFinite(window.RATIB_USD_TO_SAR) && window.RATIB_USD_TO_SAR > 0)
            ? window.RATIB_USD_TO_SAR : 3.75;
        if (gatewayCur === 'USD') {
            usdToGateway = 1.0;
        }
        var fallbackUsdRates = {
            USD: 1.00,
            SAR: 3.75,
            BDT: 117.50,
            IDR: 16000.00,
            ETB: 57.00,
            PHP: 57.00,
            KES: 129.00,
            UGX: 3800.00,
            NGN: 1450.00,
            RWF: 1300.00,
            LKR: 300.00,
            NPR: 133.00,
            THB: 36.00
        };
        // Guard against stale bootstrap payloads that still send 3.75 for non-SAR currencies.
        if ((!isFinite(usdToDisplay) || usdToDisplay <= 0 || (displayCur !== 'SAR' && Math.abs(usdToDisplay - 3.75) < 0.000001))
            && Object.prototype.hasOwnProperty.call(fallbackUsdRates, displayCur)) {
            usdToDisplay = fallbackUsdRates[displayCur];
        }
        var ngeniusNote = '';
        var gatewayApprox = (total * usdToGateway).toFixed(2);
        var gatewayRateStr = usdToGateway.toFixed(2);
        var displayApprox = (total * usdToDisplay).toFixed(2);
        var displayRateStr = usdToDisplay.toFixed(2);
        ngeniusNote = '<p class="small mb-0 mt-2 ratib-ngenius-currency-note">Card checkout is charged in <strong>' + displayCur + '</strong>: <strong class="ratib-ngenius-sar-total">' + displayCur + ' ' + displayApprox + '</strong> <span class="ratib-ngenius-rate-note">(USD × ' + displayRateStr + ')</span>.</p>';
        if (displayCur !== gatewayCur) {
            ngeniusNote += '<p class="small text-muted mb-0 mt-1 ratib-ngenius-currency-note">You will complete payment in ' + gatewayCur + '.</p>';
        }

        console.log('updatePaymentSummary - subtotal:', subtotal, 'years:', years, 'planLabel:', planLabel, 'inputPlan.value:', inputPlanEl ? inputPlanEl.value : '');

        var durationLabel = years === 0
            ? 'monthly'
            : (years + ' year' + (years > 1 ? 's' : ''));
        var listPrice = subtotal * DISPLAY_MULTIPLIER;
        var discountAmount = listPrice - subtotal;
        summaryEl.innerHTML = '<h4 class="payment-summary-title"><i class="fas fa-receipt me-2"></i>Payment Summary</h4>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">List Price</span>' +
            '<span class="payment-summary-value">$' + listPrice.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">Discount (50%)</span>' +
            '<span class="payment-summary-value payment-summary-discount">-$' + discountAmount.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">' + planLabel + ' Plan (' + durationLabel + ')</span>' +
            '<span class="payment-summary-value">$' + subtotal.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">Tax (15%)</span>' +
            '<span class="payment-summary-value">$' + tax.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-total-row">' +
            '<span>Total</span>' +
            '<span>' + displayCur + ' ' + displayApprox + '</span>' +
            '</div>' + ngeniusNote;
    }

    // EN: Form state manager for plan/year buttons and hidden inputs.
    // AR: إدارة حالة النموذج وربط أزرار الخطة/المدة بالحقول المخفية.
    (function () {
        var form = document.getElementById('regForm');
        if (!form) {
            return;
        }
        var desiredSiteUrlInput = form.querySelector('input[name="desired_site_url"]');
        if (desiredSiteUrlInput) {
            desiredSiteUrlInput.removeAttribute('required');
            var desiredLabel = desiredSiteUrlInput.closest('.mb-3');
            if (desiredLabel) {
                var labelEl = desiredLabel.querySelector('.form-label');
                if (labelEl) {
                    labelEl.textContent = 'Desired Site URL (optional)';
                }
            }
        }

        document.getElementById('countrySelect').addEventListener('change', function () {
            var wrap = document.getElementById('otherCountryWrap');
            wrap.style.display = (this.value === 'Other countries sending workers') ? 'block' : 'none';
            if (wrap.style.display === 'none') {
                document.getElementById('countryOther').value = '';
            }
        });
        var inputPlan = document.getElementById('inputPlan');
        var inputPlanAmount = document.getElementById('inputPlanAmount');
        var inputYears = document.getElementById('inputYears');
        var paymentBlockWrap = document.getElementById('paymentBlockWrap');
        var btnSubmit = document.getElementById('btnSubmit');
        var formYearButtonsWrap = document.getElementById('formYearButtonsWrap');
        // Keep duration choices limited to supported tiers only (monthly and 1 year).
        var legacyYearButtons = document.querySelectorAll('.form-year-btn[data-years]:not([data-years="0"]):not([data-years="1"])');
        legacyYearButtons.forEach(function (btn) {
            if (btn && btn.parentNode) {
                btn.parentNode.removeChild(btn);
            }
        });
        var formYearButtons = document.querySelectorAll('.form-year-btn');
        var planBtns = document.querySelectorAll('.plan-btn-form');
        var activePlanStyle = {
            gold: 'border-color: rgba(212,175,55,0.8); background: rgba(212,175,55,0.2); color: #d4af37;',
            platinum: 'border-color: rgba(241,196,15,0.8); background: rgba(241,196,15,0.2); color: #f1c40f;',
            pro: 'border-color: rgba(93,173,226,0.6); background: rgba(93,173,226,0.15); color: #5dade2;'
        };
        var inactiveStyle = 'border: 2px solid rgba(255,255,255,0.3); background: rgba(255,255,255,0.05); color: #aaa;';
        function setFormPlan(planVal, amount, years) {
            planVal = planVal || '';
            if (inputPlan) {
                inputPlan.value = planVal;
                inputPlan.setAttribute('value', planVal);
            }
            if (inputPlanAmount) {
                inputPlanAmount.value = amount || '';
                inputPlanAmount.setAttribute('value', amount || '');
            }
            if (inputYears) {
                var yIn = parseInt(years, 10);
                if (!isFinite(yIn) || yIn < 0) {
                    yIn = 1;
                }
                inputYears.value = String(yIn);
                inputYears.setAttribute('value', String(yIn));
            }
            amount = parseFloat(amount) || 0;
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }

            console.log('setFormPlan called - planVal:', planVal, 'amount:', amount, 'years:', years);

            if (formYearButtonsWrap) {
                formYearButtonsWrap.style.display = (planVal === 'gold' || planVal === 'platinum') ? 'block' : 'none';
            }
            if (paymentBlockWrap) {
                paymentBlockWrap.style.display = amount > 0 ? 'block' : 'none';
                console.log('paymentBlockWrap display set to:', amount > 0 ? 'block' : 'none', 'for amount:', amount);
            }
            var placeholder = document.getElementById('paymentBlockPlaceholder');
            if (placeholder) {
                placeholder.style.display = amount > 0 ? 'none' : 'block';
            }
            if (btnSubmit) {
                btnSubmit.style.display = 'block';
            }
            planBtns.forEach(function (b) {
                var p = b.getAttribute('data-plan');
                b.setAttribute('style', (p === planVal ? (activePlanStyle[p] || inactiveStyle) : inactiveStyle) + ' padding: 0.5rem 1rem; border-radius: 8px; font-weight: 600; cursor: pointer; transition: all 0.2s;');
            });
            if (planVal === 'gold' || planVal === 'platinum') {
                if (inputPlan && inputPlan.value !== planVal) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                formYearButtons.forEach(function (b) {
                    var y = parseInt(b.getAttribute('data-years'), 10);
                    if (isNaN(y) || y < 0) {
                        y = 1;
                    }
                    var price = planVal === 'gold' ? parseFloat(b.getAttribute('data-price-gold')) : parseFloat(b.getAttribute('data-price-platinum'));
                    var span = b.querySelector('.form-year-price');
                    if (span) {
                        span.innerHTML = formatPromoInline(price);
                    }
                    var isActive = (y === years);
                    if (planVal === 'gold') {
                        b.style.border = isActive ? '2px solid rgba(212,175,55,0.8)' : '2px solid rgba(255,255,255,0.2)';
                        b.style.background = isActive ? 'rgba(212,175,55,0.2)' : 'rgba(255,255,255,0.05)';
                        b.style.color = isActive ? '#d4af37' : '#aaa';
                    } else {
                        b.style.border = isActive ? '2px solid rgba(241,196,15,0.8)' : '2px solid rgba(255,255,255,0.2)';
                        b.style.background = isActive ? 'rgba(241,196,15,0.2)' : 'rgba(255,255,255,0.05)';
                        b.style.color = isActive ? '#f1c40f' : '#aaa';
                    }
                });
            }
            if (amount > 0 && typeof updatePaymentSummary === 'function') {
                if (inputPlan) {
                    inputPlan.value = planVal || 'gold';
                    inputPlan.setAttribute('value', planVal || 'gold');
                }
                if (paymentBlockWrap) {
                    paymentBlockWrap.style.display = 'block';
                }
                console.log('Calling updatePaymentSummary with amount:', amount, 'planVal:', planVal);
                updatePaymentSummary(amount, years, planVal);
            } else {
                console.log('NOT calling updatePaymentSummary - amount:', amount, 'function exists:', typeof updatePaymentSummary === 'function');
            }
        }
        var initialPlan = HOME.initialPlan;
        var initialAmount = HOME.initialAmount;
        var initialYears = HOME.initialYears;
        var defaultAmount = null;
        if (initialPlan === 'gold') {
            defaultAmount = initialYears === 0 ? HOME.goldMonth : HOME.goldYear1;
        } else if (initialPlan === 'platinum') {
            defaultAmount = initialYears === 0 ? HOME.platinumMonth : HOME.platinumYear1;
        }
        if (inputPlan && initialPlan) {
            inputPlan.value = initialPlan;
            inputPlan.setAttribute('value', initialPlan);
        }
        setFormPlan(initialPlan, initialAmount !== null ? initialAmount : defaultAmount, initialYears);
        if (openRegister) {
            var rs = document.getElementById('register');
            if (rs) {
                rs.style.display = 'flex';
                rs.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        }
        planBtns.forEach(function (b) {
            b.addEventListener('click', function () {
                var planVal = this.getAttribute('data-plan');
                var amt = this.getAttribute('data-amount');
                var y = parseInt(this.getAttribute('data-years'), 10) || 1;

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                if (planVal === 'gold' || planVal === 'platinum') {
                    amt = parseFloat(amt) || 0;

                    if (!amt || amt === 0) {
                        var firstYearBtn = document.querySelector('.form-year-btn[data-years="1"]');
                        if (firstYearBtn) {
                            var price = planVal === 'gold' ? parseFloat(firstYearBtn.getAttribute('data-price-gold')) : parseFloat(firstYearBtn.getAttribute('data-price-platinum'));
                            amt = price || (planVal === 'gold' ? HOME.goldYear1 : HOME.platinumYear1);
                        } else {
                            amt = planVal === 'gold' ? HOME.goldYear1 : HOME.platinumYear1;
                        }
                    }
                    y = 1;
                }

                console.log('Plan button clicked - planVal:', planVal, 'amt:', amt, 'y:', y);

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                    inputPlan.dispatchEvent(new Event('change', { bubbles: true }));
                }

                setFormPlan(planVal, amt, y);
            });
        });
        formYearButtons.forEach(function (b) {
            b.addEventListener('click', function () {
                var planVal = inputPlan ? (inputPlan.value || 'gold') : 'gold';
                planVal = planVal.trim().toLowerCase();

                if (planVal !== 'gold' && planVal !== 'platinum') {
                    var activeGoldBtn = document.querySelector('.plan-btn-form[data-plan="gold"]');
                    var activePlatinumBtn = document.querySelector('.plan-btn-form[data-plan="platinum"]');
                    var goldStyle = activeGoldBtn ? (activeGoldBtn.getAttribute('style') || '') : '';
                    var platinumStyle = activePlatinumBtn ? (activePlatinumBtn.getAttribute('style') || '') : '';

                    if (goldStyle.indexOf('rgba(212,175,55') !== -1 || goldStyle.indexOf('#d4af37') !== -1) {
                        planVal = 'gold';
                    } else if (platinumStyle.indexOf('rgba(241,196,15') !== -1 || platinumStyle.indexOf('#f1c40f') !== -1) {
                        planVal = 'platinum';
                    }
                }

                var yDur = parseInt(this.getAttribute('data-years'), 10);
                if (isNaN(yDur) || yDur < 0) {
                    yDur = 1;
                }
                var price = planVal === 'gold' ? parseFloat(this.getAttribute('data-price-gold')) : parseFloat(this.getAttribute('data-price-platinum'));

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                setFormPlan(planVal, price, yDur);
            });
        });
    })();

    // EN: Price card interactions (top pricing cards) and year toggles.
    // AR: تفاعلات بطاقات الأسعار العلوية وتبديل مدة الاشتراك.
    (function () {
        var goldPrices = { 0: HOME.goldMonth, 1: HOME.goldYear1 };
        var platinumPrices = { 0: HOME.platinumMonth, 1: HOME.platinumYear1 };

        function updateGoldPrice(years, event) {
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }
            var price = goldPrices.hasOwnProperty(years) ? goldPrices[years] : HOME.goldYear1;
            var oldPrice = price * 2;
            var priceEl = document.getElementById('goldPrice');
            var oldPriceEl = document.getElementById('goldOldPrice');
            var btn = document.getElementById('goldRegisterBtn');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');

            if (priceEl) {
                var goldLbl = years === 0 ? 'per month' : ('for ' + years + ' year' + (years > 1 ? 's' : ''));
                priceEl.innerHTML = '$' + price.toLocaleString() + ' <span id="goldPriceLabel">' + goldLbl + '</span>';
            }
            if (oldPriceEl) {
                oldPriceEl.textContent = '$' + oldPrice.toLocaleString();
            }
            if (btn) {
                btn.setAttribute('data-register-plan', 'gold');
                btn.setAttribute('data-register-amount', String(price));
                btn.setAttribute('data-register-years', String(years));
            }

            if (event && event.type === 'click') {
                if (inputPlanAmount) {
                    inputPlanAmount.value = price;
                }
                if (inputYears) {
                    inputYears.value = String(years);
                }
                var inputPlanEl = document.getElementById('inputPlan');
                if (inputPlanEl) {
                    inputPlanEl.value = 'gold';
                    inputPlanEl.setAttribute('value', 'gold');
                }
                var registerSection = document.getElementById('register');
                if (registerSection && registerSection.style.display !== 'none') {
                    setTimeout(function () {
                        updatePaymentSummary(price, years, 'gold');
                    }, 10);
                }
            }

            document.querySelectorAll('.gold-year-btn').forEach(function (b) {
                var btnYears = parseInt(b.getAttribute('data-years'), 10) || 0;
                if (btnYears === years) {
                    b.classList.add('active');
                    b.style.background = 'rgba(212,175,55,0.2)';
                    b.style.borderColor = '#d4af37';
                    b.style.color = '#d4af37';
                } else {
                    b.classList.remove('active');
                    b.style.background = 'rgba(255,255,255,0.05)';
                    b.style.borderColor = 'rgba(255,255,255,0.2)';
                    b.style.color = '#aaa';
                }
            });
        }

        function updatePlatinumPrice(years, event) {
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }
            var price = platinumPrices.hasOwnProperty(years) ? platinumPrices[years] : HOME.platinumYear1;
            var oldPrice = price * 2;
            var priceEl = document.getElementById('platinumPrice');
            var oldPriceEl = document.getElementById('platinumOldPrice');
            var btn = document.getElementById('platinumRegisterBtn');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');

            if (priceEl) {
                var platLbl = years === 0 ? 'per month' : ('for ' + years + ' year' + (years > 1 ? 's' : ''));
                priceEl.innerHTML = '$' + price.toLocaleString() + ' <span id="platinumPriceLabel">' + platLbl + '</span>';
            }
            if (oldPriceEl) {
                oldPriceEl.textContent = '$' + oldPrice.toLocaleString();
            }
            if (btn) {
                btn.setAttribute('data-register-plan', 'platinum');
                btn.setAttribute('data-register-amount', String(price));
                btn.setAttribute('data-register-years', String(years));
            }

            if (event && event.type === 'click') {
                if (inputPlanAmount) {
                    inputPlanAmount.value = price;
                }
                if (inputYears) {
                    inputYears.value = String(years);
                }
                var inputPlanEl = document.getElementById('inputPlan');
                if (inputPlanEl) {
                    inputPlanEl.value = 'platinum';
                    inputPlanEl.setAttribute('value', 'platinum');
                }
                var registerSection = document.getElementById('register');
                if (registerSection && registerSection.style.display !== 'none' && typeof updatePaymentSummary === 'function') {
                    setTimeout(function () {
                        updatePaymentSummary(price, years, 'platinum');
                    }, 10);
                }
            }

            document.querySelectorAll('.platinum-year-btn').forEach(function (b) {
                var btnYears = parseInt(b.getAttribute('data-years'), 10) || 0;
                if (btnYears === years) {
                    b.classList.add('active');
                    b.style.background = 'rgba(241,196,15,0.2)';
                    b.style.borderColor = '#f1c40f';
                    b.style.color = '#f1c40f';
                } else {
                    b.classList.remove('active');
                    b.style.background = 'rgba(255,255,255,0.05)';
                    b.style.borderColor = 'rgba(255,255,255,0.2)';
                    b.style.color = '#aaa';
                }
            });
        }

        document.querySelectorAll('.gold-year-btn').forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                var y = parseInt(this.getAttribute('data-years'), 10);
                if (isNaN(y) || y < 0) {
                    y = 1;
                } else if (y > 1) {
                    y = 1;
                }
                updateGoldPrice(y, e);
            });
        });

        document.querySelectorAll('.platinum-year-btn').forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                var y = parseInt(this.getAttribute('data-years'), 10);
                if (isNaN(y) || y < 0) {
                    y = 1;
                } else if (y > 1) {
                    y = 1;
                }
                updatePlatinumPrice(y, e);
            });
        });

        (function syncPricingCardsFromBootstrap() {
            var iy = parseInt(HOME.initialYears, 10);
            if (isNaN(iy) || iy < 0) {
                iy = 1;
            }
            if (HOME.initialPlan === 'gold' && (iy === 0 || iy === 1)) {
                updateGoldPrice(iy, null);
            } else if (HOME.initialPlan === 'platinum' && (iy === 0 || iy === 1)) {
                updatePlatinumPrice(iy, null);
            }
        })();
    })();

    // EN: Delegated click handlers for register anchors.
    // AR: معالجات نقر عامة لروابط التسجيل.
    document.addEventListener('click', function (e) {
        var scrollA = e.target.closest('a.js-scroll-register');
        if (scrollA && scrollA.getAttribute('href') === '#register') {
            e.preventDefault();
            var registerSection = document.getElementById('register');
            if (registerSection) {
                registerSection.style.display = 'flex';
                registerSection.scrollIntoView({ behavior: 'smooth' });
            }
            return;
        }
        var openA = e.target.closest('a.js-open-register');
        if (openA) {
            e.preventDefault();
            var plan = openA.getAttribute('data-register-plan') || 'gold';
            var amount = parseFloat(openA.getAttribute('data-register-amount') || '0') || 0;
            var yrs = parseInt(openA.getAttribute('data-register-years') || '1', 10);
            if (isNaN(yrs) || yrs < 0) {
                yrs = 1;
            }
            showRegistrationForm(plan, amount, yrs);
        }
    });
})();

(function ratibHomeNavChrome() {
    var header = document.getElementById('ratib-main-header');
    var toggle = document.getElementById('ratibNavToggle');
    var menu = document.getElementById('ratibNavMenu');
    if (!header) {
        return;
    }
    function onScroll() {
        header.classList.toggle('is-scrolled', window.scrollY > 32);
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
    if (toggle && menu) {
        toggle.addEventListener('click', function () {
            var open = menu.classList.toggle('is-open');
            toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
        });
        menu.querySelectorAll('a').forEach(function (a) {
            a.addEventListener('click', function () {
                menu.classList.remove('is-open');
                toggle.setAttribute('aria-expanded', 'false');
            });
        });
    }
})();

/** Phase 2: subtle scroll reveal — adds classes only; no DOM/markup changes. */
(function ratibHomeScrollReveal() {
    if (!window.IntersectionObserver) {
        return;
    }
    var reduce =
        window.matchMedia &&
        window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduce) {
        return;
    }
    var main = document.querySelector('.ratib-main');
    if (!main) {
        return;
    }
    var sel =
        '.ratib-hero, .ratib-section, .pricing-section.ratib-pricing-saas, .video-section.ratib-video, .ratib-final-cta';
    var els = main.querySelectorAll(sel);
    if (!els.length) {
        return;
    }
    var html = document.documentElement;
    els.forEach(function (el) {
        el.classList.add('ratib-reveal');
        var r = el.getBoundingClientRect();
        var vh = window.innerHeight || document.documentElement.clientHeight;
        if (r.top < vh * 0.92 && r.bottom > -40) {
            el.classList.add('ratib-reveal-visible');
        }
    });
    html.classList.add('ratib-reveal-init');
    html.classList.add('ratib-reveal-ready');
    var io = new IntersectionObserver(
        function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    entry.target.classList.add('ratib-reveal-visible');
                    io.unobserve(entry.target);
                }
            });
        },
        { rootMargin: '0px 0px -6% 0px', threshold: 0.06 }
    );
    els.forEach(function (el) {
        if (!el.classList.contains('ratib-reveal-visible')) {
            io.observe(el);
        }
    });
})();


