/**
 * Public home page: registration panel, plan/year UI, payment summary.
 * Config from #ratib-home-bootstrap (JSON) set in home.php.
 * EN: Handles user interactions only; business/pricing values are injected from PHP bootstrap JSON.
 * AR: هذا الملف يدير تفاعلات الواجهة فقط؛ قيم التسعير والمنطق الأساسية يتم تمريرها من PHP عبر JSON.
 */
(function () {
    'use strict';

    var ratibIsAboutPage = document.body && document.body.getAttribute('data-ratib-about') === '1';
    if (ratibIsAboutPage) {
        return;
    }

    // EN: Parse bootstrap JSON generated by PHP and normalize defaults.
    // AR: قراءة JSON القادم من PHP وتوحيد القيم الافتراضية.
    function parseBootstrap() {
        var d = {
            checkoutCurrency: 'SAR',
            displayCheckoutCurrency: 'SAR',
            displayNgeniusLabel: 'N-Genius KSA',
            displayUsdRate: 3.75,
            usdToSar: 3.75,
            openRegister: false,
            initialPlan: 'pro',
            initialAmount: null,
            initialYears: 1,
            goldMonth: 4.5,
            goldYear1: 5,
            platinumMonth: 67,
            platinumYear1: 800
        };
        var el = document.getElementById('ratib-home-bootstrap');
        if (!el || !el.textContent) {
            return d;
        }
        try {
            var o = JSON.parse(el.textContent);
            if (o && typeof o === 'object') {
                if (typeof o.checkoutCurrency === 'string') {
                    d.checkoutCurrency = o.checkoutCurrency;
                }
                if (typeof o.usdToSar === 'number' && isFinite(o.usdToSar) && o.usdToSar > 0) {
                    d.usdToSar = o.usdToSar;
                }
                if (typeof o.displayCheckoutCurrency === 'string' && o.displayCheckoutCurrency.trim() !== '') {
                    d.displayCheckoutCurrency = o.displayCheckoutCurrency.trim().toUpperCase();
                }
                if (typeof o.displayNgeniusLabel === 'string' && o.displayNgeniusLabel.trim() !== '') {
                    d.displayNgeniusLabel = o.displayNgeniusLabel.trim();
                }
                if (typeof o.displayUsdRate === 'number' && isFinite(o.displayUsdRate) && o.displayUsdRate > 0) {
                    d.displayUsdRate = o.displayUsdRate;
                }
                if (typeof o.openRegister === 'boolean') {
                    d.openRegister = o.openRegister;
                }
                if (typeof o.initialPlan === 'string') {
                    d.initialPlan = o.initialPlan;
                }
                if (o.initialAmount === null || typeof o.initialAmount === 'number') {
                    d.initialAmount = o.initialAmount;
                }
                if (typeof o.initialYears === 'number') {
                    d.initialYears = o.initialYears;
                }
                if (typeof o.goldMonth === 'number') {
                    d.goldMonth = o.goldMonth;
                }
                if (typeof o.goldYear1 === 'number') {
                    d.goldYear1 = o.goldYear1;
                }
                if (typeof o.platinumMonth === 'number') {
                    d.platinumMonth = o.platinumMonth;
                }
                if (typeof o.platinumYear1 === 'number') {
                    d.platinumYear1 = o.platinumYear1;
                }
            }
        } catch (err) {
            console.error('ratib-home-bootstrap parse error', err);
        }
        return d;
    }

    var HOME = parseBootstrap();
    // EN: Monthly = 0, annual = 1 only; coerce legacy bootstrap values (e.g. years=2 from old URLs already fixed in PHP).
    if (HOME.initialYears > 1) {
        HOME.initialYears = 1;
    }
    window.RATIB_CHECKOUT_CURRENCY = HOME.checkoutCurrency;
    window.RATIB_DISPLAY_CHECKOUT_CURRENCY = HOME.displayCheckoutCurrency;
    window.RATIB_DISPLAY_NGENIUS_LABEL = HOME.displayNgeniusLabel;
    window.RATIB_DISPLAY_USD_RATE = HOME.displayUsdRate;
    window.RATIB_USD_TO_SAR = HOME.usdToSar;
    var openRegister = HOME.openRegister;
    var DISPLAY_MULTIPLIER = 2;
    function formatPayableAmount(value) {
        var n = Number(value);
        if (!isFinite(n) || n <= 0) {
            return '0';
        }
        if (Math.abs(n - Math.round(n)) < 0.0001) {
            return Math.round(n).toLocaleString();
        }
        return n.toFixed(2);
    }
    function formatDisplayAmount(value) {
        var n = Number(value);
        if (!isFinite(n) || n <= 0) {
            return '0';
        }
        return (Math.round(n * DISPLAY_MULTIPLIER)).toLocaleString();
    }
    function formatPromoInline(payable) {
        return '<span class="promo-old">$' + formatDisplayAmount(payable) + '</span> <span class="promo-new">$' + formatPayableAmount(payable) + '</span>';
    }
    // EN: Remove any legacy 2-year buttons if stale markup is served.
    // AR: إزالة أي أزرار مدة قديمة (سنتان) إذا تم تحميل HTML قديم.
    document.querySelectorAll('[data-years]').forEach(function (btn) {
        var yLegacy = parseInt(btn.getAttribute('data-years'), 10);
        if (isFinite(yLegacy) && yLegacy > 1 && btn.parentNode) {
            btn.parentNode.removeChild(btn);
        }
    });

    // EN: Opens registration section and synchronizes hidden pricing fields.
    // AR: فتح قسم التسجيل وتحديث حقول الخطة/السعر المخفية.
    function showRegistrationForm(plan, amount, years) {
        var registerSection = document.getElementById('register');
        if (registerSection) {
            var successMsg = document.getElementById('successMsg');
            var successText = document.getElementById('successText');
            var phpSuccessMsg = document.getElementById('phpSuccessMsg');
            var form = document.getElementById('regForm');

            if (successMsg) {
                successMsg.style.display = 'none';
            }
            if (successText) {
                successText.innerHTML = '';
            }
            if (phpSuccessMsg) {
                phpSuccessMsg.style.display = 'none';
            }

            if (form) {
                form.style.display = 'block';
            }

            if (form) {
                form.reset();
            }

            if (window.history && window.history.replaceState) {
                var url = new URL(window.location.href);
                window.history.replaceState({}, '', url.toString());
            }

            registerSection.style.display = 'flex';
            var inputPlan = document.getElementById('inputPlan');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');
            var paymentBlockWrap = document.getElementById('paymentBlockWrap');
            var btnSubmit = document.getElementById('btnSubmit');
            if (inputPlan) {
                inputPlan.value = plan;
            }
            if (inputPlanAmount) {
                inputPlanAmount.value = amount || '';
            }
            if (inputYears) {
                var yShow = parseInt(years, 10);
                if (!isFinite(yShow) || yShow < 0) {
                    yShow = 1;
                }
                inputYears.value = String(yShow);
            }
            amount = parseFloat(amount) || 0;
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }
            if (paymentBlockWrap) {
                paymentBlockWrap.style.display = amount > 0 ? 'block' : 'none';
            }
            if (btnSubmit) {
                btnSubmit.style.display = 'block';
            }
            if (amount > 0 && typeof updatePaymentSummary === 'function') {
                updatePaymentSummary(amount, years, plan);
            }
            registerSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }
    window.showRegistrationForm = showRegistrationForm;

    // EN: Debounce-like guard to avoid duplicate summary DOM writes.
    // AR: آلية حماية لتقليل التحديثات المتكررة في ملخص الدفع.
    var lastPaymentSummaryUpdate = { subtotal: 0, years: 0, planKey: '', timestamp: 0 };

    // EN: Render pricing summary block (subtotal, tax, total, currency note).
    // AR: إنشاء وعرض ملخص الدفع (المبلغ، الضريبة، الإجمالي، وملاحظة العملة).
    function updatePaymentSummary(subtotal, years, planKeyOpt) {
        var summaryEl = document.querySelector('.payment-summary-box') ||
            document.querySelector('#paymentBlockWrap .payment-summary-box') ||
            document.querySelector('.register-section .form-card .payment-summary-box') ||
            document.querySelector('#paymentSummary');

        if (!summaryEl) {
            console.log('ERROR: Payment summary element not found! subtotal:', subtotal);
            console.log('Tried selectors: .payment-summary-box, #paymentBlockWrap .payment-summary-box');
            return;
        }

        years = parseInt(years, 10);
        if (!isFinite(years) || years < 0) {
            years = 1;
        }
        var inputPlanEl = document.getElementById('inputPlan');
        var planValue = (planKeyOpt != null && String(planKeyOpt).trim() !== '')
            ? String(planKeyOpt).trim().toLowerCase()
            : (inputPlanEl ? (inputPlanEl.value || inputPlanEl.getAttribute('value') || '').trim().toLowerCase() : '');

        var planLabel = 'Gold';
        if (planValue === 'platinum') {
            planLabel = 'Platinum';
        } else if (planValue === 'pro') {
            planLabel = 'Pro';
        } else if (planValue === 'gold') {
            planLabel = 'Gold';
        } else {
            var activeGoldBtn = document.querySelector('.plan-btn-form[data-plan="gold"]');
            var activePlatinumBtn = document.querySelector('.plan-btn-form[data-plan="platinum"]');
            var goldStyle = activeGoldBtn ? (activeGoldBtn.getAttribute('style') || '') : '';
            var platinumStyle = activePlatinumBtn ? (activePlatinumBtn.getAttribute('style') || '') : '';
            var goldActive = goldStyle.indexOf('rgba(212,175,55') !== -1 || goldStyle.indexOf('#d4af37') !== -1;
            var platinumActive = platinumStyle.indexOf('rgba(241,196,15') !== -1 || platinumStyle.indexOf('#f1c40f') !== -1;
            if (platinumActive && !goldActive) {
                planLabel = 'Platinum';
            } else if (goldActive && !platinumActive) {
                planLabel = 'Gold';
            }
        }

        var now = Date.now();
        if (lastPaymentSummaryUpdate.subtotal === subtotal && lastPaymentSummaryUpdate.years === years &&
            lastPaymentSummaryUpdate.planKey === planValue && (now - lastPaymentSummaryUpdate.timestamp) < 100) {
            console.log('Skipping duplicate updatePaymentSummary call for subtotal:', subtotal);
            return;
        }
        lastPaymentSummaryUpdate = { subtotal: subtotal, years: years, planKey: planValue, timestamp: now };

        var tax = subtotal * 0.15;
        var total = subtotal + tax;
        var displayCur = (typeof window.RATIB_DISPLAY_CHECKOUT_CURRENCY === 'string' && window.RATIB_DISPLAY_CHECKOUT_CURRENCY)
            ? String(window.RATIB_DISPLAY_CHECKOUT_CURRENCY).toUpperCase() : 'SAR';
        var gatewayCur = (typeof window.RATIB_CHECKOUT_CURRENCY === 'string' && window.RATIB_CHECKOUT_CURRENCY)
            ? String(window.RATIB_CHECKOUT_CURRENCY).toUpperCase() : 'SAR';
        if (gatewayCur !== 'SAR' && gatewayCur !== 'USD') {
            gatewayCur = 'SAR';
        }
        var usdToDisplay = (typeof window.RATIB_DISPLAY_USD_RATE === 'number' && isFinite(window.RATIB_DISPLAY_USD_RATE) && window.RATIB_DISPLAY_USD_RATE > 0)
            ? window.RATIB_DISPLAY_USD_RATE : 3.75;
        var usdToGateway = (typeof window.RATIB_USD_TO_SAR === 'number' && isFinite(window.RATIB_USD_TO_SAR) && window.RATIB_USD_TO_SAR > 0)
            ? window.RATIB_USD_TO_SAR : 3.75;
        if (gatewayCur === 'USD') {
            usdToGateway = 1.0;
        }
        var fallbackUsdRates = {
            USD: 1.00,
            SAR: 3.75,
            BDT: 117.50,
            IDR: 16000.00,
            ETB: 57.00,
            PHP: 57.00,
            KES: 129.00,
            UGX: 3800.00,
            NGN: 1450.00,
            RWF: 1300.00,
            LKR: 300.00,
            NPR: 133.00,
            THB: 36.00
        };
        // Guard against stale bootstrap payloads that still send 3.75 for non-SAR currencies.
        if ((!isFinite(usdToDisplay) || usdToDisplay <= 0 || (displayCur !== 'SAR' && Math.abs(usdToDisplay - 3.75) < 0.000001))
            && Object.prototype.hasOwnProperty.call(fallbackUsdRates, displayCur)) {
            usdToDisplay = fallbackUsdRates[displayCur];
        }
        var ngeniusNote = '';
        var gatewayApprox = (total * usdToGateway).toFixed(2);
        var gatewayRateStr = usdToGateway.toFixed(2);
        var displayApprox = (total * usdToDisplay).toFixed(2);
        var displayRateStr = usdToDisplay.toFixed(2);
        ngeniusNote = '<p class="small mb-0 mt-2 ratib-ngenius-currency-note">Card checkout is charged in <strong>' + displayCur + '</strong>: <strong class="ratib-ngenius-sar-total">' + displayCur + ' ' + displayApprox + '</strong> <span class="ratib-ngenius-rate-note">(USD × ' + displayRateStr + ')</span>.</p>';
        if (displayCur !== gatewayCur) {
            ngeniusNote += '<p class="small text-muted mb-0 mt-1 ratib-ngenius-currency-note">You will complete payment in ' + gatewayCur + '.</p>';
        }

        console.log('updatePaymentSummary - subtotal:', subtotal, 'years:', years, 'planLabel:', planLabel, 'inputPlan.value:', inputPlanEl ? inputPlanEl.value : '');

        var durationLabel = years === 0
            ? 'monthly'
            : (years + ' year' + (years > 1 ? 's' : ''));
        var listPrice = subtotal * DISPLAY_MULTIPLIER;
        var discountAmount = listPrice - subtotal;
        summaryEl.innerHTML = '<h4 class="payment-summary-title"><i class="fas fa-receipt me-2"></i>Payment Summary</h4>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">List Price</span>' +
            '<span class="payment-summary-value">$' + listPrice.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">Discount (50%)</span>' +
            '<span class="payment-summary-value payment-summary-discount">-$' + discountAmount.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">' + planLabel + ' Plan (' + durationLabel + ')</span>' +
            '<span class="payment-summary-value">$' + subtotal.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-row">' +
            '<span class="payment-summary-muted">Tax (15%)</span>' +
            '<span class="payment-summary-value">$' + tax.toFixed(2) + '</span>' +
            '</div>' +
            '<div class="payment-summary-total-row">' +
            '<span>Total</span>' +
            '<span>' + displayCur + ' ' + displayApprox + '</span>' +
            '</div>' + ngeniusNote;
    }

    // EN: Form state manager for plan/year buttons and hidden inputs.
    // AR: إدارة حالة النموذج وربط أزرار الخطة/المدة بالحقول المخفية.
    (function () {
        var form = document.getElementById('regForm');
        if (!form) {
            return;
        }
        var desiredSiteUrlInput = form.querySelector('input[name="desired_site_url"]');
        if (desiredSiteUrlInput) {
            desiredSiteUrlInput.removeAttribute('required');
            var desiredLabel = desiredSiteUrlInput.closest('.mb-3');
            if (desiredLabel) {
                var labelEl = desiredLabel.querySelector('.form-label');
                if (labelEl) {
                    labelEl.textContent = 'Desired Site URL (optional)';
                }
            }
        }

        document.getElementById('countrySelect').addEventListener('change', function () {
            var wrap = document.getElementById('otherCountryWrap');
            wrap.style.display = (this.value === 'Other countries sending workers') ? 'block' : 'none';
            if (wrap.style.display === 'none') {
                document.getElementById('countryOther').value = '';
            }
        });
        var inputPlan = document.getElementById('inputPlan');
        var inputPlanAmount = document.getElementById('inputPlanAmount');
        var inputYears = document.getElementById('inputYears');
        var paymentBlockWrap = document.getElementById('paymentBlockWrap');
        var btnSubmit = document.getElementById('btnSubmit');
        var formYearButtonsWrap = document.getElementById('formYearButtonsWrap');
        // Keep duration choices limited to supported tiers only (monthly and 1 year).
        var legacyYearButtons = document.querySelectorAll('.form-year-btn[data-years]:not([data-years="0"]):not([data-years="1"])');
        legacyYearButtons.forEach(function (btn) {
            if (btn && btn.parentNode) {
                btn.parentNode.removeChild(btn);
            }
        });
        var formYearButtons = document.querySelectorAll('.form-year-btn');
        var planBtns = document.querySelectorAll('.plan-btn-form');
        var activePlanStyle = {
            gold: 'border-color: rgba(212,175,55,0.8); background: rgba(212,175,55,0.2); color: #d4af37;',
            platinum: 'border-color: rgba(241,196,15,0.8); background: rgba(241,196,15,0.2); color: #f1c40f;',
            pro: 'border-color: rgba(93,173,226,0.6); background: rgba(93,173,226,0.15); color: #5dade2;'
        };
        var inactiveStyle = 'border: 2px solid rgba(255,255,255,0.3); background: rgba(255,255,255,0.05); color: #aaa;';
        function setFormPlan(planVal, amount, years) {
            planVal = planVal || '';
            if (inputPlan) {
                inputPlan.value = planVal;
                inputPlan.setAttribute('value', planVal);
            }
            if (inputPlanAmount) {
                inputPlanAmount.value = amount || '';
                inputPlanAmount.setAttribute('value', amount || '');
            }
            if (inputYears) {
                var yIn = parseInt(years, 10);
                if (!isFinite(yIn) || yIn < 0) {
                    yIn = 1;
                }
                inputYears.value = String(yIn);
                inputYears.setAttribute('value', String(yIn));
            }
            amount = parseFloat(amount) || 0;
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }

            console.log('setFormPlan called - planVal:', planVal, 'amount:', amount, 'years:', years);

            if (formYearButtonsWrap) {
                formYearButtonsWrap.style.display = (planVal === 'gold' || planVal === 'platinum') ? 'block' : 'none';
            }
            if (paymentBlockWrap) {
                paymentBlockWrap.style.display = amount > 0 ? 'block' : 'none';
                console.log('paymentBlockWrap display set to:', amount > 0 ? 'block' : 'none', 'for amount:', amount);
            }
            var placeholder = document.getElementById('paymentBlockPlaceholder');
            if (placeholder) {
                placeholder.style.display = amount > 0 ? 'none' : 'block';
            }
            if (btnSubmit) {
                btnSubmit.style.display = 'block';
            }
            planBtns.forEach(function (b) {
                var p = b.getAttribute('data-plan');
                b.setAttribute('style', (p === planVal ? (activePlanStyle[p] || inactiveStyle) : inactiveStyle) + ' padding: 0.5rem 1rem; border-radius: 8px; font-weight: 600; cursor: pointer; transition: all 0.2s;');
            });
            if (planVal === 'gold' || planVal === 'platinum') {
                if (inputPlan && inputPlan.value !== planVal) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                formYearButtons.forEach(function (b) {
                    var y = parseInt(b.getAttribute('data-years'), 10);
                    if (isNaN(y) || y < 0) {
                        y = 1;
                    }
                    var price = planVal === 'gold' ? parseFloat(b.getAttribute('data-price-gold')) : parseFloat(b.getAttribute('data-price-platinum'));
                    var span = b.querySelector('.form-year-price');
                    if (span) {
                        span.innerHTML = formatPromoInline(price);
                    }
                    var isActive = (y === years);
                    if (planVal === 'gold') {
                        b.style.border = isActive ? '2px solid rgba(212,175,55,0.8)' : '2px solid rgba(255,255,255,0.2)';
                        b.style.background = isActive ? 'rgba(212,175,55,0.2)' : 'rgba(255,255,255,0.05)';
                        b.style.color = isActive ? '#d4af37' : '#aaa';
                    } else {
                        b.style.border = isActive ? '2px solid rgba(241,196,15,0.8)' : '2px solid rgba(255,255,255,0.2)';
                        b.style.background = isActive ? 'rgba(241,196,15,0.2)' : 'rgba(255,255,255,0.05)';
                        b.style.color = isActive ? '#f1c40f' : '#aaa';
                    }
                });
            }
            if (amount > 0 && typeof updatePaymentSummary === 'function') {
                if (inputPlan) {
                    inputPlan.value = planVal || 'gold';
                    inputPlan.setAttribute('value', planVal || 'gold');
                }
                if (paymentBlockWrap) {
                    paymentBlockWrap.style.display = 'block';
                }
                console.log('Calling updatePaymentSummary with amount:', amount, 'planVal:', planVal);
                updatePaymentSummary(amount, years, planVal);
            } else {
                console.log('NOT calling updatePaymentSummary - amount:', amount, 'function exists:', typeof updatePaymentSummary === 'function');
            }
        }
        var initialPlan = HOME.initialPlan;
        var initialAmount = HOME.initialAmount;
        var initialYears = HOME.initialYears;
        var defaultAmount = null;
        if (initialPlan === 'gold') {
            defaultAmount = initialYears === 0 ? HOME.goldMonth : HOME.goldYear1;
        } else if (initialPlan === 'platinum') {
            defaultAmount = initialYears === 0 ? HOME.platinumMonth : HOME.platinumYear1;
        }
        if (inputPlan && initialPlan) {
            inputPlan.value = initialPlan;
            inputPlan.setAttribute('value', initialPlan);
        }
        setFormPlan(initialPlan, initialAmount !== null ? initialAmount : defaultAmount, initialYears);
        if (openRegister) {
            var rs = document.getElementById('register');
            if (rs) {
                rs.style.display = 'flex';
                rs.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        }
        planBtns.forEach(function (b) {
            b.addEventListener('click', function () {
                var planVal = this.getAttribute('data-plan');
                var amt = this.getAttribute('data-amount');
                var y = parseInt(this.getAttribute('data-years'), 10) || 1;

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                if (planVal === 'gold' || planVal === 'platinum') {
                    amt = parseFloat(amt) || 0;

                    if (!amt || amt === 0) {
                        var firstYearBtn = document.querySelector('.form-year-btn[data-years="1"]');
                        if (firstYearBtn) {
                            var price = planVal === 'gold' ? parseFloat(firstYearBtn.getAttribute('data-price-gold')) : parseFloat(firstYearBtn.getAttribute('data-price-platinum'));
                            amt = price || (planVal === 'gold' ? HOME.goldYear1 : HOME.platinumYear1);
                        } else {
                            amt = planVal === 'gold' ? HOME.goldYear1 : HOME.platinumYear1;
                        }
                    }
                    y = 1;
                }

                console.log('Plan button clicked - planVal:', planVal, 'amt:', amt, 'y:', y);

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                    inputPlan.dispatchEvent(new Event('change', { bubbles: true }));
                }

                setFormPlan(planVal, amt, y);
            });
        });
        formYearButtons.forEach(function (b) {
            b.addEventListener('click', function () {
                var planVal = inputPlan ? (inputPlan.value || 'gold') : 'gold';
                planVal = planVal.trim().toLowerCase();

                if (planVal !== 'gold' && planVal !== 'platinum') {
                    var activeGoldBtn = document.querySelector('.plan-btn-form[data-plan="gold"]');
                    var activePlatinumBtn = document.querySelector('.plan-btn-form[data-plan="platinum"]');
                    var goldStyle = activeGoldBtn ? (activeGoldBtn.getAttribute('style') || '') : '';
                    var platinumStyle = activePlatinumBtn ? (activePlatinumBtn.getAttribute('style') || '') : '';

                    if (goldStyle.indexOf('rgba(212,175,55') !== -1 || goldStyle.indexOf('#d4af37') !== -1) {
                        planVal = 'gold';
                    } else if (platinumStyle.indexOf('rgba(241,196,15') !== -1 || platinumStyle.indexOf('#f1c40f') !== -1) {
                        planVal = 'platinum';
                    }
                }

                var yDur = parseInt(this.getAttribute('data-years'), 10);
                if (isNaN(yDur) || yDur < 0) {
                    yDur = 1;
                }
                var price = planVal === 'gold' ? parseFloat(this.getAttribute('data-price-gold')) : parseFloat(this.getAttribute('data-price-platinum'));

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                setFormPlan(planVal, price, yDur);
            });
        });
    })();

    // EN: Price card interactions (top pricing cards) and year toggles.
    // AR: تفاعلات بطاقات الأسعار العلوية وتبديل مدة الاشتراك.
    (function () {
        var goldPrices = { 0: HOME.goldMonth, 1: HOME.goldYear1 };
        var platinumPrices = { 0: HOME.platinumMonth, 1: HOME.platinumYear1 };

        function updateGoldPrice(years, event) {
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }
            var price = goldPrices.hasOwnProperty(years) ? goldPrices[years] : HOME.goldYear1;
            var oldPrice = price * 2;
            var priceEl = document.getElementById('goldPrice');
            var oldPriceEl = document.getElementById('goldOldPrice');
            var btn = document.getElementById('goldRegisterBtn');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');

            if (priceEl) {
                var goldLbl = years === 0 ? 'per month' : ('for ' + years + ' year' + (years > 1 ? 's' : ''));
                priceEl.innerHTML = '$' + price.toLocaleString() + ' <span id="goldPriceLabel">' + goldLbl + '</span>';
            }
            if (oldPriceEl) {
                oldPriceEl.textContent = '$' + oldPrice.toLocaleString();
            }
            if (btn) {
                btn.setAttribute('data-register-plan', 'gold');
                btn.setAttribute('data-register-amount', String(price));
                btn.setAttribute('data-register-years', String(years));
            }

            if (event && event.type === 'click') {
                if (inputPlanAmount) {
                    inputPlanAmount.value = price;
                }
                if (inputYears) {
                    inputYears.value = String(years);
                }
                var inputPlanEl = document.getElementById('inputPlan');
                if (inputPlanEl) {
                    inputPlanEl.value = 'gold';
                    inputPlanEl.setAttribute('value', 'gold');
                }
                var registerSection = document.getElementById('register');
                if (registerSection && registerSection.style.display !== 'none') {
                    setTimeout(function () {
                        updatePaymentSummary(price, years, 'gold');
                    }, 10);
                }
            }

            document.querySelectorAll('.gold-year-btn').forEach(function (b) {
                var btnYears = parseInt(b.getAttribute('data-years'), 10) || 0;
                if (btnYears === years) {
                    b.classList.add('active');
                    b.style.background = 'rgba(212,175,55,0.2)';
                    b.style.borderColor = '#d4af37';
                    b.style.color = '#d4af37';
                } else {
                    b.classList.remove('active');
                    b.style.background = 'rgba(255,255,255,0.05)';
                    b.style.borderColor = 'rgba(255,255,255,0.2)';
                    b.style.color = '#aaa';
                }
            });
        }

        function updatePlatinumPrice(years, event) {
            years = parseInt(years, 10);
            if (!isFinite(years) || years < 0) {
                years = 1;
            }
            var price = platinumPrices.hasOwnProperty(years) ? platinumPrices[years] : HOME.platinumYear1;
            var oldPrice = price * 2;
            var priceEl = document.getElementById('platinumPrice');
            var oldPriceEl = document.getElementById('platinumOldPrice');
            var btn = document.getElementById('platinumRegisterBtn');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');

            if (priceEl) {
                var platLbl = years === 0 ? 'per month' : ('for ' + years + ' year' + (years > 1 ? 's' : ''));
                priceEl.innerHTML = '$' + price.toLocaleString() + ' <span id="platinumPriceLabel">' + platLbl + '</span>';
            }
            if (oldPriceEl) {
                oldPriceEl.textContent = '$' + oldPrice.toLocaleString();
            }
            if (btn) {
                btn.setAttribute('data-register-plan', 'platinum');
                btn.setAttribute('data-register-amount', String(price));
                btn.setAttribute('data-register-years', String(years));
            }

            if (event && event.type === 'click') {
                if (inputPlanAmount) {
                    inputPlanAmount.value = price;
                }
                if (inputYears) {
                    inputYears.value = String(years);
                }
                var inputPlanEl = document.getElementById('inputPlan');
                if (inputPlanEl) {
                    inputPlanEl.value = 'platinum';
                    inputPlanEl.setAttribute('value', 'platinum');
                }
                var registerSection = document.getElementById('register');
                if (registerSection && registerSection.style.display !== 'none' && typeof updatePaymentSummary === 'function') {
                    setTimeout(function () {
                        updatePaymentSummary(price, years, 'platinum');
                    }, 10);
                }
            }

            document.querySelectorAll('.platinum-year-btn').forEach(function (b) {
                var btnYears = parseInt(b.getAttribute('data-years'), 10) || 0;
                if (btnYears === years) {
                    b.classList.add('active');
                    b.style.background = 'rgba(241,196,15,0.2)';
                    b.style.borderColor = '#f1c40f';
                    b.style.color = '#f1c40f';
                } else {
                    b.classList.remove('active');
                    b.style.background = 'rgba(255,255,255,0.05)';
                    b.style.borderColor = 'rgba(255,255,255,0.2)';
                    b.style.color = '#aaa';
                }
            });
        }

        document.querySelectorAll('.gold-year-btn').forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                var y = parseInt(this.getAttribute('data-years'), 10);
                if (isNaN(y) || y < 0) {
                    y = 1;
                } else if (y > 1) {
                    y = 1;
                }
                updateGoldPrice(y, e);
            });
        });

        document.querySelectorAll('.platinum-year-btn').forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                var y = parseInt(this.getAttribute('data-years'), 10);
                if (isNaN(y) || y < 0) {
                    y = 1;
                } else if (y > 1) {
                    y = 1;
                }
                updatePlatinumPrice(y, e);
            });
        });

        (function syncPricingCardsFromBootstrap() {
            var iy = parseInt(HOME.initialYears, 10);
            if (isNaN(iy) || iy < 0) {
                iy = 1;
            }
            if (HOME.initialPlan === 'gold' && (iy === 0 || iy === 1)) {
                updateGoldPrice(iy, null);
            } else if (HOME.initialPlan === 'platinum' && (iy === 0 || iy === 1)) {
                updatePlatinumPrice(iy, null);
            }
        })();
    })();

    // EN: Delegated click handlers for register anchors.
    // AR: معالجات نقر عامة لروابط التسجيل.
    document.addEventListener('click', function (e) {
        var scrollA = e.target.closest('a.js-scroll-register');
        if (scrollA && scrollA.getAttribute('href') === '#register') {
            e.preventDefault();
            var registerSection = document.getElementById('register');
            if (registerSection) {
                registerSection.style.display = 'flex';
                registerSection.scrollIntoView({ behavior: 'smooth' });
            }
            return;
        }
        var openA = e.target.closest('a.js-open-register');
        if (openA) {
            e.preventDefault();
            var plan = openA.getAttribute('data-register-plan') || 'gold';
            var amount = parseFloat(openA.getAttribute('data-register-amount') || '0') || 0;
            var yrs = parseInt(openA.getAttribute('data-register-years') || '1', 10);
            if (isNaN(yrs) || yrs < 0) {
                yrs = 1;
            }
            showRegistrationForm(plan, amount, yrs);
        }
    });
})();

(function ratibHomeNavChrome() {
    var header = document.getElementById('ratib-main-header');
    var toggle = document.getElementById('ratibNavToggle');
    var menu = document.getElementById('ratibNavMenu');
    if (!header) {
        return;
    }
    function onScroll() {
        header.classList.toggle('is-scrolled', window.scrollY > 32);
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
    if (toggle && menu) {
        toggle.addEventListener('click', function () {
            var open = menu.classList.toggle('is-open');
            toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
        });
        menu.addEventListener('click', function (ev) {
            if (!ev.target.closest('a')) {
                return;
            }
            menu.classList.remove('is-open');
            toggle.setAttribute('aria-expanded', 'false');
        });
    }
})();

/** If the server HTML is stale/cached and omits video/pic nav, insert it after Platform (same href rules as PHP). */
(function ratibHomeEnsureProductTourNavTab() {
    function productTourHref() {
        if (document.getElementById('video')) {
            return '#video';
        }
        if (document.getElementById('program-previews')) {
            return '#program-previews';
        }
        return '#platform';
    }
    function run() {
        var nav = document.getElementById('ratibNavMenu');
        if (!nav || nav.querySelector('[data-ratib-product-tour-tab]')) {
            return;
        }
        var platform = nav.querySelector('a[href="#platform"]');
        if (!platform || !platform.parentNode) {
            return;
        }
        var a = document.createElement('a');
        a.href = productTourHref();
        a.className = 'ratib-nav__link ratib-nav__link--product-tour';
        a.setAttribute('data-ratib-product-tour-tab', '1');
        a.setAttribute('data-ratib-product-tour-fallback', '1');
        a.innerHTML =
            '<span class="ratib-nav__icon" aria-hidden="true"><svg class="ratib-nav__glyph" viewBox="0 0 24 24" focusable="false"><use href="#ratib-ng-video"/></svg></span>' +
            '<span class="ratib-nav__label">Tour</span>';
        platform.parentNode.insertBefore(a, platform.nextSibling);
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', run);
    } else {
        run();
    }
})();

/** Normalize stale cached nav HTML to the compact IA (Domains/Sites/Grow + 7 platform pills). */
(function ratibHomeNormalizeLegacyNav() {
    function textOf(el) {
        return ((el && el.textContent) || '').replace(/\s+/g, ' ').trim().toLowerCase();
    }
    function hashPart(href) {
        if (!href) {
            return '';
        }
        var i = href.indexOf('#');
        if (i === -1) {
            return '';
        }
        return href.slice(i).split('?')[0];
    }
    function run() {
        var nav = document.getElementById('ratibNavMenu');
        if (!nav || nav.getAttribute('data-ratib-nav-sync') === '1') {
            return;
        }

        // Top mega row normalization for stale cached markup.
        nav.querySelectorAll('.ratib-mega-nav__trigger-label, .ratib-mega-nav__flat-label').forEach(function (labelEl) {
            var t = textOf(labelEl);
            if (t === 'websites') {
                labelEl.textContent = 'Sites';
            } else if (t === 'marketing') {
                labelEl.textContent = 'Grow';
            }
        });
        nav.querySelectorAll('.ratib-mega-nav__li').forEach(function (li) {
            var labelEl = li.querySelector('.ratib-mega-nav__trigger-label, .ratib-mega-nav__flat-label');
            var flat = li.querySelector('a.ratib-mega-nav__flat');
            var t = textOf(labelEl);
            var fh = flat ? flat.getAttribute('href') || '' : '';
            if (
                t === 'email' ||
                t === 'hosting' ||
                t === 'ai builder' ||
                t === 'pricing' ||
                t === 'plans & register' ||
                /#register\b/i.test(hashPart(fh))
            ) {
                li.remove();
            }
        });

        function pillKeyFromHref(href, a) {
            var hp = hashPart(href);
            if (a.classList.contains('ratib-nav__link--about')) {
                return 'about';
            }
            if (
                a.classList.contains('ratib-nav__link--product-tour') ||
                hp === '#video' ||
                hp === '#program-previews' ||
                hp === '#top'
            ) {
                return 'tour';
            }
            if (
                a.classList.contains('ratib-nav__link--platform-section') ||
                hp === '#what-is-ratib' ||
                hp === '#platform'
            ) {
                return 'platform';
            }
            if (hp === '#corridors' || hp === '#domains') {
                return 'domains';
            }
            if (hp === '#platform-services' || hp === '#features') {
                return 'product';
            }
            if (hp === '#finance' || hp === '#programs') {
                return 'pricing';
            }
            if (hp === '#partners' || hp === '#agencies') {
                return 'partners';
            }
            if (hp === '#contact-cta' || hp === '#contact') {
                return 'contact';
            }
            if (
                /\/profile\/?([#?]|$)/i.test(href) ||
                /company-profile\.php/i.test(href) ||
                /about\.php/i.test(href) ||
                /[?&]open=(about|profile)\b/i.test(href)
            ) {
                return 'about';
            }
            if (/\/modules\/infrastructure-marketplace\/Views\/marketplace\/index\.php/i.test(href)) {
                return 'legacy-remove';
            }
            if (/\/modules\/infrastructure-marketplace\/Views\/client\/services\.php/i.test(href)) {
                return 'legacy-remove';
            }
            return 'legacy-remove';
        }

        // Platform pills normalization: keep only Platform/Domains/Tour/Product/Pricing/Partners/Contact.
        var pillWrap = nav.querySelector('.ratib-nav__platform-links');
        if (!pillWrap) {
            nav.setAttribute('data-ratib-nav-sync', '1');
            return;
        }
        if (
            document.body &&
            (document.body.classList.contains('ratib-about-page') ||
                document.body.getAttribute('data-ratib-about') === '1')
        ) {
            nav.setAttribute('data-ratib-nav-sync', '1');
            nav.style.visibility = 'visible';
            nav.style.opacity = '1';
            nav.style.pointerEvents = 'auto';
            return;
        }
        var linkByKey = new Map();
        pillWrap.querySelectorAll('a.ratib-nav__link').forEach(function (a) {
            var href = a.getAttribute('href') || '';
            var key = pillKeyFromHref(href, a);

            if (key === 'legacy-remove') {
                a.remove();
                return;
            }
            if (!linkByKey.has(key)) {
                linkByKey.set(key, a);
            } else {
                a.remove();
            }
        });

        var desiredOrder = ['about', 'platform', 'domains', 'tour', 'product', 'pricing', 'partners', 'contact'];
        desiredOrder.forEach(function (key) {
            var node = linkByKey.get(key);
            if (!node) {
                return;
            }
            var label = node.querySelector('.ratib-nav__label');
            if (label) {
                if (key === 'about' && !label.textContent.trim()) {
                    label.textContent = 'Profile';
                }
                if (key === 'tour') label.textContent = 'Tour';
                if (key === 'domains') label.textContent = 'Domains';
                if (key === 'product') label.textContent = 'Product';
                if (key === 'pricing') label.textContent = 'Pricing';
                if (key === 'partners') label.textContent = 'Partners';
            }
            pillWrap.appendChild(node);
        });
        var PROFILE = (window.location.origin || '') + '/profile/#company-profile';
        var onProfilePage =
            document.body &&
            (document.body.classList.contains('ratib-about-page') ||
                document.body.getAttribute('data-ratib-about') === '1');
        pillWrap
            .querySelectorAll('.ratib-nav__brand-profile, .ratib-nav__link--about, [data-ratib-profile-nav]')
            .forEach(function (a) {
                a.setAttribute('href', PROFILE);
                a.setAttribute('data-ratib-profile-nav', '1');
                if (!onProfilePage) {
                    a.setAttribute('target', '_blank');
                    a.setAttribute('rel', 'noopener noreferrer');
                }
            });
        var aboutNode = linkByKey.get('about');
        if (aboutNode) {
            aboutNode.setAttribute('href', PROFILE);
            aboutNode.setAttribute('data-ratib-profile-nav', '1');
            if (!onProfilePage) {
                aboutNode.setAttribute('target', '_blank');
                aboutNode.setAttribute('rel', 'noopener noreferrer');
            }
        }
        nav.setAttribute('data-ratib-nav-sync', '1');
        nav.style.visibility = 'visible';
        nav.style.opacity = '1';
        nav.style.pointerEvents = 'auto';
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', run);
    } else {
        run();
    }
})();

/** Phase 2: subtle scroll reveal — adds classes only; no DOM/markup changes. */
(function ratibHomeScrollReveal() {
    if (!window.IntersectionObserver) {
        return;
    }
    var reduce =
        window.matchMedia &&
        window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduce) {
        return;
    }
    var main = document.querySelector('.ratib-main');
    if (!main) {
        return;
    }
    var sel =
        '.ratib-hero, .ratib-section, .pricing-section.ratib-pricing-saas, .video-section.ratib-video, .ratib-final-cta';
    var els = main.querySelectorAll(sel);
    if (!els.length) {
        return;
    }
    var html = document.documentElement;
    els.forEach(function (el) {
        el.classList.add('ratib-reveal');
        var r = el.getBoundingClientRect();
        var vh = window.innerHeight || document.documentElement.clientHeight;
        if (r.top < vh * 0.92 && r.bottom > -40) {
            el.classList.add('ratib-reveal-visible');
        }
    });
    html.classList.add('ratib-reveal-init');
    html.classList.add('ratib-reveal-ready');
    var io = new IntersectionObserver(
        function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    entry.target.classList.add('ratib-reveal-visible');
                    io.unobserve(entry.target);
                }
            });
        },
        { rootMargin: '0px 0px -6% 0px', threshold: 0.06 }
    );
    els.forEach(function (el) {
        if (!el.classList.contains('ratib-reveal-visible')) {
            io.observe(el);
        }
    });
})();

/** Program preview strip: horizontal marquee + click-to-enlarge. Must run for all users (incl. prefers-reduced-motion). */
(function ratibHomeProgramStrip() {
    function attachProgramStripDrag(viewport, wrapFn) {
        var dragThreshold = 8;
        var dragState = null;

        viewport.addEventListener('pointerdown', function (ev) {
            if (ev.button !== 0) {
                return;
            }
            dragState = {
                pointerId: ev.pointerId,
                startX: ev.clientX,
                startScroll: viewport.scrollLeft,
                dragged: false,
                captured: false,
            };
            /* Do NOT setPointerCapture here — it retargets the click to the viewport so
               [data-ratib-program-open] never receives the synthetic click. Capture only after drag intent. */
        });

        viewport.addEventListener('pointermove', function (ev) {
            if (!dragState || ev.pointerId !== dragState.pointerId) {
                return;
            }
            var dx = ev.clientX - dragState.startX;
            if (!dragState.dragged && Math.abs(dx) > dragThreshold) {
                dragState.dragged = true;
                try {
                    viewport.setPointerCapture(ev.pointerId);
                    dragState.captured = true;
                } catch (eCap) {}
                viewport.classList.add('ratib-program-marquee__viewport--dragging');
            }
            if (dragState.dragged) {
                viewport.scrollLeft = dragState.startScroll - dx;
                wrapFn();
            }
        });

        function endDrag(ev) {
            if (!dragState || ev.pointerId !== dragState.pointerId) {
                return;
            }
            if (dragState.captured) {
                try {
                    viewport.releasePointerCapture(ev.pointerId);
                } catch (eRel) {}
            }
            viewport.classList.remove('ratib-program-marquee__viewport--dragging');
            if (dragState.dragged) {
                viewport.setAttribute('data-ratib-marquee-suppress-click', '1');
            }
            dragState = null;
        }

        viewport.addEventListener('pointerup', endDrag);
        viewport.addEventListener('pointercancel', endDrag);
    }

    function attachProgramStripScrollButtons(root, viewport, track) {
        if (!root || !viewport || !track) {
            return;
        }
        var btnPrev = root.querySelector('[data-ratib-program-marquee-scroll-prev]');
        var btnNext = root.querySelector('[data-ratib-program-marquee-scroll-next]');
        if (!btnPrev || !btnNext) {
            return;
        }
        function wrapViewport() {
            var w = track.scrollWidth / 2;
            if (w <= 0) {
                return;
            }
            while (viewport.scrollLeft >= w) {
                viewport.scrollLeft -= w;
            }
            while (viewport.scrollLeft < 0) {
                viewport.scrollLeft += w;
            }
        }
        function scrollStep() {
            var cw = viewport.clientWidth || 360;
            return Math.round(Math.min(420, Math.max(160, cw * 0.78)));
        }
        btnPrev.addEventListener('click', function (ev) {
            ev.preventDefault();
            viewport.scrollLeft -= scrollStep();
            wrapViewport();
        });
        btnNext.addEventListener('click', function (ev) {
            ev.preventDefault();
            viewport.scrollLeft += scrollStep();
            wrapViewport();
        });
    }

    function initProgramStripMarqueeAndLightbox() {
        var mqRoot = document.querySelector('[data-ratib-program-marquee]');
        if (mqRoot) {
            var viewport = mqRoot.querySelector('.ratib-program-marquee__viewport');
            var track = mqRoot.querySelector('.ratib-program-marquee__track');
            var mqReduce = window.matchMedia('(prefers-reduced-motion: reduce)');
            if (mqReduce.matches) {
                mqRoot.classList.add('ratib-program-marquee--no-motion');
                if (viewport && track) {
                    function wrapNm() {
                        var w = track.scrollWidth / 2;
                        if (w <= 0) {
                            return;
                        }
                        while (viewport.scrollLeft >= w) {
                            viewport.scrollLeft -= w;
                        }
                        while (viewport.scrollLeft < 0) {
                            viewport.scrollLeft += w;
                        }
                    }
                    viewport.addEventListener(
                        'wheel',
                        function (ev) {
                            if (!viewport.contains(ev.target)) {
                                return;
                            }
                            var dy = ev.deltaY;
                            var dx = ev.deltaX;
                            var d = Math.abs(dx) > Math.abs(dy) ? dx : dy;
                            if (!d) {
                                return;
                            }
                            ev.preventDefault();
                            viewport.scrollLeft += d * 1.15;
                            wrapNm();
                        },
                        { passive: false }
                    );
                    attachProgramStripDrag(viewport, wrapNm);
                    attachProgramStripScrollButtons(mqRoot, viewport, track);
                }
            } else if (track && viewport) {
                mqRoot.classList.add('ratib-program-marquee--js-marquee');
                var loopW = 0;
                var tabHidden = false;
                var hoverPause = false;
                var lastTs = 0;
                var rafId = 0;
                /** ~px/s — higher = faster auto-scroll (was ~38px/s via CSS duration). */
                var speedPxSec = 88;

                function measureLoop() {
                    loopW = track.scrollWidth / 2;
                }

                function wrapScrollLeft() {
                    if (loopW <= 0) {
                        return;
                    }
                    while (viewport.scrollLeft >= loopW) {
                        viewport.scrollLeft -= loopW;
                    }
                    while (viewport.scrollLeft < 0) {
                        viewport.scrollLeft += loopW;
                    }
                }

                function onWheelMarquee(ev) {
                    if (!viewport.contains(ev.target)) {
                        return;
                    }
                    var dy = ev.deltaY;
                    var dx = ev.deltaX;
                    var delta = Math.abs(dx) > Math.abs(dy) ? dx : dy;
                    if (!delta) {
                        return;
                    }
                    ev.preventDefault();
                    viewport.scrollLeft += delta * 1.15;
                    wrapScrollLeft();
                }

                function tick(now) {
                    var t = now !== undefined ? now : performance.now();
                    if (!lastTs) {
                        lastTs = t;
                    }
                    var dt = Math.min(0.045, (t - lastTs) / 1000);
                    lastTs = t;
                    if (!tabHidden && !hoverPause && loopW > 0) {
                        viewport.scrollLeft += speedPxSec * dt;
                        wrapScrollLeft();
                    }
                    rafId = window.requestAnimationFrame(tick);
                }

                measureLoop();
                window.addEventListener('load', measureLoop);
                window.addEventListener('resize', measureLoop);
                if (window.ResizeObserver) {
                    try {
                        var roMarq = new ResizeObserver(function () {
                            measureLoop();
                        });
                        roMarq.observe(track);
                    } catch (eRo) {}
                }

                viewport.addEventListener('mouseenter', function () {
                    hoverPause = true;
                });
                viewport.addEventListener('mouseleave', function () {
                    hoverPause = false;
                    lastTs = 0;
                });
                viewport.addEventListener('wheel', onWheelMarquee, { passive: false });

                attachProgramStripDrag(viewport, wrapScrollLeft);
                attachProgramStripScrollButtons(mqRoot, viewport, track);

                document.addEventListener('visibilitychange', function () {
                    tabHidden = document.hidden;
                    if (!tabHidden) {
                        lastTs = 0;
                    }
                });

                rafId = window.requestAnimationFrame(tick);
            }
        }

        var mqForSlides = document.querySelector('[data-ratib-program-marquee]');
        /* First half of thumbnails = one full marquee cycle (same order as CMS slots). The second half is only for infinite scroll — do not dedupe by URL or duplicate captions collapse to one slide and hide Prev/Next. */
        var slides = [];
        if (mqForSlides) {
            var allProgOpen = mqForSlides.querySelectorAll('[data-ratib-program-open]');
            var total = allProgOpen.length;
            var halfCount = Math.floor(total / 2);
            slides = Array.prototype.slice.call(allProgOpen, 0, halfCount > 0 ? halfCount : total);
        }

        var lb = document.getElementById('ratib-program-lightbox');
        if (!lb) {
            return;
        }
        var imgEl = lb.querySelector('.ratib-program-lightbox__img');
        var capEl = lb.querySelector('.ratib-program-lightbox__caption');
        var controlsEl = document.getElementById('ratib-program-lightbox-controls');
        var counterEl = document.getElementById('ratib-program-lightbox-counter');
        var lbIndex = 0;

        function readSlideFromBtn(btn) {
            var full = btn.getAttribute('data-full-src') || '';
            var im = btn.querySelector('img');
            var altText = im ? im.getAttribute('alt') || '' : '';
            var cap = btn.getAttribute('data-caption');
            if (cap === null || typeof cap === 'undefined') {
                cap = '';
            }
            if (!full && im) {
                full = im.getAttribute('src') || '';
            }
            return { src: full, alt: altText, caption: cap };
        }

        function indexOfProgramSlide(btn) {
            var idx = slides.indexOf(btn);
            if (idx >= 0) {
                return idx;
            }
            var full = btn.getAttribute('data-full-src') || '';
            var im0 = btn.querySelector('img');
            if (!full && im0) {
                full = im0.getAttribute('src') || '';
            }
            var capBtn = String(btn.getAttribute('data-caption') || '');
            var si;
            for (si = 0; si < slides.length; si++) {
                var b = slides[si];
                var f = b.getAttribute('data-full-src') || '';
                var im = b.querySelector('img');
                if (!f && im) {
                    f = im.getAttribute('src') || '';
                }
                var capS = String(b.getAttribute('data-caption') || '');
                if (full && f === full && capBtn === capS) {
                    return si;
                }
            }
            for (si = 0; si < slides.length; si++) {
                var b2 = slides[si];
                var f2 = b2.getAttribute('data-full-src') || '';
                var im2 = b2.querySelector('img');
                if (!f2 && im2) {
                    f2 = im2.getAttribute('src') || '';
                }
                if (full && f2 === full) {
                    return si;
                }
            }
            return 0;
        }

        function syncLbNav() {
            var hide = slides.length <= 1;
            if (controlsEl) {
                controlsEl.hidden = hide;
            }
        }

        function applyLbIndex(i) {
            if (!slides.length || !imgEl) {
                return;
            }
            lbIndex = (i % slides.length + slides.length) % slides.length;
            var o = readSlideFromBtn(slides[lbIndex]);
            imgEl.src = o.src || '';
            imgEl.alt = o.alt || '';
            if (capEl) {
                var t = (o.caption || '').trim();
                capEl.textContent = t;
                capEl.hidden = !t;
            }
            if (counterEl) {
                counterEl.textContent =
                    slides.length > 1 ? String(lbIndex + 1) + ' / ' + String(slides.length) : '';
            }
        }

        function openLbAt(i) {
            applyLbIndex(i);
            lb.hidden = false;
            lb.classList.add('ratib-program-lightbox--open');
            document.body.classList.add('ratib-program-lightbox-open');
            syncLbNav();
        }

        function closeLb() {
            lb.hidden = true;
            lb.classList.remove('ratib-program-lightbox--open');
            document.body.classList.remove('ratib-program-lightbox-open');
            if (imgEl) {
                imgEl.removeAttribute('src');
                imgEl.alt = '';
            }
            if (capEl) {
                capEl.textContent = '';
                capEl.hidden = true;
            }
            if (counterEl) {
                counterEl.textContent = '';
            }
        }

        document.addEventListener('click', function (ev) {
            var closeHit = ev.target.closest('[data-ratib-program-lightbox-close]');
            if (closeHit && !lb.hidden) {
                ev.preventDefault();
                closeLb();
                return;
            }

            var vpMarq = ev.target.closest('.ratib-program-marquee__viewport');
            if (vpMarq && vpMarq.getAttribute('data-ratib-marquee-suppress-click')) {
                ev.preventDefault();
                ev.stopPropagation();
                vpMarq.removeAttribute('data-ratib-marquee-suppress-click');
                return;
            }

            if (!lb.hidden) {
                if (ev.target.closest('[data-ratib-program-lightbox-prev]')) {
                    ev.preventDefault();
                    openLbAt(lbIndex - 1);
                    return;
                }
                if (ev.target.closest('[data-ratib-program-lightbox-next]')) {
                    ev.preventDefault();
                    openLbAt(lbIndex + 1);
                    return;
                }
            }

            var btn = ev.target.closest('[data-ratib-program-open]');
            if (!btn) {
                return;
            }
            ev.preventDefault();
            openLbAt(indexOfProgramSlide(btn));
        });

        document.addEventListener('keydown', function (ev) {
            if (lb.hidden) {
                return;
            }
            if (ev.key === 'Escape') {
                closeLb();
                return;
            }
            if (slides.length <= 1) {
                return;
            }
            if (ev.key === 'ArrowLeft') {
                ev.preventDefault();
                openLbAt(lbIndex - 1);
            } else if (ev.key === 'ArrowRight') {
                ev.preventDefault();
                openLbAt(lbIndex + 1);
            }
        });
    }

    try {
        initProgramStripMarqueeAndLightbox();
    } catch (eProg) {
        if (typeof console !== 'undefined' && console.error) {
            console.error('ratib program strip init failed', eProg);
        }
    }
})();

/** Phase 3: subtle live telemetry (timestamps, sync age, micro jitter) — illustrative only. */
(function ratibHomeLiveTelemetry() {
    var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduce) {
        return;
    }

    function rnd(min, max) {
        return min + Math.floor(Math.random() * (max - min + 1));
    }

    function tickSyncAge() {
        var m = rnd(1, 4);
        var txt = m + 'm';
        document.querySelectorAll('.ratib-live-sync-age').forEach(function (el) {
            el.textContent = txt;
        });
        document.querySelectorAll('.ratib-live-ping').forEach(function (el) {
            el.textContent = txt;
        });
    }

    function tickAgencyCounter() {
        var el = document.getElementById('ratib-topbar-nodes-counter');
        if (!el || !el.classList.contains('ratib-live-counter')) {
            return;
        }
        var base = parseInt(el.getAttribute('data-ratib-counter'), 10);
        if (!isFinite(base)) {
            return;
        }
        var n = base + rnd(-2, 2);
        if (n < 0) {
            n = 0;
        }
        el.textContent = String(n);
    }

    function tickIntJitter() {
        document.querySelectorAll('[data-ratib-jitter]').forEach(function (el) {
            var base = parseInt(el.getAttribute('data-ratib-jitter'), 10);
            if (!isFinite(base)) {
                return;
            }
            var n = base + rnd(-3, 3);
            el.textContent = n.toLocaleString();
        });
    }

    function tickPctJitter() {
        document.querySelectorAll('[data-ratib-jitter-pct]').forEach(function (el) {
            var base = parseFloat(el.getAttribute('data-ratib-jitter-pct'));
            if (!isFinite(base)) {
                return;
            }
            var v = base + (Math.random() * 0.12 - 0.06);
            if (v < 90) {
                v = 90;
            }
            if (v > 99.95) {
                v = 99.95;
            }
            el.textContent = v.toFixed(1) + '%';
        });
    }

    function tickEventClock() {
        var els = document.querySelectorAll('.ratib-live-clock');
        if (!els.length) {
            return;
        }
        function pad(x) {
            return x < 10 ? '0' + x : String(x);
        }
        function run() {
            var d = new Date();
            var txt = pad(d.getHours()) + ':' + pad(d.getMinutes()) + ':' + pad(d.getSeconds());
            var iso = '';
            try {
                iso = d.toISOString();
            } catch (e) {}
            els.forEach(function (el) {
                el.textContent = txt;
                if (iso) {
                    try {
                        el.setAttribute('datetime', iso);
                    } catch (e2) {}
                }
            });
        }
        run();
        setInterval(run, 1000);
    }

    tickSyncAge();
    tickAgencyCounter();
    tickIntJitter();
    tickPctJitter();
    tickEventClock();

    setInterval(tickSyncAge, 48000 + rnd(0, 12000));
    setInterval(tickAgencyCounter, 62000 + rnd(0, 8000));
    setInterval(tickIntJitter, 44000 + rnd(0, 9000));
    setInterval(tickPctJitter, 56000 + rnd(0, 11000));
})();

/** Profile nav — never use /pages/profile (404); always site root /profile */
(function ratibAboutNavInject() {
    function profileUrl() {
        var o = window.location.origin || '';
        return o ? o + '/profile/#company-profile' : '/profile/#company-profile';
    }

    function onProfilePage() {
        return (
            document.body &&
            (document.body.classList.contains('ratib-about-page') ||
                document.body.getAttribute('data-ratib-about') === '1')
        );
    }

    function fixProfileNav() {
        var PROFILE = profileUrl();
        document
            .querySelectorAll(
                '.ratib-nav__brand-profile, .ratib-nav__link--about, [data-ratib-profile-nav], .ratib-footer-link--about'
            )
            .forEach(function (a) {
                a.setAttribute('href', PROFILE);
                a.setAttribute('data-ratib-profile-nav', '1');
                if (!onProfilePage()) {
                    a.setAttribute('target', '_blank');
                    a.setAttribute('rel', 'noopener noreferrer');
                }
            });
        document.querySelectorAll('a.ratib-mega-nav__card').forEach(function (card) {
            var t = card.querySelector('.ratib-mega-nav__card-title');
            if (t && /company profile/i.test(t.textContent || '')) {
                card.setAttribute('href', PROFILE);
                if (!onProfilePage()) {
                    card.setAttribute('target', '_blank');
                    card.setAttribute('rel', 'noopener noreferrer');
                }
            }
        });
    }

    function schedule() {
        fixProfileNav();
        setTimeout(fixProfileNav, 0);
        setTimeout(fixProfileNav, 200);
        setTimeout(fixProfileNav, 900);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', schedule);
    } else {
        schedule();
    }
})();

