/**
 * Public home page: registration panel, plan/year UI, payment summary.
 * Config from #ratib-home-bootstrap (JSON) set in home.php.
 * EN: Handles user interactions only; business/pricing values are injected from PHP bootstrap JSON.
 * AR: هذا الملف يدير تفاعلات الواجهة فقط؛ قيم التسعير والمنطق الأساسية يتم تمريرها من PHP عبر JSON.
 */
(function () {
    'use strict';

    // EN: Parse bootstrap JSON generated by PHP and normalize defaults.
    // AR: قراءة JSON القادم من PHP وتوحيد القيم الافتراضية.
    function parseBootstrap() {
        var d = {
            checkoutCurrency: 'SAR',
            usdToSar: 3.75,
            openRegister: false,
            initialPlan: 'pro',
            initialAmount: null,
            initialYears: 1,
            goldYear1: 550,
            goldYear2: 1000,
            platinumYear1: 600,
            platinumYear2: 1100
        };
        var el = document.getElementById('ratib-home-bootstrap');
        if (!el || !el.textContent) {
            return d;
        }
        try {
            var o = JSON.parse(el.textContent);
            if (o && typeof o === 'object') {
                if (typeof o.checkoutCurrency === 'string') {
                    d.checkoutCurrency = o.checkoutCurrency;
                }
                if (typeof o.usdToSar === 'number' && isFinite(o.usdToSar) && o.usdToSar > 0) {
                    d.usdToSar = o.usdToSar;
                }
                if (typeof o.openRegister === 'boolean') {
                    d.openRegister = o.openRegister;
                }
                if (typeof o.initialPlan === 'string') {
                    d.initialPlan = o.initialPlan;
                }
                if (o.initialAmount === null || typeof o.initialAmount === 'number') {
                    d.initialAmount = o.initialAmount;
                }
                if (typeof o.initialYears === 'number') {
                    d.initialYears = o.initialYears;
                }
                if (typeof o.goldYear1 === 'number') {
                    d.goldYear1 = o.goldYear1;
                }
                if (typeof o.goldYear2 === 'number') {
                    d.goldYear2 = o.goldYear2;
                }
                if (typeof o.platinumYear1 === 'number') {
                    d.platinumYear1 = o.platinumYear1;
                }
                if (typeof o.platinumYear2 === 'number') {
                    d.platinumYear2 = o.platinumYear2;
                }
            }
        } catch (err) {
            console.error('ratib-home-bootstrap parse error', err);
        }
        return d;
    }

    var HOME = parseBootstrap();
    window.RATIB_CHECKOUT_CURRENCY = HOME.checkoutCurrency;
    window.RATIB_USD_TO_SAR = HOME.usdToSar;
    var openRegister = HOME.openRegister;

    // EN: Opens registration section and synchronizes hidden pricing fields.
    // AR: فتح قسم التسجيل وتحديث حقول الخطة/السعر المخفية.
    function showRegistrationForm(plan, amount, years) {
        var registerSection = document.getElementById('register');
        if (registerSection) {
            var successMsg = document.getElementById('successMsg');
            var successText = document.getElementById('successText');
            var phpSuccessMsg = document.getElementById('phpSuccessMsg');
            var form = document.getElementById('regForm');

            if (successMsg) {
                successMsg.style.display = 'none';
            }
            if (successText) {
                successText.innerHTML = '';
            }
            if (phpSuccessMsg) {
                phpSuccessMsg.style.display = 'none';
            }

            if (form) {
                form.style.display = 'block';
            }

            if (form) {
                form.reset();
            }

            if (window.history && window.history.replaceState) {
                var url = new URL(window.location.href);
                window.history.replaceState({}, '', url.toString());
            }

            registerSection.style.display = 'flex';
            var inputPlan = document.getElementById('inputPlan');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');
            var paymentBlockWrap = document.getElementById('paymentBlockWrap');
            var btnSubmit = document.getElementById('btnSubmit');
            if (inputPlan) {
                inputPlan.value = plan;
            }
            if (inputPlanAmount) {
                inputPlanAmount.value = amount || '';
            }
            if (inputYears) {
                inputYears.value = years || 1;
            }
            amount = parseFloat(amount) || 0;
            years = parseInt(years, 10) || 1;
            if (paymentBlockWrap) {
                paymentBlockWrap.style.display = amount > 0 ? 'block' : 'none';
            }
            if (btnSubmit) {
                btnSubmit.style.display = 'block';
            }
            if (amount > 0 && typeof updatePaymentSummary === 'function') {
                updatePaymentSummary(amount, years, plan);
            }
            registerSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }
    window.showRegistrationForm = showRegistrationForm;

    // EN: Debounce-like guard to avoid duplicate summary DOM writes.
    // AR: آلية حماية لتقليل التحديثات المتكررة في ملخص الدفع.
    var lastPaymentSummaryUpdate = { subtotal: 0, years: 0, planKey: '', timestamp: 0 };

    // EN: Render pricing summary block (subtotal, tax, total, currency note).
    // AR: إنشاء وعرض ملخص الدفع (المبلغ، الضريبة، الإجمالي، وملاحظة العملة).
    function updatePaymentSummary(subtotal, years, planKeyOpt) {
        var summaryEl = document.querySelector('.payment-summary-box') ||
            document.querySelector('#paymentBlockWrap .payment-summary-box') ||
            document.querySelector('.register-section .form-card .payment-summary-box') ||
            document.querySelector('#paymentSummary');

        if (!summaryEl) {
            console.log('ERROR: Payment summary element not found! subtotal:', subtotal);
            console.log('Tried selectors: .payment-summary-box, #paymentBlockWrap .payment-summary-box');
            return;
        }

        years = parseInt(years, 10) || 1;
        var inputPlanEl = document.getElementById('inputPlan');
        var planValue = (planKeyOpt != null && String(planKeyOpt).trim() !== '')
            ? String(planKeyOpt).trim().toLowerCase()
            : (inputPlanEl ? (inputPlanEl.value || inputPlanEl.getAttribute('value') || '').trim().toLowerCase() : '');

        var planLabel = 'Gold';
        if (planValue === 'platinum') {
            planLabel = 'Platinum';
        } else if (planValue === 'pro') {
            planLabel = 'Pro';
        } else if (planValue === 'gold') {
            planLabel = 'Gold';
        } else {
            var activeGoldBtn = document.querySelector('.plan-btn-form[data-plan="gold"]');
            var activePlatinumBtn = document.querySelector('.plan-btn-form[data-plan="platinum"]');
            var goldStyle = activeGoldBtn ? (activeGoldBtn.getAttribute('style') || '') : '';
            var platinumStyle = activePlatinumBtn ? (activePlatinumBtn.getAttribute('style') || '') : '';
            var goldActive = goldStyle.indexOf('rgba(212,175,55') !== -1 || goldStyle.indexOf('#d4af37') !== -1;
            var platinumActive = platinumStyle.indexOf('rgba(241,196,15') !== -1 || platinumStyle.indexOf('#f1c40f') !== -1;
            if (platinumActive && !goldActive) {
                planLabel = 'Platinum';
            } else if (goldActive && !platinumActive) {
                planLabel = 'Gold';
            }
        }

        var now = Date.now();
        if (lastPaymentSummaryUpdate.subtotal === subtotal && lastPaymentSummaryUpdate.years === years &&
            lastPaymentSummaryUpdate.planKey === planValue && (now - lastPaymentSummaryUpdate.timestamp) < 100) {
            console.log('Skipping duplicate updatePaymentSummary call for subtotal:', subtotal);
            return;
        }
        lastPaymentSummaryUpdate = { subtotal: subtotal, years: years, planKey: planValue, timestamp: now };

        var tax = subtotal * 0.15;
        var total = subtotal + tax;
        var checkoutCur = (typeof window.RATIB_CHECKOUT_CURRENCY === 'string' && window.RATIB_CHECKOUT_CURRENCY)
            ? String(window.RATIB_CHECKOUT_CURRENCY).toUpperCase() : 'SAR';
        var usdToSar = (typeof window.RATIB_USD_TO_SAR === 'number' && isFinite(window.RATIB_USD_TO_SAR) && window.RATIB_USD_TO_SAR > 0)
            ? window.RATIB_USD_TO_SAR : 3.75;
        var ngeniusNote = '';
        if (checkoutCur === 'SAR') {
            var sarApprox = (total * usdToSar).toFixed(2);
            var rateStr = usdToSar.toFixed(2);
            ngeniusNote = '<p class="small mb-0 mt-2 ratib-ngenius-currency-note" style="color:#95a5a6;line-height:1.45;font-size:0.85rem;border-top:1px solid rgba(255,255,255,0.06);padding-top:0.65rem;">Card checkout (N-Genius KSA) is charged in <strong>SAR</strong>. Approximate total: <strong style="color:#bdc3c7;">SAR ' + sarApprox + '</strong> <span style="opacity:0.85;">(USD × ' + rateStr + ')</span>.</p>';
        } else if (checkoutCur === 'USD') {
            ngeniusNote = '<p class="small mb-0 mt-2 ratib-ngenius-currency-note" style="color:#95a5a6;line-height:1.45;font-size:0.85rem;border-top:1px solid rgba(255,255,255,0.06);padding-top:0.65rem;">Card checkout is in <strong>USD</strong> (no currency conversion).</p>';
        }

        console.log('updatePaymentSummary - subtotal:', subtotal, 'years:', years, 'planLabel:', planLabel, 'inputPlan.value:', inputPlanEl ? inputPlanEl.value : '');

        summaryEl.innerHTML = '<h4 style="font-size: 1rem; margin-bottom: 0.75rem; color: #f1c40f;"><i class="fas fa-receipt me-2"></i>Payment Summary</h4>' +
            '<div style="display: flex; justify-content: space-between; padding: 0.5rem 0; border-bottom: 1px solid rgba(255,255,255,0.1);">' +
            '<span style="color: #aaa;">' + planLabel + ' Plan (' + years + ' year' + (years > 1 ? 's' : '') + ')</span>' +
            '<span style="color: #fff; font-weight: 600;">$' + subtotal.toFixed(2) + '</span>' +
            '</div>' +
            '<div style="display: flex; justify-content: space-between; padding: 0.5rem 0; border-bottom: 1px solid rgba(255,255,255,0.1);">' +
            '<span style="color: #aaa;">Tax (15%)</span>' +
            '<span style="color: #fff; font-weight: 600;">$' + tax.toFixed(2) + '</span>' +
            '</div>' +
            '<div style="display: flex; justify-content: space-between; padding: 0.75rem 0 0.5rem 0; font-size: 1.1rem; font-weight: 700; color: #f1c40f;">' +
            '<span>Total</span>' +
            '<span>$' + total.toFixed(2) + '</span>' +
            '</div>' + ngeniusNote;
    }

    // EN: Form state manager for plan/year buttons and hidden inputs.
    // AR: إدارة حالة النموذج وربط أزرار الخطة/المدة بالحقول المخفية.
    (function () {
        var form = document.getElementById('regForm');
        if (!form) {
            return;
        }

        document.getElementById('countrySelect').addEventListener('change', function () {
            var wrap = document.getElementById('otherCountryWrap');
            wrap.style.display = (this.value === 'Other countries sending workers') ? 'block' : 'none';
            if (wrap.style.display === 'none') {
                document.getElementById('countryOther').value = '';
            }
        });
        var inputPlan = document.getElementById('inputPlan');
        var inputPlanAmount = document.getElementById('inputPlanAmount');
        var inputYears = document.getElementById('inputYears');
        var paymentBlockWrap = document.getElementById('paymentBlockWrap');
        var btnSubmit = document.getElementById('btnSubmit');
        var formYearButtonsWrap = document.getElementById('formYearButtonsWrap');
        var formYearButtons = document.querySelectorAll('.form-year-btn');
        var planBtns = document.querySelectorAll('.plan-btn-form');
        var activePlanStyle = {
            gold: 'border-color: rgba(212,175,55,0.8); background: rgba(212,175,55,0.2); color: #d4af37;',
            platinum: 'border-color: rgba(241,196,15,0.8); background: rgba(241,196,15,0.2); color: #f1c40f;',
            pro: 'border-color: rgba(93,173,226,0.6); background: rgba(93,173,226,0.15); color: #5dade2;'
        };
        var inactiveStyle = 'border: 2px solid rgba(255,255,255,0.3); background: rgba(255,255,255,0.05); color: #aaa;';
        function setFormPlan(planVal, amount, years) {
            planVal = planVal || '';
            if (inputPlan) {
                inputPlan.value = planVal;
                inputPlan.setAttribute('value', planVal);
            }
            if (inputPlanAmount) {
                inputPlanAmount.value = amount || '';
                inputPlanAmount.setAttribute('value', amount || '');
            }
            if (inputYears) {
                inputYears.value = years || 1;
                inputYears.setAttribute('value', years || 1);
            }
            amount = parseFloat(amount) || 0;
            years = parseInt(years, 10) || 1;

            console.log('setFormPlan called - planVal:', planVal, 'amount:', amount, 'years:', years);

            if (formYearButtonsWrap) {
                formYearButtonsWrap.style.display = (planVal === 'gold' || planVal === 'platinum') ? 'block' : 'none';
            }
            if (paymentBlockWrap) {
                paymentBlockWrap.style.display = amount > 0 ? 'block' : 'none';
                console.log('paymentBlockWrap display set to:', amount > 0 ? 'block' : 'none', 'for amount:', amount);
            }
            var placeholder = document.getElementById('paymentBlockPlaceholder');
            if (placeholder) {
                placeholder.style.display = amount > 0 ? 'none' : 'block';
            }
            if (btnSubmit) {
                btnSubmit.style.display = 'block';
            }
            planBtns.forEach(function (b) {
                var p = b.getAttribute('data-plan');
                b.setAttribute('style', (p === planVal ? (activePlanStyle[p] || inactiveStyle) : inactiveStyle) + ' padding: 0.5rem 1rem; border-radius: 8px; font-weight: 600; cursor: pointer; transition: all 0.2s;');
            });
            if (planVal === 'gold' || planVal === 'platinum') {
                if (inputPlan && inputPlan.value !== planVal) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                formYearButtons.forEach(function (b) {
                    var y = parseInt(b.getAttribute('data-years'), 10) || 1;
                    var price = planVal === 'gold' ? parseFloat(b.getAttribute('data-price-gold')) : parseFloat(b.getAttribute('data-price-platinum'));
                    var span = b.querySelector('.form-year-price');
                    if (span) {
                        if (price >= 1000) {
                            span.textContent = '$' + price.toLocaleString();
                        } else if (price % 1 === 0) {
                            span.textContent = '$' + price.toFixed(0);
                        } else {
                            span.textContent = '$' + price.toFixed(1);
                        }
                    }
                    var isActive = (y === years);
                    if (planVal === 'gold') {
                        b.style.border = isActive ? '2px solid rgba(212,175,55,0.8)' : '2px solid rgba(255,255,255,0.2)';
                        b.style.background = isActive ? 'rgba(212,175,55,0.2)' : 'rgba(255,255,255,0.05)';
                        b.style.color = isActive ? '#d4af37' : '#aaa';
                    } else {
                        b.style.border = isActive ? '2px solid rgba(241,196,15,0.8)' : '2px solid rgba(255,255,255,0.2)';
                        b.style.background = isActive ? 'rgba(241,196,15,0.2)' : 'rgba(255,255,255,0.05)';
                        b.style.color = isActive ? '#f1c40f' : '#aaa';
                    }
                });
            }
            if (amount > 0 && typeof updatePaymentSummary === 'function') {
                if (inputPlan) {
                    inputPlan.value = planVal || 'gold';
                    inputPlan.setAttribute('value', planVal || 'gold');
                }
                if (paymentBlockWrap) {
                    paymentBlockWrap.style.display = 'block';
                }
                console.log('Calling updatePaymentSummary with amount:', amount, 'planVal:', planVal);
                updatePaymentSummary(amount, years, planVal);
            } else {
                console.log('NOT calling updatePaymentSummary - amount:', amount, 'function exists:', typeof updatePaymentSummary === 'function');
            }
        }
        var initialPlan = HOME.initialPlan;
        var initialAmount = HOME.initialAmount;
        var initialYears = HOME.initialYears;
        var defaultAmount = null;
        if (initialPlan === 'gold') {
            defaultAmount = HOME.goldYear1;
        } else if (initialPlan === 'platinum') {
            defaultAmount = HOME.platinumYear1;
        }
        if (inputPlan && initialPlan) {
            inputPlan.value = initialPlan;
            inputPlan.setAttribute('value', initialPlan);
        }
        setFormPlan(initialPlan, initialAmount !== null ? initialAmount : defaultAmount, initialYears);
        if (openRegister) {
            var rs = document.getElementById('register');
            if (rs) {
                rs.style.display = 'flex';
                rs.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        }
        planBtns.forEach(function (b) {
            b.addEventListener('click', function () {
                var planVal = this.getAttribute('data-plan');
                var amt = this.getAttribute('data-amount');
                var y = parseInt(this.getAttribute('data-years'), 10) || 1;

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                if (planVal === 'gold' || planVal === 'platinum') {
                    amt = parseFloat(amt) || 0;

                    if (!amt || amt === 0) {
                        var firstYearBtn = document.querySelector('.form-year-btn[data-years="1"]');
                        if (firstYearBtn) {
                            var price = planVal === 'gold' ? parseFloat(firstYearBtn.getAttribute('data-price-gold')) : parseFloat(firstYearBtn.getAttribute('data-price-platinum'));
                            amt = price || (planVal === 'gold' ? HOME.goldYear1 : HOME.platinumYear1);
                        } else {
                            amt = planVal === 'gold' ? HOME.goldYear1 : HOME.platinumYear1;
                        }
                    }
                    y = 1;
                }

                console.log('Plan button clicked - planVal:', planVal, 'amt:', amt, 'y:', y);

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                    inputPlan.dispatchEvent(new Event('change', { bubbles: true }));
                }

                setFormPlan(planVal, amt, y);
            });
        });
        formYearButtons.forEach(function (b) {
            b.addEventListener('click', function () {
                var planVal = inputPlan ? (inputPlan.value || 'gold') : 'gold';
                planVal = planVal.trim().toLowerCase();

                if (planVal !== 'gold' && planVal !== 'platinum') {
                    var activeGoldBtn = document.querySelector('.plan-btn-form[data-plan="gold"]');
                    var activePlatinumBtn = document.querySelector('.plan-btn-form[data-plan="platinum"]');
                    var goldStyle = activeGoldBtn ? (activeGoldBtn.getAttribute('style') || '') : '';
                    var platinumStyle = activePlatinumBtn ? (activePlatinumBtn.getAttribute('style') || '') : '';

                    if (goldStyle.indexOf('rgba(212,175,55') !== -1 || goldStyle.indexOf('#d4af37') !== -1) {
                        planVal = 'gold';
                    } else if (platinumStyle.indexOf('rgba(241,196,15') !== -1 || platinumStyle.indexOf('#f1c40f') !== -1) {
                        planVal = 'platinum';
                    }
                }

                var y = parseInt(this.getAttribute('data-years'), 10) || 1;
                var price = planVal === 'gold' ? parseFloat(this.getAttribute('data-price-gold')) : parseFloat(this.getAttribute('data-price-platinum'));

                if (inputPlan) {
                    inputPlan.value = planVal;
                    inputPlan.setAttribute('value', planVal);
                }

                setFormPlan(planVal, price, y);
            });
        });
    })();

    // EN: Price card interactions (top pricing cards) and year toggles.
    // AR: تفاعلات بطاقات الأسعار العلوية وتبديل مدة الاشتراك.
    (function () {
        var goldPrices = { 1: HOME.goldYear1, 2: HOME.goldYear2 };
        var platinumPrices = { 1: HOME.platinumYear1, 2: HOME.platinumYear2 };
        var goldOldPrices = { 1: 1100, 2: 2000 };
        var platinumOldPrices = { 1: 1200, 2: 2200 };

        function updateGoldPrice(years, event) {
            years = parseInt(years, 10) || 1;
            var price = goldPrices[years] || HOME.goldYear1;
            var oldPrice = goldOldPrices[years] || 1100;
            var priceEl = document.getElementById('goldPrice');
            var oldPriceEl = document.getElementById('goldOldPrice');
            var btn = document.getElementById('goldRegisterBtn');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');

            if (priceEl) {
                priceEl.innerHTML = '$' + price.toLocaleString() + ' <span id="goldPriceLabel">for ' + years + ' year' + (years > 1 ? 's' : '') + '</span>';
            }
            if (oldPriceEl) {
                oldPriceEl.textContent = '$' + oldPrice.toLocaleString();
            }
            if (btn) {
                btn.setAttribute('data-register-plan', 'gold');
                btn.setAttribute('data-register-amount', String(price));
                btn.setAttribute('data-register-years', String(years));
            }

            if (event && event.type === 'click') {
                if (inputPlanAmount) {
                    inputPlanAmount.value = price;
                }
                if (inputYears) {
                    inputYears.value = years;
                }
                var inputPlanEl = document.getElementById('inputPlan');
                if (inputPlanEl) {
                    inputPlanEl.value = 'gold';
                    inputPlanEl.setAttribute('value', 'gold');
                }
                var registerSection = document.getElementById('register');
                if (registerSection && registerSection.style.display !== 'none') {
                    setTimeout(function () {
                        updatePaymentSummary(price, years, 'gold');
                    }, 10);
                }
            }

            document.querySelectorAll('.gold-year-btn').forEach(function (b) {
                var btnYears = parseInt(b.getAttribute('data-years'), 10) || 0;
                if (btnYears === years) {
                    b.classList.add('active');
                    b.style.background = 'rgba(212,175,55,0.2)';
                    b.style.borderColor = '#d4af37';
                    b.style.color = '#d4af37';
                } else {
                    b.classList.remove('active');
                    b.style.background = 'rgba(255,255,255,0.05)';
                    b.style.borderColor = 'rgba(255,255,255,0.2)';
                    b.style.color = '#aaa';
                }
            });
        }

        function updatePlatinumPrice(years, event) {
            years = parseInt(years, 10) || 1;
            var price = platinumPrices[years] || HOME.platinumYear1;
            var oldPrice = platinumOldPrices[years] || 1200;
            var priceEl = document.getElementById('platinumPrice');
            var oldPriceEl = document.getElementById('platinumOldPrice');
            var btn = document.getElementById('platinumRegisterBtn');
            var inputPlanAmount = document.getElementById('inputPlanAmount');
            var inputYears = document.getElementById('inputYears');

            if (priceEl) {
                priceEl.innerHTML = '$' + price.toLocaleString() + ' <span id="platinumPriceLabel">for ' + years + ' year' + (years > 1 ? 's' : '') + '</span>';
            }
            if (oldPriceEl) {
                oldPriceEl.textContent = '$' + oldPrice.toLocaleString();
            }
            if (btn) {
                btn.setAttribute('data-register-plan', 'platinum');
                btn.setAttribute('data-register-amount', String(price));
                btn.setAttribute('data-register-years', String(years));
            }

            if (event && event.type === 'click') {
                if (inputPlanAmount) {
                    inputPlanAmount.value = price;
                }
                if (inputYears) {
                    inputYears.value = years;
                }
                var inputPlanEl = document.getElementById('inputPlan');
                if (inputPlanEl) {
                    inputPlanEl.value = 'platinum';
                    inputPlanEl.setAttribute('value', 'platinum');
                }
                var registerSection = document.getElementById('register');
                if (registerSection && registerSection.style.display !== 'none' && typeof updatePaymentSummary === 'function') {
                    setTimeout(function () {
                        updatePaymentSummary(price, years, 'platinum');
                    }, 10);
                }
            }

            document.querySelectorAll('.platinum-year-btn').forEach(function (b) {
                var btnYears = parseInt(b.getAttribute('data-years'), 10) || 0;
                if (btnYears === years) {
                    b.classList.add('active');
                    b.style.background = 'rgba(241,196,15,0.2)';
                    b.style.borderColor = '#f1c40f';
                    b.style.color = '#f1c40f';
                } else {
                    b.classList.remove('active');
                    b.style.background = 'rgba(255,255,255,0.05)';
                    b.style.borderColor = 'rgba(255,255,255,0.2)';
                    b.style.color = '#aaa';
                }
            });
        }

        document.querySelectorAll('.gold-year-btn').forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                var y = parseInt(this.getAttribute('data-years'), 10) || 1;
                updateGoldPrice(y, e);
            });
        });

        document.querySelectorAll('.platinum-year-btn').forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                var y = parseInt(this.getAttribute('data-years'), 10) || 1;
                updatePlatinumPrice(y, e);
            });
        });
    })();

    // EN: Delegated click handlers for register anchors.
    // AR: معالجات نقر عامة لروابط التسجيل.
    document.addEventListener('click', function (e) {
        var scrollA = e.target.closest('a.js-scroll-register');
        if (scrollA && scrollA.getAttribute('href') === '#register') {
            e.preventDefault();
            var registerSection = document.getElementById('register');
            if (registerSection) {
                registerSection.style.display = 'flex';
                registerSection.scrollIntoView({ behavior: 'smooth' });
            }
            return;
        }
        var openA = e.target.closest('a.js-open-register');
        if (openA) {
            e.preventDefault();
            var plan = openA.getAttribute('data-register-plan') || 'gold';
            var amount = parseFloat(openA.getAttribute('data-register-amount') || '0') || 0;
            var yrs = parseInt(openA.getAttribute('data-register-years') || '1', 10) || 1;
            showRegistrationForm(plan, amount, yrs);
        }
    });
})();
