<?php
declare(strict_types=1);

namespace Ratib\InfrastructureMarketplace\Provisioning;

use Ratib\InfrastructureMarketplace\Domain\TenantContext;

/**
 * Queue unit for infra workflows (id generated by dispatcher/persistence layer).
 */
final class ProvisioningJob
{
    /**
     * @param list<string> $steps Ordered logical steps, e.g. ['registrar','dns','ssl','hosting']
     * @param array<string, ProvisioningPayload> $payloadByStep
     */
    public function __construct(
        private readonly TenantContext $tenant,
        private readonly array $steps,
        private readonly array $payloadByStep,
        private readonly ?string $correlationId = null
    ) {}

    public function tenant(): TenantContext
    {
        return $this->tenant;
    }

    /**
     * @return list<string>
     */
    public function steps(): array
    {
        return $this->steps;
    }

    /**
     * @return array<string, ProvisioningPayload>
     */
    public function payloadByStep(): array
    {
        return $this->payloadByStep;
    }

    public function correlationId(): ?string
    {
        return $this->correlationId;
    }
}
