<?php
/**
 * EN: Handles user-facing page rendering and page-level server flow in `pages/forgot-password.php`.
 * AR: يدير عرض صفحات المستخدم وتدفق الخادم الخاص بالصفحة في `pages/forgot-password.php`.
 */
require_once '../includes/config.php';
$error = '';
$success = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $input = trim($_POST['email_or_username'] ?? '');
    if ($input) {
        $stmt = $conn->prepare("SELECT user_id, email FROM users WHERE (username = ? OR email = ?) AND status = 'active' LIMIT 1");
        $stmt->bind_param("ss", $input, $input);
        $stmt->execute();
        $result = $stmt->get_result();
        if ($result->num_rows === 1) {
            $user = $result->fetch_assoc();
            // Generate token
            $token = bin2hex(random_bytes(32));
            $expires = date('Y-m-d H:i:s', strtotime('+1 hour'));
            // Store in password_resets
            $stmt2 = $conn->prepare("INSERT INTO password_resets (user_id, token, expires_at) VALUES (?, ?, ?)");
            $stmt2->bind_param("iss", $user['user_id'], $token, $expires);
            if ($stmt2->execute()) {
                $resetLink = SITE_URL . "/pages/reset-password.php?token=" . $token;
                $success = "Password reset link generated. <br><a href='$resetLink' class='text-primary'>Reset Password</a> (Demo: In production, this would be emailed.)";
            } else {
                $error = 'Failed to generate reset link. Please try again.';
            }
        } else {
            $success = 'If this account exists, a password reset link has been sent.';
        }
    } else {
        $error = 'Please enter your email or username.';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password - Ratibprogram</title>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    
    <!-- Login Page CSS -->
    <link rel="stylesheet" href="<?php echo htmlspecialchars(asset('css/login.css')); ?>">
    <?php require_once __DIR__ . '/../includes/chat-widget-standalone-head.php'; ?>
</head>
<body>
    <!-- Dark Mode Toggle -->
    <button class="dark-mode-toggle" id="dark-mode-toggle" aria-label="Toggle dark mode">
        <i class="fas fa-moon" id="theme-icon"></i>
    </button>
    
    <div class="hyperdimensional-container">
        <!-- Animated Background -->
        <div class="animated-background" id="animated-background">
            <!-- Text will be dynamically generated by JavaScript -->
        </div>
        
        <div class="portal-content active">
            <h2>Forgot Password</h2>
            <?php if ($error): ?>
                <div class="error-message"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>
            <?php if ($success): ?>
                <div class="success-message"><?php echo $success; ?></div>
                <div class="mt-3 text-center">
                    <a href="login.php" class="link-primary">Back to Login</a>
                </div>
            <?php else: ?>
            <form method="POST" action="" class="text-center">
                <div class="quantum-input">
                    <i class="fas fa-envelope"></i>
                    <input type="text" name="email_or_username" placeholder="Email or Username" required autofocus>
                </div>
                <button type="submit" class="btn btn-primary w-100">Send Reset Link</button>
            </form>
            <div class="mt-3 text-center">
                <a href="login.php" class="link-primary">Back to Login</a>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <?php
    $chatWidgetPlaceholder = 'Forgot password? Ask here or: I need to talk to support';
    require_once __DIR__ . '/../includes/chat-widget-standalone-body.php';
    ?>

    <!-- Login Page JavaScript -->
    <script src="<?php echo htmlspecialchars(asset('js/login.js')); ?>"></script>
</body>
</html>
 