<?php
/**
 * EN: Handles user-facing page rendering and page-level server flow in `pages/reset-password.php`.
 * AR: يدير عرض صفحات المستخدم وتدفق الخادم الخاص بالصفحة في `pages/reset-password.php`.
 */
require_once '../includes/config.php';
$error = '';
$success = '';
$token = $_GET['token'] ?? '';
if (!$token) {
    $error = 'Invalid or missing token.';
} else {
    // Look up token
    $stmt = $conn->prepare("SELECT pr.*, u.user_id FROM password_resets pr JOIN users u ON pr.user_id = u.user_id WHERE pr.token = ? AND pr.expires_at > NOW() AND pr.used = 0 LIMIT 1");
    $stmt->bind_param("s", $token);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($result->num_rows !== 1) {
        $error = 'Invalid or expired reset link.';
    } else {
        $reset = $result->fetch_assoc();
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $new = $_POST['new_password'] ?? '';
            $confirm = $_POST['confirm_password'] ?? '';
            if (!$new || !$confirm) {
                $error = 'Please fill in both fields.';
            } elseif ($new !== $confirm) {
                $error = 'Passwords do not match.';
            } elseif (strlen($new) < 6) {
                $error = 'Password must be at least 6 characters.';
            } else {
                $hashed = password_hash($new, PASSWORD_DEFAULT);
                // Update user password
                $stmt2 = $conn->prepare("UPDATE users SET password = ? WHERE user_id = ?");
                $stmt2->bind_param("si", $hashed, $reset['user_id']);
                if ($stmt2->execute()) {
                    // Mark token as used
                    $stmt3 = $conn->prepare("UPDATE password_resets SET used = 1 WHERE id = ?");
                    $stmt3->bind_param("i", $reset['id']);
                    $stmt3->execute();
                    $success = 'Your password has been reset! You can now <a href="login.php">login</a>.';
                } else {
                    $error = 'Failed to update password. Please try again.';
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password - Ratibprogram</title>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    
    <!-- Login Page CSS -->
    <link rel="stylesheet" href="<?php echo htmlspecialchars(asset('css/login.css')); ?>">
    <?php require_once __DIR__ . '/../includes/chat-widget-standalone-head.php'; ?>
</head>
<body>
    <!-- Dark Mode Toggle -->
    <button class="dark-mode-toggle" id="dark-mode-toggle" aria-label="Toggle dark mode">
        <i class="fas fa-moon" id="theme-icon"></i>
    </button>
    
    <div class="hyperdimensional-container">
        <!-- Animated Background -->
        <div class="animated-background" id="animated-background">
            <!-- Text will be dynamically generated by JavaScript -->
        </div>
        
        <div class="portal-content active">
            <h2>Reset Password</h2>
            <?php if ($error): ?>
                <div class="error-message"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>
            <?php if ($success): ?>
                <div class="success-message"><?php echo $success; ?></div>
            <?php elseif (!$error): ?>
            <form method="POST" action="" class="text-center">
                <div class="quantum-input">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="new_password" placeholder="New Password" required>
                </div>
                <div class="quantum-input">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="confirm_password" placeholder="Confirm Password" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">Reset Password</button>
            </form>
            <?php endif; ?>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <?php
    $chatWidgetPlaceholder = 'Reset password help? Ask here or: I need to talk to support';
    require_once __DIR__ . '/../includes/chat-widget-standalone-body.php';
    ?>

    <!-- Login Page JavaScript -->
    <script src="<?php echo htmlspecialchars(asset('js/login.js')); ?>"></script>
</body>
</html>
 