<?php
declare(strict_types=1);

/** code => [name_en, name_ar] */
return [
    '1000' => ['Assets', 'الأصول'],
    '1100' => ['Cash on Hand', 'النقدية / الصندوق'],
    '1150' => ['Bank Accounts', 'الحسابات البنكية'],
    '1200' => ['Accounts Receivable', 'ذمم مدينة'],
    '1210' => ['VAT Recoverable', 'ضريبة قابلة للاسترداد'],
    '1220' => ['Advances to Suppliers', 'سلف موردين'],
    '1300' => ['Inventory', 'المخزون'],
    '1400' => ['Prepaid Expenses', 'مصروفات مقدمة'],
    '1500' => ['Fixed Assets', 'الأصول الثابتة'],
    '1510' => ['Equipment', 'معدات'],
    '1520' => ['Vehicles', 'مركبات'],
    '1530' => ['Buildings', 'مباني'],
    '1590' => ['Accumulated Depreciation', 'مجمع الإهلاك'],
    '2000' => ['Liabilities', 'الخصوم'],
    '2100' => ['Accounts Payable', 'ذمم دائنة'],
    '2110' => ['Customer Advances', 'دفعات مقدمة من العملاء'],
    '2200' => ['VAT Payable', 'ضريبة مستحقة'],
    '2300' => ['Accrued Expenses', 'مصروفات مستحقة'],
    '2400' => ['Salaries Payable', 'رواتب مستحقة'],
    '2500' => ['Short-term Loans', 'قروض قصيرة الأجل'],
    '3000' => ['Equity', 'حقوق الملكية'],
    '3100' => ['Retained Earnings', 'أرباح محتجزة'],
    '3200' => ['Share Capital', 'رأس المال'],
    '3300' => ['Current Year Profit/Loss', 'أرباح/خسائر العام الحالي'],
    '4000' => ['Revenue', 'الإيرادات'],
    '4100' => ['Sales Revenue', 'إيرادات المبيعات'],
    '4200' => ['Service Revenue', 'إيرادات الخدمات'],
    '4300' => ['Other Income', 'إيرادات أخرى'],
    '4900' => ['Sales Returns & Allowances', 'مردودات ومسموحات المبيعات'],
    '5000' => ['Expenses', 'المصروفات'],
    '5100' => ['Procurement Expense', 'مصروفات المشتريات'],
    '5200' => ['Cost of Goods Sold', 'تكلفة البضاعة المباعة'],
    '5300' => ['Salaries & Wages', 'الرواتب والأجور'],
    '5400' => ['Rent Expense', 'مصروف الإيجار'],
    '5500' => ['Utilities', 'مرافق (كهرباء، ماء، …)'],
    '5600' => ['Depreciation Expense', 'مصروف الإهلاك'],
    '5700' => ['Bank & Finance Charges', 'عمولات بنكية ومالية'],
    '5800' => ['General & Administrative', 'مصروفات عمومية وإدارية'],
    '5900' => ['Marketing & Sales', 'مصروفات تسويق ومبيعات'],
];
