<?php
declare(strict_types=1);

/**
 * Server-authoritative Module Add-on Commerce catalog (platform-controlled).
 *
 * Prices are NOT derived from HTTP input. A zero/empty price is not purchasable.
 * Commercial amounts stay unset until configured (fail closed).
 *
 * `enabled` must be true for a slug to be sold. Runtime access is still
 * company.modules → PlanLimitService::companyHasModule() → CompanyModuleMiddleware.
 *
 * Tenants cannot change these values. Overlay on admin.rateb.sa may enable
 * preview prices without changing this production file. Platform Super Admin
 * may store per-database overrides in rateb_system_settings.
 *
 * @return array<string, array<string, mixed>>
 */
return [
    'crm' => [
        'name' => 'CRM',
        'name_ar' => 'إدارة علاقات العملاء',
        'description' => 'Manage customers, opportunities and sales from one powerful workspace.',
        'description_ar' => 'أدر العملاء والفرص والمبيعات من مساحة عمل واحدة.',
        'icon' => 'crm',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 10,
        'promo_label' => '',
        'features' => [
            ['en' => 'Customer management', 'ar' => 'إدارة العملاء'],
            ['en' => 'Leads & opportunities', 'ar' => 'العملاء المحتملون والفرص'],
            ['en' => 'Sales pipeline', 'ar' => 'مسار المبيعات'],
            ['en' => 'Follow-ups & activity', 'ar' => 'المتابعات والأنشطة'],
            ['en' => 'Reports & analytics', 'ar' => 'التقارير والتحليلات'],
        ],
    ],
    'pos' => [
        'name' => 'POS',
        'name_ar' => 'نقاط البيع',
        'description' => 'In-store selling, receipts, and register operations.',
        'description_ar' => 'البيع في المتجر والإيصالات وتشغيل الصندوق.',
        'icon' => 'pos',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 20,
        'features' => [
            ['en' => 'Register sales', 'ar' => 'مبيعات الصندوق'],
            ['en' => 'Receipts', 'ar' => 'الإيصالات'],
            ['en' => 'Shifts & cash drawer', 'ar' => 'الورديات والصندوق'],
            ['en' => 'Returns', 'ar' => 'المرتجعات'],
        ],
    ],
    'hr' => [
        'name' => 'HR',
        'name_ar' => 'الموارد البشرية',
        'description' => 'Employees, attendance, leave, and people operations.',
        'description_ar' => 'الموظفون والحضور والإجازات وعمليات الموارد البشرية.',
        'icon' => 'hr',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 30,
        'features' => [
            ['en' => 'Employee records', 'ar' => 'ملفات الموظفين'],
            ['en' => 'Attendance', 'ar' => 'الحضور'],
            ['en' => 'Leave', 'ar' => 'الإجازات'],
            ['en' => 'HR workflows', 'ar' => 'مسارات الموارد البشرية'],
        ],
    ],
    'recruitment' => [
        'name' => 'Recruitment',
        'name_ar' => 'التوظيف',
        'description' => 'Jobs, candidates, interviews, and hiring pipeline.',
        'description_ar' => 'الوظائف والمرشحون والمقابلات ومسار التوظيف.',
        'icon' => 'recruitment',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 40,
        'features' => [
            ['en' => 'Job openings', 'ar' => 'الوظائف الشاغرة'],
            ['en' => 'Candidates', 'ar' => 'المرشحون'],
            ['en' => 'Interviews', 'ar' => 'المقابلات'],
            ['en' => 'Hiring pipeline', 'ar' => 'مسار التوظيف'],
        ],
    ],
    'logistics' => [
        'name' => 'Logistics',
        'name_ar' => 'اللوجستيات',
        'description' => 'Shipments, tracking, and delivery operations.',
        'description_ar' => 'الشحنات والتتبع وعمليات التوصيل.',
        'icon' => 'logistics',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 50,
        'features' => [
            ['en' => 'Shipments', 'ar' => 'الشحنات'],
            ['en' => 'Tracking', 'ar' => 'التتبع'],
            ['en' => 'Delivery status', 'ar' => 'حالة التوصيل'],
            ['en' => 'Logistics reports', 'ar' => 'تقارير اللوجستيات'],
        ],
    ],
    'marketplace' => [
        'name' => 'Marketplace',
        'name_ar' => 'السوق',
        'description' => 'Multi-vendor catalog, orders, and marketplace operations.',
        'description_ar' => 'كتالوج متعدد البائعين والطلبات وتشغيل السوق.',
        'icon' => 'marketplace',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 60,
        'features' => [
            ['en' => 'Vendor catalog', 'ar' => 'كتالوج البائعين'],
            ['en' => 'Marketplace orders', 'ar' => 'طلبات السوق'],
            ['en' => 'Listings', 'ar' => 'العروض'],
            ['en' => 'Settlement views', 'ar' => 'التسويات'],
        ],
    ],
    'manufacturing' => [
        'name' => 'Manufacturing',
        'name_ar' => 'التصنيع',
        'description' => 'Work orders, bills of materials, and production tracking.',
        'description_ar' => 'أوامر العمل وقوائم المواد وتتبع الإنتاج.',
        'icon' => 'manufacturing',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 70,
        'features' => [
            ['en' => 'Work orders', 'ar' => 'أوامر العمل'],
            ['en' => 'Bills of materials', 'ar' => 'قوائم المواد'],
            ['en' => 'Production tracking', 'ar' => 'تتبع الإنتاج'],
            ['en' => 'Manufacturing reports', 'ar' => 'تقارير التصنيع'],
        ],
    ],
    'payroll' => [
        'name' => 'Payroll',
        'name_ar' => 'الرواتب',
        'description' => 'Salary runs, deductions, and payroll documents.',
        'description_ar' => 'مسيرات الرواتب والاستقطاعات ومستندات الأجور.',
        'icon' => 'payroll',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 80,
        'features' => [
            ['en' => 'Salary runs', 'ar' => 'مسيرات الرواتب'],
            ['en' => 'Deductions', 'ar' => 'الاستقطاعات'],
            ['en' => 'Payroll documents', 'ar' => 'مستندات الرواتب'],
            ['en' => 'Payroll reports', 'ar' => 'تقارير الرواتب'],
        ],
    ],
    'accounting' => [
        'name' => 'Accounting',
        'name_ar' => 'المحاسبة',
        'description' => 'Ledgers, journals, and financial reporting.',
        'description_ar' => 'الدفاتر والقيود والتقارير المالية.',
        'icon' => 'accounting',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 90,
        'features' => [
            ['en' => 'General ledger', 'ar' => 'دفتر الأستاذ'],
            ['en' => 'Journal entries', 'ar' => 'القيود اليومية'],
            ['en' => 'Financial reports', 'ar' => 'التقارير المالية'],
            ['en' => 'Chart of accounts', 'ar' => 'دليل الحسابات'],
        ],
    ],
    'projects' => [
        'name' => 'Projects',
        'name_ar' => 'المشاريع',
        'description' => 'Project planning, tasks, and delivery tracking.',
        'description_ar' => 'تخطيط المشاريع والمهام وتتبع التسليم.',
        'icon' => 'projects',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 100,
        'features' => [
            ['en' => 'Project workspace', 'ar' => 'مساحة المشروع'],
            ['en' => 'Tasks', 'ar' => 'المهام'],
            ['en' => 'Milestones', 'ar' => 'المراحل'],
            ['en' => 'Project reports', 'ar' => 'تقارير المشاريع'],
        ],
    ],
    'quality' => [
        'name' => 'Quality',
        'name_ar' => 'الجودة',
        'description' => 'Quality records, inspections, and non-conformance follow-up.',
        'description_ar' => 'سجلات الجودة والفحوصات ومتابعة حالات عدم المطابقة.',
        'icon' => 'quality',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 110,
        'features' => [
            ['en' => 'Inspections', 'ar' => 'الفحوصات'],
            ['en' => 'Quality records', 'ar' => 'سجلات الجودة'],
            ['en' => 'Non-conformance', 'ar' => 'عدم المطابقة'],
            ['en' => 'Quality reports', 'ar' => 'تقارير الجودة'],
        ],
    ],
    'bi' => [
        'name' => 'BI',
        'name_ar' => 'ذكاء الأعمال',
        'description' => 'Dashboards, KPIs, and business intelligence views.',
        'description_ar' => 'لوحات المعلومات والمؤشرات وعروض ذكاء الأعمال.',
        'icon' => 'bi',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 120,
        'features' => [
            ['en' => 'Dashboards', 'ar' => 'لوحات المعلومات'],
            ['en' => 'KPIs', 'ar' => 'المؤشرات'],
            ['en' => 'Analytical views', 'ar' => 'العروض التحليلية'],
            ['en' => 'Exports', 'ar' => 'التصدير'],
        ],
    ],
    'website' => [
        'name' => 'Website',
        'name_ar' => 'الموقع',
        'description' => 'Company website, CMS pages, and public content.',
        'description_ar' => 'موقع الشركة وصفحات المحتوى والمحتوى العام.',
        'icon' => 'website',
        'monthly' => 0.0,
        'yearly' => 0.0,
        'enabled' => false,
        'featured' => false,
        'sort_order' => 130,
        'features' => [
            ['en' => 'CMS pages', 'ar' => 'صفحات المحتوى'],
            ['en' => 'Public content', 'ar' => 'المحتوى العام'],
            ['en' => 'Leads capture', 'ar' => 'التقاط العملاء المحتملين'],
            ['en' => 'Site settings', 'ar' => 'إعدادات الموقع'],
        ],
    ],
];
