<?php
declare(strict_types=1);

/**
 * Canonical SaaS plan tiers — limits, pricing, and module bundles.
 * Synced to rateb_plans via migration 241 + MigrationService::syncPlanTiersFromConfig().
 *
 * Ladder (6 packages):
 * launch → starter → commerce → professional → enterprise → ultimate
 */
return [
    'launch' => [
        'name' => 'Launch',
        'description' => 'Start with the control panel, alerts, and essential reporting',
        'price_monthly' => 990.00,
        'price_yearly' => 10900.00,
        'max_users' => 3,
        'max_branches' => 1,
        'max_storage_mb' => 256,
        'modules' => [
            'dashboard',
            'notifications',
            'profile',
            'reports',
        ],
    ],
    'starter' => [
        'name' => 'Starter',
        'description' => 'Core purchasing operations for clinics and small establishments',
        'price_monthly' => 1500.00,
        'price_yearly' => 16000.00,
        'max_users' => 8,
        'max_branches' => 3,
        'max_storage_mb' => 512,
        'modules' => [
            'dashboard',
            'notifications',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
        ],
    ],
    'commerce' => [
        'name' => 'Commerce',
        'description' => 'Sell, stock, and deliver with POS, logistics, and marketplace',
        'price_monthly' => 1990.00,
        'price_yearly' => 21900.00,
        'max_users' => 20,
        'max_branches' => 5,
        'max_storage_mb' => 2048,
        'modules' => [
            'dashboard',
            'notifications',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
            'pos',
            'logistics',
            'marketplace',
            'branches',
        ],
    ],
    'professional' => [
        'name' => 'Professional',
        'description' => 'Grow with HR, CRM, projects, accounting, and approvals',
        'price_monthly' => 2490.00,
        'price_yearly' => 26900.00,
        'max_users' => 50,
        'max_branches' => 10,
        'max_storage_mb' => 5120,
        'modules' => [
            'dashboard',
            'notifications',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
            'pos',
            'logistics',
            'marketplace',
            'branches',
            'hr',
            'recruitment',
            'crm',
            'projects',
            'approval',
            'accounting',
            'assets',
            'contracts',
            'documents',
            'workflows',
        ],
    ],
    'enterprise' => [
        'name' => 'Enterprise',
        'description' => 'Industrial depth: manufacturing, payroll, quality, BI, and website',
        'price_monthly' => 3490.00,
        'price_yearly' => 37900.00,
        'max_users' => 150,
        'max_branches' => 25,
        'max_storage_mb' => 15360,
        'modules' => [
            'dashboard',
            'notifications',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
            'pos',
            'logistics',
            'marketplace',
            'branches',
            'hr',
            'recruitment',
            'crm',
            'projects',
            'approval',
            'accounting',
            'assets',
            'contracts',
            'documents',
            'workflows',
            'manufacturing',
            'payroll',
            'quality',
            'bi',
            'website',
            'tenders',
            'medical_devices',
        ],
    ],
    'ultimate' => [
        'name' => 'Ultimate',
        'description' => 'Full Rateb ERP platform with governance and access control',
        'price_monthly' => 4990.00,
        'price_yearly' => 53900.00,
        'max_users' => 500,
        'max_branches' => 100,
        'max_storage_mb' => 51200,
        'modules' => [
            'dashboard',
            'procurement',
            'inventory',
            'suppliers',
            'assets',
            'contracts',
            'tenders',
            'reports',
            'medical_devices',
            'accounting',
            'documents',
            'workflows',
            'notifications',
            'access_control',
            'profile',
            'hr',
            'branches',
            'pos',
            'recruitment',
            'crm',
            'projects',
            'approval',
            'manufacturing',
            'payroll',
            'quality',
            'bi',
            'website',
            'logistics',
            'marketplace',
        ],
    ],
];
