<?php
declare(strict_types=1);

/**
 * Canonical SaaS plan tiers — limits, pricing, and module bundles.
 * Synced to rateb_plans via migration 243 + MigrationService::syncPlanTiersFromConfig().
 *
 * Pricing strategy (Saudi market 2026):
 * - Positioned under common cloud ERP/accounting list prices
 *   (Plugin Soft ~46–246 SAR/mo, Daftra 75–159, Qoyod ~48–192, Rewaa ~287+).
 * - Annual billing = 9 × monthly (3 months free).
 *
 * Ladder: launch → starter → commerce → professional → enterprise → ultimate
 */
return [
    'free_months_yearly' => 3,
    /** Highlighted on /site/pricing and default checkout selection. */
    'recommended_slug' => 'professional',

    'launch' => [
        'name' => 'انطلاق',
        'description' => 'ابدأ بلوحة التحكم والإشعارات والتقارير الأساسية.',
        'price_monthly' => 39.00,
        'price_yearly' => 351.00, // 9 months (3 free)
        'max_users' => 3,
        'max_branches' => 1,
        'max_storage_mb' => 256,
        'modules' => [
            'dashboard',
            'notifications',
            'access_control',
            'profile',
            'reports',
        ],
    ],
    'starter' => [
        'name' => 'أساسي',
        'description' => 'تشغيل المشتريات والمخزون والموردين للمنشآت الصغيرة.',
        'price_monthly' => 69.00,
        'price_yearly' => 621.00,
        'max_users' => 8,
        'max_branches' => 3,
        'max_storage_mb' => 512,
        'modules' => [
            'dashboard',
            'notifications',
            'access_control',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
        ],
    ],
    'commerce' => [
        'name' => 'تجاري',
        'description' => 'البيع والتوزيع عبر نقطة البيع واللوجستيات وسوق الخدمات.',
        'price_monthly' => 99.00,
        'price_yearly' => 891.00,
        'max_users' => 20,
        'max_branches' => 5,
        'max_storage_mb' => 2048,
        'modules' => [
            'dashboard',
            'notifications',
            'access_control',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
            'pos',
            'logistics',
            'marketplace',
            'branches',
        ],
    ],
    'professional' => [
        'name' => 'احترافي',
        'description' => 'نمو إداري مع الموارد البشرية وCRM والمشاريع والحسابات.',
        'price_monthly' => 129.00,
        'price_yearly' => 1161.00,
        'max_users' => 50,
        'max_branches' => 10,
        'max_storage_mb' => 5120,
        'modules' => [
            'dashboard',
            'notifications',
            'access_control',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
            'pos',
            'logistics',
            'marketplace',
            'branches',
            'hr',
            'recruitment',
            'crm',
            'projects',
            'approval',
            'accounting',
            'assets',
            'contracts',
            'documents',
            'workflows',
        ],
    ],
    'enterprise' => [
        'name' => 'مؤسسات',
        'description' => 'عمق مؤسسي: التصنيع والرواتب والجودة وذكاء الأعمال.',
        'price_monthly' => 179.00,
        'price_yearly' => 1611.00,
        'max_users' => 150,
        'max_branches' => 25,
        'max_storage_mb' => 15360,
        'modules' => [
            'dashboard',
            'notifications',
            'access_control',
            'profile',
            'reports',
            'procurement',
            'inventory',
            'suppliers',
            'pos',
            'logistics',
            'marketplace',
            'branches',
            'hr',
            'recruitment',
            'crm',
            'projects',
            'approval',
            'accounting',
            'assets',
            'contracts',
            'documents',
            'workflows',
            'manufacturing',
            'payroll',
            'quality',
            'bi',
            'website',
            'tenders',
            'medical_devices',
        ],
    ],
    'ultimate' => [
        'name' => 'متكامل',
        'description' => 'منصة رتب ERP كاملة مع الحوكمة والتحكم بالوصول.',
        'price_monthly' => 249.00,
        'price_yearly' => 2241.00,
        'max_users' => 500,
        'max_branches' => 100,
        'max_storage_mb' => 51200,
        'modules' => [
            'dashboard',
            'procurement',
            'inventory',
            'suppliers',
            'assets',
            'contracts',
            'tenders',
            'reports',
            'medical_devices',
            'accounting',
            'documents',
            'workflows',
            'notifications',
            'access_control',
            'profile',
            'hr',
            'branches',
            'pos',
            'recruitment',
            'crm',
            'projects',
            'approval',
            'manufacturing',
            'payroll',
            'quality',
            'bi',
            'website',
            'logistics',
            'marketplace',
        ],
    ],
];
