<?php

declare(strict_types=1);

/**
 * Entity → API route mapping for offline replay (Phase 5).
 * Inventory + HR + Procurement drafts delegate to existing domain services.
 */
return [
    'offline_ack' => [
        'module' => 'offline_meta',
        'method' => 'POST',
        'path' => null,
        'replay' => 'noop',
    ],
    'pos_checkout' => [
        'module' => 'pos',
        'method' => 'POST',
        'path' => '/api/v1/pos/register/checkout',
        'replay' => 'delegate_pos',
    ],
    'inventory_stock_movement' => [
        'module' => 'inventory',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_inventory',
        'action' => 'stock_movement.create',
    ],
    'inventory_stock_count' => [
        'module' => 'inventory',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_inventory',
        'action' => 'stock_count.create',
    ],
    'inventory_warehouse_transfer' => [
        'module' => 'inventory',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_inventory',
        'action' => 'warehouse_transfer.create',
    ],
    'inventory_catalog' => [
        'module' => 'inventory',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/inventory_catalog',
        'replay' => 'delta_pull',
    ],
    'hr_attendance' => [
        'module' => 'hr',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_hr',
        'action' => 'attendance.create',
    ],
    'hr_attendance_bulk' => [
        'module' => 'hr',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_hr',
        'action' => 'attendance.bulk',
    ],
    'hr_leave_draft' => [
        'module' => 'hr',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_hr',
        'action' => 'leave_request.draft',
    ],
    'employee_directory' => [
        'module' => 'hr',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/employee_directory',
        'replay' => 'delta_pull',
    ],
    'procurement_purchase_request_draft' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'purchase_request.draft',
    ],
    'procurement_rfq_draft' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'rfq.draft',
    ],
    'procurement_purchase_order_draft' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'purchase_order.draft',
    ],
    'procurement_goods_receipt' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'goods_receipt.receive',
        // Doc mapping only: transaction_id→client_id, entity→purchase_order, operation→receive
    ],
    'supplier_directory' => [
        'module' => 'procurement',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/supplier_directory',
        'replay' => 'delta_pull',
    ],
    'recruitment_candidate_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'candidate.create',
    ],
    'recruitment_candidate_update' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'candidate.update',
    ],
    'recruitment_workflow_transition' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'workflow.transition',
    ],
    'recruitment_assignment_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'assignment.create',
    ],
    'recruitment_interview_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'interview.create',
    ],
    'recruitment_visa_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'visa.create',
    ],
    'recruitment_medical_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'medical.create',
    ],
    'recruitment_passport_update' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'passport.update',
    ],
    'recruitment_contract_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'contract.create',
    ],
    'recruitment_note_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'note.create',
    ],
    'recruitment_agency_directory' => [
        'module' => 'recruitment',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/recruitment_agency_directory',
        'replay' => 'delta_pull',
    ],
    'recruitment_skill_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/recruitment_skill_directory',
        'replay' => 'delta_pull',
    ],
    'recruitment_language_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/recruitment_language_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_journal_create' => [
        'module' => 'accounting',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_accounting',
        'action' => 'journal.create',
    ],
    'accounting_journal_update' => [
        'module' => 'accounting',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_accounting',
        'action' => 'journal.update',
    ],
    'accounting_workflow_transition' => [
        'module' => 'accounting',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_accounting',
        'action' => 'workflow.transition',
    ],
    'accounting_recurring_create' => [
        'module' => 'accounting',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_accounting',
        'action' => 'recurring.create',
    ],
    'accounting_opening_balance_create' => [
        'module' => 'accounting',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_accounting',
        'action' => 'opening_balance.create',
    ],
    'accounting_note_create' => [
        'module' => 'accounting',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_accounting',
        'action' => 'note.create',
    ],
    'chart_of_accounts_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/chart_of_accounts_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_currency_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/accounting_currency_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_exchange_rate_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/accounting_exchange_rate_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_tax_code_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/accounting_tax_code_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_cost_center_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/accounting_cost_center_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_profit_center_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/accounting_profit_center_directory',
        'replay' => 'delta_pull',
    ],
    'accounting_fiscal_period_directory' => [
        'module' => 'accounting',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/accounting_fiscal_period_directory',
        'replay' => 'delta_pull',
    ],
    'crm_lead_create' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'lead.create',
    ],
    'crm_lead_update' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'lead.update',
    ],
    'crm_workflow_transition' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'workflow.transition',
    ],
    'crm_opportunity_create' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'opportunity.create',
    ],
    'crm_meeting_create' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'meeting.create',
    ],
    'crm_task_create' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'task.create',
    ],
    'crm_note_create' => [
        'module' => 'crm',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_crm',
        'action' => 'note.create',
    ],
    'crm_lead_source_directory' => [
        'module' => 'crm',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/crm_lead_source_directory',
        'replay' => 'delta_pull',
    ],
    'crm_pipeline_stage_directory' => [
        'module' => 'crm',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/crm_pipeline_stage_directory',
        'replay' => 'delta_pull',
    ],
    'crm_tag_directory' => [
        'module' => 'crm',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/crm_tag_directory',
        'replay' => 'delta_pull',
    ],
    'crm_company_directory' => [
        'module' => 'crm',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/crm_company_directory',
        'replay' => 'delta_pull',
    ],
    'projects_project_create' => [
        'module' => 'projects',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_projects',
        'action' => 'project.create',
    ],
    'projects_project_update' => [
        'module' => 'projects',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_projects',
        'action' => 'project.update',
    ],
    'projects_task_create' => [
        'module' => 'projects',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_projects',
        'action' => 'task.create',
    ],
    'projects_workflow_transition' => [
        'module' => 'projects',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_projects',
        'action' => 'workflow.transition',
    ],
    'projects_timesheet_create' => [
        'module' => 'projects',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_projects',
        'action' => 'timesheet.create',
    ],
    'project_tag_directory' => [
        'module' => 'projects',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/project_tag_directory',
        'replay' => 'delta_pull',
    ],
    'project_role_directory' => [
        'module' => 'projects',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/project_role_directory',
        'replay' => 'delta_pull',
    ],
    'task_status_directory' => [
        'module' => 'projects',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/task_status_directory',
        'replay' => 'delta_pull',
    ],
    'assets_asset_create' => [
        'module' => 'assets',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_assets',
    ],
    'assets_asset_update' => [
        'module' => 'assets',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_assets',
    ],
    'assets_workflow_transition' => [
        'module' => 'assets',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_assets',
    ],
    'assets_maintenance_request_create' => [
        'module' => 'assets',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_assets',
    ],
    'assets_work_order_create' => [
        'module' => 'assets',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_assets',
    ],
    'assets_inspection_create' => [
        'module' => 'assets',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_assets',
    ],
    'asset_category_directory' => [
        'module' => 'assets',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/asset_category_directory',
        'replay' => 'delta_pull',
    ],
    'asset_manufacturer_directory' => [
        'module' => 'assets',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/asset_manufacturer_directory',
        'replay' => 'delta_pull',
    ],
    'asset_location_directory' => [
        'module' => 'assets',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/asset_location_directory',
        'replay' => 'delta_pull',
    ],
    'asset_model_directory' => [
        'module' => 'assets',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/asset_model_directory',
        'replay' => 'delta_pull',
    ],
    'maintenance_plan_directory' => [
        'module' => 'assets',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/maintenance_plan_directory',
        'replay' => 'delta_pull',
    ],
    'approval_request_create' => [
        'module' => 'approval',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_approval',
    ],
    'approval_request_update' => [
        'module' => 'approval',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_approval',
    ],
    'approval_workflow_transition' => [
        'module' => 'approval',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_approval',
    ],
    'approval_comment_create' => [
        'module' => 'approval',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_approval',
    ],
    'approval_delegation_create' => [
        'module' => 'approval',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_approval',
    ],
    'approval_template_directory' => [
        'module' => 'approval',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/approval_template_directory',
        'replay' => 'delta_pull',
    ],
    'approval_chain_directory' => [
        'module' => 'approval',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/approval_chain_directory',
        'replay' => 'delta_pull',
    ],
    'approval_stage_directory' => [
        'module' => 'approval',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/approval_stage_directory',
        'replay' => 'delta_pull',
    ],
    'approval_rule_directory' => [
        'module' => 'approval',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/approval_rule_directory',
        'replay' => 'delta_pull',
    ],
    'approval_delegation_directory' => [
        'module' => 'approval',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/approval_delegation_directory',
        'replay' => 'delta_pull',
    ],
    'eproc_supplier_profile_create' => [
        'module' => 'procurement_enterprise',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_procurement_enterprise',
    ],
    'eproc_workflow_transition' => [
        'module' => 'procurement_enterprise',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_procurement_enterprise',
    ],
    'eproc_tender_create' => [
        'module' => 'procurement_enterprise',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_procurement_enterprise',
    ],
    'eproc_contract_create' => [
        'module' => 'procurement_enterprise',
        'method' => 'POST',
        'path' => '/api/v1/offline/queue',
        'replay' => 'delegate_procurement_enterprise',
    ],
    'eproc_supplier_category_directory' => [
        'module' => 'procurement_enterprise',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/eproc_supplier_category_directory',
        'replay' => 'delta_pull',
    ],
    'eproc_rfq_template_directory' => [
        'module' => 'procurement_enterprise',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/eproc_rfq_template_directory',
        'replay' => 'delta_pull',
    ],
    'eproc_tag_directory' => [
        'module' => 'procurement_enterprise',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/eproc_tag_directory',
        'replay' => 'delta_pull',
    ],
    'customer_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/customer_directory',
        'replay' => 'delta_pull',
    ],
    'branch_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/branch_directory',
        'replay' => 'delta_pull',
    ],
    'warehouse_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/warehouse_directory',
        'replay' => 'delta_pull',
    ],
];
