<?php

declare(strict_types=1);

/**
 * Entity → API route mapping for offline replay (Phase 5).
 * Inventory + HR + Procurement drafts delegate to existing domain services.
 */
return [
    'offline_ack' => [
        'module' => 'offline_meta',
        'method' => 'POST',
        'path' => null,
        'replay' => 'noop',
    ],
    'pos_checkout' => [
        'module' => 'pos',
        'method' => 'POST',
        'path' => '/api/v1/pos/register/checkout',
        'replay' => 'delegate_pos',
    ],
    'inventory_stock_movement' => [
        'module' => 'inventory',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_inventory',
        'action' => 'stock_movement.create',
    ],
    'inventory_stock_count' => [
        'module' => 'inventory',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_inventory',
        'action' => 'stock_count.create',
    ],
    'inventory_warehouse_transfer' => [
        'module' => 'inventory',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_inventory',
        'action' => 'warehouse_transfer.create',
    ],
    'inventory_catalog' => [
        'module' => 'inventory',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/inventory_catalog',
        'replay' => 'delta_pull',
    ],
    'hr_attendance' => [
        'module' => 'hr',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_hr',
        'action' => 'attendance.create',
    ],
    'hr_attendance_bulk' => [
        'module' => 'hr',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_hr',
        'action' => 'attendance.bulk',
    ],
    'hr_leave_draft' => [
        'module' => 'hr',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_hr',
        'action' => 'leave_request.draft',
    ],
    'employee_directory' => [
        'module' => 'hr',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/employee_directory',
        'replay' => 'delta_pull',
    ],
    'procurement_purchase_request_draft' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'purchase_request.draft',
    ],
    'procurement_rfq_draft' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'rfq.draft',
    ],
    'procurement_purchase_order_draft' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'purchase_order.draft',
    ],
    'procurement_goods_receipt' => [
        'module' => 'procurement',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_procurement',
        'action' => 'goods_receipt.receive',
        // Doc mapping only: transaction_id→client_id, entity→purchase_order, operation→receive
    ],
    'supplier_directory' => [
        'module' => 'procurement',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/supplier_directory',
        'replay' => 'delta_pull',
    ],
    'recruitment_candidate_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'candidate.create',
    ],
    'recruitment_candidate_update' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'candidate.update',
    ],
    'recruitment_workflow_transition' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'workflow.transition',
    ],
    'recruitment_assignment_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'assignment.create',
    ],
    'recruitment_interview_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'interview.create',
    ],
    'recruitment_visa_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'visa.create',
    ],
    'recruitment_medical_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'medical.create',
    ],
    'recruitment_passport_update' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'passport.update',
    ],
    'recruitment_contract_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'contract.create',
    ],
    'recruitment_note_create' => [
        'module' => 'recruitment',
        'method' => 'POST',
        'path' => null,
        'replay' => 'delegate_recruitment',
        'action' => 'note.create',
    ],
    'recruitment_agency_directory' => [
        'module' => 'recruitment',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/recruitment_agency_directory',
        'replay' => 'delta_pull',
    ],
    'recruitment_skill_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/recruitment_skill_directory',
        'replay' => 'delta_pull',
    ],
    'recruitment_language_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/recruitment_language_directory',
        'replay' => 'delta_pull',
    ],
    'customer_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/customer_directory',
        'replay' => 'delta_pull',
    ],
    'branch_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/branch_directory',
        'replay' => 'delta_pull',
    ],
    'warehouse_directory' => [
        'module' => 'platform',
        'method' => 'GET',
        'path' => '/api/v1/offline/delta/warehouse_directory',
        'replay' => 'delta_pull',
    ],
];
