<?php

declare(strict_types=1);

/**
 * Enterprise offline feature flags (Phase 2A + Phase 14 pilot).
 * Master default is OFF — no behavior change until explicitly enabled.
 */
return [
    'defaults' => [
        'offline.enabled' => false,
        'offline.pos.complete' => true,
        'offline.inventory.movements' => false,
        'offline.hr.attendance' => false,
        /** Phase 23B — Enterprise HRMS Tier-1 drafts (requires master). Additive to Phase 4 attendance. */
        'offline.hr' => false,
        'offline.hr.employee' => false,
        'offline.hr.training' => false,
        'offline.hr.performance' => false,
        'offline.hr.workflow' => false,
        'offline.hr.masterdata' => false,
        'offline.procurement' => false,
        /** Phase 14.2 — PO goods receipt (GRN) via ProcurementService::receiveOrder (requires procurement). */
        'offline.procurement.goods_receipt' => false,
        /** Phase 15B — Recruitment Tier-1 (requires master). */
        'offline.recruitment' => false,
        'offline.recruitment.candidates' => false,
        'offline.recruitment.workflow' => false,
        'offline.recruitment.assignment' => false,
        /** Phase 16B — Accounting Tier-1 drafts (requires master). */
        'offline.accounting' => false,
        'offline.accounting.journals' => false,
        'offline.accounting.workflow' => false,
        'offline.accounting.masterdata' => false,
        /** Phase 17B — CRM Tier-1 drafts (requires master). */
        'offline.crm' => false,
        'offline.crm.leads' => false,
        'offline.crm.workflow' => false,
        'offline.crm.activities' => false,
        'offline.crm.masterdata' => false,
        /** Phase 18B — Projects Tier-1 drafts (requires master). */
        'offline.projects' => false,
        'offline.projects.tasks' => false,
        'offline.projects.workflow' => false,
        'offline.projects.timesheets' => false,
        'offline.projects.masterdata' => false,
        'offline.assets' => false,
        'offline.assets.maintenance' => false,
        'offline.assets.workflow' => false,
        'offline.assets.inspections' => false,
        'offline.assets.masterdata' => false,
        'offline.approval' => false,
        'offline.approval.requests' => false,
        'offline.approval.workflow' => false,
        'offline.approval.masterdata' => false,
        'offline.procurement_enterprise' => false,
        'offline.procurement_enterprise.suppliers' => false,
        'offline.procurement_enterprise.tenders' => false,
        'offline.procurement_enterprise.contracts' => false,
        'offline.procurement_enterprise.workflow' => false,
        'offline.procurement_enterprise.masterdata' => false,
        'offline.manufacturing' => false,
        'offline.manufacturing.production' => false,
        'offline.manufacturing.workflow' => false,
        'offline.manufacturing.quality' => false,
        'offline.manufacturing.masterdata' => false,
        'offline.payroll' => false,
        'offline.payroll.employee' => false,
        'offline.payroll.batch' => false,
        'offline.payroll.workflow' => false,
        'offline.payroll.masterdata' => false,
        'offline.quality' => false,
        'offline.quality.inspections' => false,
        'offline.quality.audit' => false,
        'offline.quality.workflow' => false,
        'offline.quality.masterdata' => false,
        'offline.documents' => false,
        'offline.documents.repositories' => false,
        'offline.documents.workflow' => false,
        'offline.documents.masterdata' => false,
        'offline.bi' => false,
        'offline.bi.dashboards' => false,
        'offline.bi.reports' => false,
        'offline.bi.workflow' => false,
        'offline.bi.masterdata' => false,
        'offline.monitoring' => false,
        'offline.read_cache' => false,
        'offline.auth.unlock' => false,
        'offline.rbac.cache' => false,
        'offline.master_data' => false,
        /** Phase 14 — allowlisted ops page snapshots (requires master + read_cache). */
        'offline.pilot.ops_pages' => false,
    ],

    /** Env var overrides (string "1"/"true"/"yes" → true). */
    'env' => [
        'offline.enabled' => 'RATEB_OFFLINE_ENABLED',
        'offline.pos.complete' => 'RATEB_OFFLINE_POS_COMPLETE',
        'offline.inventory.movements' => 'RATEB_OFFLINE_INVENTORY_MOVEMENTS',
        'offline.hr.attendance' => 'RATEB_OFFLINE_HR_ATTENDANCE',
        'offline.hr' => 'RATEB_OFFLINE_HR',
        'offline.hr.employee' => 'RATEB_OFFLINE_HR_EMPLOYEE',
        'offline.hr.training' => 'RATEB_OFFLINE_HR_TRAINING',
        'offline.hr.performance' => 'RATEB_OFFLINE_HR_PERFORMANCE',
        'offline.hr.workflow' => 'RATEB_OFFLINE_HR_WORKFLOW',
        'offline.hr.masterdata' => 'RATEB_OFFLINE_HR_MASTERDATA',
        'offline.procurement' => 'RATEB_OFFLINE_PROCUREMENT',
        'offline.procurement.goods_receipt' => 'RATEB_OFFLINE_PROCUREMENT_GRN',
        'offline.recruitment' => 'RATEB_OFFLINE_RECRUITMENT',
        'offline.recruitment.candidates' => 'RATEB_OFFLINE_RECRUITMENT_CANDIDATES',
        'offline.recruitment.workflow' => 'RATEB_OFFLINE_RECRUITMENT_WORKFLOW',
        'offline.recruitment.assignment' => 'RATEB_OFFLINE_RECRUITMENT_ASSIGNMENT',
        'offline.accounting' => 'RATEB_OFFLINE_ACCOUNTING',
        'offline.accounting.journals' => 'RATEB_OFFLINE_ACCOUNTING_JOURNALS',
        'offline.accounting.workflow' => 'RATEB_OFFLINE_ACCOUNTING_WORKFLOW',
        'offline.accounting.masterdata' => 'RATEB_OFFLINE_ACCOUNTING_MASTERDATA',
        'offline.crm' => 'RATEB_OFFLINE_CRM',
        'offline.crm.leads' => 'RATEB_OFFLINE_CRM_LEADS',
        'offline.crm.workflow' => 'RATEB_OFFLINE_CRM_WORKFLOW',
        'offline.crm.activities' => 'RATEB_OFFLINE_CRM_ACTIVITIES',
        'offline.crm.masterdata' => 'RATEB_OFFLINE_CRM_MASTERDATA',
        'offline.projects' => 'RATEB_OFFLINE_PROJECTS',
        'offline.projects.tasks' => 'RATEB_OFFLINE_PROJECTS_TASKS',
        'offline.projects.workflow' => 'RATEB_OFFLINE_PROJECTS_WORKFLOW',
        'offline.projects.timesheets' => 'RATEB_OFFLINE_PROJECTS_TIMESHEETS',
        'offline.projects.masterdata' => 'RATEB_OFFLINE_PROJECTS_MASTERDATA',
        'offline.assets' => 'RATEB_OFFLINE_ASSETS',
        'offline.assets.maintenance' => 'RATEB_OFFLINE_ASSETS_MAINTENANCE',
        'offline.assets.workflow' => 'RATEB_OFFLINE_ASSETS_WORKFLOW',
        'offline.assets.inspections' => 'RATEB_OFFLINE_ASSETS_INSPECTIONS',
        'offline.assets.masterdata' => 'RATEB_OFFLINE_ASSETS_MASTERDATA',
        'offline.approval' => 'RATEB_OFFLINE_APPROVAL',
        'offline.approval.requests' => 'RATEB_OFFLINE_APPROVAL_REQUESTS',
        'offline.approval.workflow' => 'RATEB_OFFLINE_APPROVAL_WORKFLOW',
        'offline.approval.masterdata' => 'RATEB_OFFLINE_APPROVAL_MASTERDATA',
        'offline.procurement_enterprise' => 'RATEB_OFFLINE_PROCUREMENT_ENTERPRISE',
        'offline.procurement_enterprise.suppliers' => 'RATEB_OFFLINE_PROCUREMENT_ENTERPRISE_SUPPLIERS',
        'offline.procurement_enterprise.tenders' => 'RATEB_OFFLINE_PROCUREMENT_ENTERPRISE_TENDERS',
        'offline.procurement_enterprise.contracts' => 'RATEB_OFFLINE_PROCUREMENT_ENTERPRISE_CONTRACTS',
        'offline.procurement_enterprise.workflow' => 'RATEB_OFFLINE_PROCUREMENT_ENTERPRISE_WORKFLOW',
        'offline.procurement_enterprise.masterdata' => 'RATEB_OFFLINE_PROCUREMENT_ENTERPRISE_MASTERDATA',
        'offline.manufacturing' => 'RATEB_OFFLINE_MANUFACTURING',
        'offline.manufacturing.production' => 'RATEB_OFFLINE_MANUFACTURING_PRODUCTION',
        'offline.manufacturing.workflow' => 'RATEB_OFFLINE_MANUFACTURING_WORKFLOW',
        'offline.manufacturing.quality' => 'RATEB_OFFLINE_MANUFACTURING_QUALITY',
        'offline.manufacturing.masterdata' => 'RATEB_OFFLINE_MANUFACTURING_MASTERDATA',
        'offline.payroll' => 'RATEB_OFFLINE_PAYROLL',
        'offline.payroll.employee' => 'RATEB_OFFLINE_PAYROLL_EMPLOYEE',
        'offline.payroll.batch' => 'RATEB_OFFLINE_PAYROLL_BATCH',
        'offline.payroll.workflow' => 'RATEB_OFFLINE_PAYROLL_WORKFLOW',
        'offline.payroll.masterdata' => 'RATEB_OFFLINE_PAYROLL_MASTERDATA',
        'offline.quality' => 'RATEB_OFFLINE_QUALITY',
        'offline.quality.inspections' => 'RATEB_OFFLINE_QUALITY_INSPECTIONS',
        'offline.quality.audit' => 'RATEB_OFFLINE_QUALITY_AUDIT',
        'offline.quality.workflow' => 'RATEB_OFFLINE_QUALITY_WORKFLOW',
        'offline.quality.masterdata' => 'RATEB_OFFLINE_QUALITY_MASTERDATA',
        'offline.documents' => 'RATEB_OFFLINE_DOCUMENTS',
        'offline.documents.repositories' => 'RATEB_OFFLINE_DOCUMENTS_REPOSITORIES',
        'offline.documents.workflow' => 'RATEB_OFFLINE_DOCUMENTS_WORKFLOW',
        'offline.documents.masterdata' => 'RATEB_OFFLINE_DOCUMENTS_MASTERDATA',
        'offline.bi' => 'RATEB_OFFLINE_BI',
        'offline.bi.dashboards' => 'RATEB_OFFLINE_BI_DASHBOARDS',
        'offline.bi.reports' => 'RATEB_OFFLINE_BI_REPORTS',
        'offline.bi.workflow' => 'RATEB_OFFLINE_BI_WORKFLOW',
        'offline.bi.masterdata' => 'RATEB_OFFLINE_BI_MASTERDATA',
        'offline.monitoring' => 'RATEB_OFFLINE_MONITORING',
        'offline.read_cache' => 'RATEB_OFFLINE_READ_CACHE',
        'offline.auth.unlock' => 'RATEB_OFFLINE_AUTH_UNLOCK',
        'offline.rbac.cache' => 'RATEB_OFFLINE_RBAC_CACHE',
        'offline.master_data' => 'RATEB_OFFLINE_MASTER_DATA',
        'offline.pilot.ops_pages' => 'RATEB_OFFLINE_PILOT_OPS_PAGES',
    ],
];
