<?php

declare(strict_types=1);

/**
 * Module tier + operation classification registry (Phase 5).
 * Tier 1 adapters: Inventory, HR, Procurement (all flag-gated).
 */
return [
    'tiers' => [
        'T0' => ['pos'],
        'T1' => ['inventory', 'hr', 'procurement', 'recruitment', 'accounting', 'crm', 'projects', 'assets'],
        'T2' => ['erp_shell'],
        'T3' => ['platform'],
    ],

    /** Phase 11: + platform. Phase 15B: + recruitment. Phase 16B: + accounting. Phase 17B: + crm. Phase 18B: + projects. Phase 19B: + assets. */
    'active_modules' => ['offline_meta', 'pos', 'inventory', 'hr', 'procurement', 'recruitment', 'accounting', 'crm', 'projects', 'assets', 'erp_shell', 'platform'],

    'operations' => [
        'offline.ping' => ['class' => 'OC', 'module' => 'offline_meta'],
        'offline.ack' => ['class' => 'RS', 'module' => 'offline_meta'],
        'offline.shell.ping' => ['class' => 'OC', 'module' => 'erp_shell'],
        'offline.auth.unlock' => ['class' => 'OC', 'module' => 'platform'],
        'offline.rbac.cache' => ['class' => 'OC', 'module' => 'platform'],
        'offline.master_data' => ['class' => 'OC', 'module' => 'platform'],
        'pos.checkout' => ['class' => 'RS', 'module' => 'pos'],
        'pos.process_return' => ['class' => 'RS', 'module' => 'pos'],
        'pos.process_exchange' => ['class' => 'RS', 'module' => 'pos'],
        'inventory.stock_movement' => ['class' => 'RS', 'module' => 'inventory'],
        'inventory.stock_count' => ['class' => 'RS', 'module' => 'inventory'],
        'inventory.warehouse_transfer' => ['class' => 'RS', 'module' => 'inventory'],
        'hr.attendance' => ['class' => 'RS', 'module' => 'hr'],
        'hr.attendance.bulk' => ['class' => 'RS', 'module' => 'hr'],
        'hr.leave_draft' => ['class' => 'RS', 'module' => 'hr'],
        'procurement.purchase_request.draft' => ['class' => 'RS', 'module' => 'procurement'],
        'procurement.rfq.draft' => ['class' => 'RS', 'module' => 'procurement'],
        'procurement.purchase_order.draft' => ['class' => 'RS', 'module' => 'procurement'],
        'procurement.goods_receipt.receive' => ['class' => 'RS', 'module' => 'procurement'],
        'recruitment.candidate.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.candidate.update' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.workflow.transition' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.assignment.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.interview.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.visa.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.medical.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.passport.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.passport.update' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.contract.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'recruitment.note.create' => ['class' => 'RS', 'module' => 'recruitment'],
        'accounting.journal.create' => ['class' => 'RS', 'module' => 'accounting'],
        'accounting.journal.update' => ['class' => 'RS', 'module' => 'accounting'],
        'accounting.workflow.transition' => ['class' => 'RS', 'module' => 'accounting'],
        'accounting.recurring.create' => ['class' => 'RS', 'module' => 'accounting'],
        'accounting.opening_balance.create' => ['class' => 'RS', 'module' => 'accounting'],
        'accounting.note.create' => ['class' => 'RS', 'module' => 'accounting'],
        'crm.lead.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.lead.update' => ['class' => 'RS', 'module' => 'crm'],
        'crm.workflow.transition' => ['class' => 'RS', 'module' => 'crm'],
        'crm.opportunity.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.meeting.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.call.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.task.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.note.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.assignment.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.campaign.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.contact.create' => ['class' => 'RS', 'module' => 'crm'],
        'crm.company.create' => ['class' => 'RS', 'module' => 'crm'],
        'projects.project.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.project.update' => ['class' => 'RS', 'module' => 'projects'],
        'projects.task.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.task.update' => ['class' => 'RS', 'module' => 'projects'],
        'projects.workflow.transition' => ['class' => 'RS', 'module' => 'projects'],
        'projects.milestone.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.phase.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.comment.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.assignment.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.timesheet.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.issue.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.risk.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.budget.create' => ['class' => 'RS', 'module' => 'projects'],
        'projects.activity.create' => ['class' => 'RS', 'module' => 'projects'],
        'assets.asset.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.asset.update' => ['class' => 'RS', 'module' => 'assets'],
        'assets.workflow.transition' => ['class' => 'RS', 'module' => 'assets'],
        'assets.assignment.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.transfer.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.maintenance_request.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.maintenance_plan.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.work_order.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.inspection.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.checklist.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.meter_reading.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.comment.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.activity.create' => ['class' => 'RS', 'module' => 'assets'],
        'assets.note.create' => ['class' => 'RS', 'module' => 'assets'],
    ],
];
