<?php

declare(strict_types=1);

/**
 * Phase 14 — Allowlisted enterprise daily-ops pages for offline snapshot browse.
 * Paths are logical keys (matched against location.pathname via short key OR
 * the canonical route from rateb_app_route()). Never assume /admin/ops/ for all.
 * Generated JSON (`ops-page-allowlist.json`) includes `routes` map from rateb_app_route().
 * Payroll / payments intentionally omitted from default browse (Approval Tier-1 added in Phase 20B).
 * Phase 16B: journal draft browse + form hooks only (no post/reverse/close).
 * Phase 20B: approvals browse + draft form hooks (no final decisions / escalate / notifications).
 *
 * @return array{
 *   paths: list<string>,
 *   form_hooks: list<array{match: string, module: string, action: string}>
 * }
 */
return [
    'paths' => [
        'stock-movements',
        'warehouse-transfers',
        'inventory-audits',
        'inventory',
        'warehouses',
        'hr/attendance',
        'hr/leaves',
        'purchase-requests',
        'purchase-orders',
        'rfq',
        'suppliers',
        'goods-receipts',
        'recruitment/candidates',
        'recruitment/agencies',
        'recruitment',
        'journal-entries',
        'accounting/platform',
        'accounting/currencies',
        'accounting/tax-codes',
        'accounting/profit-centers',
        'accounting/recurring',
        'accounting/opening-balances',
        'crm',
        'crm/leads',
        'crm/pipeline',
        'crm/tasks',
        'crm/meetings',
        'crm/campaigns',
        'crm/contacts',
        'crm/companies',
        'projects',
        'projects/list',
        'projects/tasks',
        'projects/tasks/kanban',
        'projects/tasks/gantt',
        'projects/tasks/calendar',
        'projects/milestones',
        'projects/issues',
        'projects/risks',
        'projects/timesheets',
        'eam',
        'eam/assets',
        'eam/maintenance',
        'eam/work-orders',
        'eam/requests',
        'eam/calendar',
        'eam/assignments',
        'eam/inspections',
        'eam/timeline',
        'eam/reports',
        'approvals',
        'approvals/requests',
        'approvals/pending',
        'approvals/templates',
        'approvals/chains',
        'approvals/rules',
        'approvals/history',
        'approvals/reports',
        'access-control',
        'access-control/matrix',
        'eproc',
        'eproc/suppliers',
        'eproc/tenders',
        'eproc/contracts',
        'eproc/calendar',
        'eproc/spend',
        'eproc/portal',
        'eproc/reports',
        'eproc/qualification',
        'eproc/categories',
        'eproc/scorecards',
        'eproc/collaboration',
        'eproc/rfq-templates',
        'mfg',
        'mfg/boms',
        'mfg/production-orders',
        'mfg/work-orders',
        'mfg/routings',
        'mfg/work-centers',
        'mfg/quality',
        'mfg/capacity',
        'mfg/schedules',
        'hrm',
        'hrm/employees',
        'hrm/departments',
        'hrm/positions',
        'hrm/organization',
        'hrm/training',
        'hrm/performance',
        'hrm/promotions',
        'hrm/transfers',
        'hrm/goals',
        'hrm/competencies',
        'payroll',
        'payroll/dashboard',
        'payroll/batches',
        'payroll/cycles',
        'payroll/payslips',
        'payroll/salary-structures',
        'payroll/loans',
        'payroll/advances',
        'payroll/overtime',
        'qms',
        'qms/dashboard',
        'qms/plans',
        'qms/standards',
        'qms/checklists',
        'qms/inspections',
        'qms/defects',
        'qms/nonconformities',
        'qms/corrective-actions',
        'qms/preventive-actions',
        'qms/audits',
        'qms/complaints',
        'qms/supplier-quality',
        'dms',
        'dms/dashboard',
        'dms/repositories',
        'dms/folders',
        'dms/documents',
        'dms/versions',
        'dms/search',
        'dms/favorites',
        'dms/shares',
        'dms/retention',
        'dms/legal-holds',
        'dms/permissions',
        'dms/timeline',
        'dms/reports',
        'bi',
        'bi/dashboard',
        'bi/dashboards',
        'bi/kpis',
        'bi/reports',
        'bi/widgets',
        'bi/datasets',
        'bi/alerts',
        'bi/schedules',
        'bi/exports',
        'bi/trends',
        'bi/forecasts',
        'bi/scopes',
        'bi/analytics',
        'bi/timeline',
    ],

    /** Narrow form-post hooks (pathname substring → adapter action). */
    'form_hooks' => [
        ['match' => 'stock-movements', 'module' => 'inventory', 'action' => 'stock_movement.create'],
        ['match' => 'warehouse-transfers', 'module' => 'inventory', 'action' => 'warehouse_transfer.create'],
        ['match' => 'inventory-audits', 'module' => 'inventory', 'action' => 'stock_count.create'],
        ['match' => 'hr/attendance/bulk', 'module' => 'hr', 'action' => 'attendance.bulk'],
        ['match' => 'hr/attendance', 'module' => 'hr', 'action' => 'attendance.create'],
        ['match' => 'hr/leaves', 'module' => 'hr', 'action' => 'leave_request.draft'],
        ['match' => 'purchase-requests', 'module' => 'procurement', 'action' => 'purchase_request.draft'],
        ['match' => 'purchase-orders', 'module' => 'procurement', 'action' => 'purchase_order.draft'],
        ['match' => 'rfq', 'module' => 'procurement', 'action' => 'rfq.draft'],
        ['match' => 'goods-receipts', 'module' => 'procurement', 'action' => 'goods_receipt.receive'],
        ['match' => 'recruitment/candidates/create', 'module' => 'recruitment', 'action' => 'candidate.create'],
        ['match' => 'recruitment/candidates', 'module' => 'recruitment', 'action' => 'candidate.update'],
        ['match' => 'journal-entries/create', 'module' => 'accounting', 'action' => 'journal.create'],
        ['match' => 'journal-entries', 'module' => 'accounting', 'action' => 'journal.update'],
        ['match' => 'accounting/recurring/create', 'module' => 'accounting', 'action' => 'recurring.create'],
        ['match' => 'accounting/opening-balances', 'module' => 'accounting', 'action' => 'opening_balance.create'],
        ['match' => 'crm/leads/create', 'module' => 'crm', 'action' => 'lead.create'],
        ['match' => 'crm/leads', 'module' => 'crm', 'action' => 'lead.update'],
        ['match' => 'crm/tasks', 'module' => 'crm', 'action' => 'task.create'],
        ['match' => 'crm/meetings', 'module' => 'crm', 'action' => 'meeting.create'],
        ['match' => 'crm/campaigns', 'module' => 'crm', 'action' => 'campaign.create'],
        ['match' => 'crm/contacts', 'module' => 'crm', 'action' => 'contact.create'],
        ['match' => 'crm/companies', 'module' => 'crm', 'action' => 'company.create'],
        ['match' => 'projects/create', 'module' => 'projects', 'action' => 'project.create'],
        ['match' => 'projects/list', 'module' => 'projects', 'action' => 'project.update'],
        ['match' => 'projects/tasks', 'module' => 'projects', 'action' => 'task.create'],
        ['match' => 'projects/milestones', 'module' => 'projects', 'action' => 'milestone.create'],
        ['match' => 'projects/issues', 'module' => 'projects', 'action' => 'issue.create'],
        ['match' => 'projects/risks', 'module' => 'projects', 'action' => 'risk.create'],
        ['match' => 'projects/timesheets', 'module' => 'projects', 'action' => 'timesheet.create'],
        ['match' => 'eam/assets/create', 'module' => 'assets', 'action' => 'asset.create'],
        ['match' => 'eam/assets', 'module' => 'assets', 'action' => 'asset.update'],
        ['match' => 'eam/requests', 'module' => 'assets', 'action' => 'maintenance_request.create'],
        ['match' => 'eam/work-orders', 'module' => 'assets', 'action' => 'work_order.create'],
        ['match' => 'eam/maintenance', 'module' => 'assets', 'action' => 'maintenance_plan.create'],
        ['match' => 'eam/inspections', 'module' => 'assets', 'action' => 'inspection.create'],
        ['match' => 'approvals/requests/create', 'module' => 'approval', 'action' => 'approval_request.create'],
        ['match' => 'approvals/requests', 'module' => 'approval', 'action' => 'approval_request.update'],
        ['match' => 'approvals/requests/', 'module' => 'approval', 'action' => 'comment.create'],
        ['match' => 'eproc/suppliers/create', 'module' => 'procurement_enterprise', 'action' => 'supplier_profile.create'],
        ['match' => 'eproc/suppliers', 'module' => 'procurement_enterprise', 'action' => 'supplier_profile.update'],
        ['match' => 'eproc/tenders/create', 'module' => 'procurement_enterprise', 'action' => 'tender.create'],
        ['match' => 'eproc/contracts/create', 'module' => 'procurement_enterprise', 'action' => 'contract.create'],
        ['match' => 'eproc/qualification', 'module' => 'procurement_enterprise', 'action' => 'qualification.create'],
        ['match' => 'eproc/scorecards', 'module' => 'procurement_enterprise', 'action' => 'scorecard.create'],
        ['match' => 'eproc/portal', 'module' => 'procurement_enterprise', 'action' => 'portal_invite.create'],
        ['match' => 'eproc/collaboration', 'module' => 'procurement_enterprise', 'action' => 'collaboration.create'],
        ['match' => 'mfg/boms/create', 'module' => 'manufacturing', 'action' => 'bom.create'],
        ['match' => 'mfg/boms', 'module' => 'manufacturing', 'action' => 'bom.update'],
        ['match' => 'mfg/production-orders/create', 'module' => 'manufacturing', 'action' => 'production_order.create'],
        ['match' => 'mfg/production-orders', 'module' => 'manufacturing', 'action' => 'production_order.update'],
        ['match' => 'mfg/work-orders/create', 'module' => 'manufacturing', 'action' => 'work_order.create'],
        ['match' => 'mfg/work-orders', 'module' => 'manufacturing', 'action' => 'work_order.update'],
        ['match' => 'mfg/routings', 'module' => 'manufacturing', 'action' => 'routing.create'],
        ['match' => 'mfg/quality', 'module' => 'manufacturing', 'action' => 'quality_check.create'],
        ['match' => 'hrm/employees/create', 'module' => 'hr', 'action' => 'employee.create'],
        ['match' => 'hrm/employees', 'module' => 'hr', 'action' => 'employee.update'],
        ['match' => 'hrm/departments', 'module' => 'hr', 'action' => 'department.create'],
        ['match' => 'hrm/positions', 'module' => 'hr', 'action' => 'position.create'],
        ['match' => 'hrm/organization', 'module' => 'hr', 'action' => 'organization.create'],
        ['match' => 'hrm/training/create', 'module' => 'hr', 'action' => 'training.create'],
        ['match' => 'hrm/performance/create', 'module' => 'hr', 'action' => 'performance.create'],
        ['match' => 'hrm/goals', 'module' => 'hr', 'action' => 'goal.create'],
        ['match' => 'hrm/competencies', 'module' => 'hr', 'action' => 'competency.create'],
        ['match' => 'hrm/promotions', 'module' => 'hr', 'action' => 'promotion.create'],
        ['match' => 'hrm/transfers', 'module' => 'hr', 'action' => 'transfer.create'],
        ['match' => 'payroll/salary-structures', 'module' => 'payroll', 'action' => 'salary_structure.create'],
        ['match' => 'payroll/batches/create', 'module' => 'payroll', 'action' => 'payroll_batch.create'],
        ['match' => 'payroll/batches', 'module' => 'payroll', 'action' => 'payroll_batch.update'],
        ['match' => 'payroll/loans', 'module' => 'payroll', 'action' => 'loan.create'],
        ['match' => 'payroll/advances', 'module' => 'payroll', 'action' => 'advance.create'],
        ['match' => 'payroll/overtime', 'module' => 'payroll', 'action' => 'overtime.create'],
        ['match' => 'qms/inspections', 'module' => 'quality', 'action' => 'inspection.create'],
        ['match' => 'qms/checklists', 'module' => 'quality', 'action' => 'checklist.create'],
        ['match' => 'qms/audits', 'module' => 'quality', 'action' => 'audit.create'],
        ['match' => 'qms/defects', 'module' => 'quality', 'action' => 'defect.create'],
        ['match' => 'qms/nonconformities', 'module' => 'quality', 'action' => 'nonconformity.create'],
        ['match' => 'qms/corrective-actions', 'module' => 'quality', 'action' => 'corrective_action.create'],
        ['match' => 'qms/preventive-actions', 'module' => 'quality', 'action' => 'preventive_action.create'],
        ['match' => 'qms/complaints', 'module' => 'quality', 'action' => 'complaint.create'],
        ['match' => 'qms/supplier-quality', 'module' => 'quality', 'action' => 'supplier_quality.create'],
        ['match' => 'dms/repositories', 'module' => 'documents', 'action' => 'repository.create'],
        ['match' => 'dms/folders', 'module' => 'documents', 'action' => 'folder.create'],
        ['match' => 'dms/documents', 'module' => 'documents', 'action' => 'document.create'],
        ['match' => 'dms/shares', 'module' => 'documents', 'action' => 'share.create'],
        ['match' => 'dms/permissions', 'module' => 'documents', 'action' => 'permission.create'],
        ['match' => 'bi/dashboards', 'module' => 'bi', 'action' => 'dashboard.create'],
        ['match' => 'bi/kpis', 'module' => 'bi', 'action' => 'kpi.create'],
        ['match' => 'bi/reports', 'module' => 'bi', 'action' => 'report.create'],
        ['match' => 'bi/widgets', 'module' => 'bi', 'action' => 'widget.create'],
        ['match' => 'bi/datasets', 'module' => 'bi', 'action' => 'dataset.create'],
        ['match' => 'bi/alerts', 'module' => 'bi', 'action' => 'alert.create'],
        ['match' => 'bi/schedules', 'module' => 'bi', 'action' => 'schedule.create'],
        ['match' => 'bi/exports', 'module' => 'bi', 'action' => 'export.create'],
        ['match' => 'bi/trends', 'module' => 'bi', 'action' => 'trend.create'],
        ['match' => 'bi/forecasts', 'module' => 'bi', 'action' => 'forecast.create'],
        ['match' => 'bi/scopes', 'module' => 'bi', 'action' => 'scope.create'],
    ],
];
